import { NextResponse } from 'next/server';
import { createSupabaseServerClient } from '@/lib/supabase-server';
import { supabaseAdmin } from '@/lib/supabaseAdmin';
import { validateFormData } from '@/lib/forms/server-validation';
import { calculateServicePrice, type PricingRule } from '@/lib/forms/pricing';
import { MAX_ORDER_BODY_BYTES, validateFormDataShape } from '@/lib/security/request-limits';
import type { FormField, FormSchema } from '@/types/forms';

function normalizeSchema(value: unknown): FormSchema { let parsed=value; if(typeof parsed==='string'){try{parsed=JSON.parse(parsed)}catch{parsed=[]}} if(Array.isArray(parsed)) return {fields:parsed as FormSchema['fields']}; if(parsed&&typeof parsed==='object'&&Array.isArray((parsed as any).fields)) return parsed as FormSchema; return {fields:[]}; }
function normalizeRules(value: unknown): PricingRule[] { if(typeof value==='string'){try{value=JSON.parse(value)}catch{value=[]}} return Array.isArray(value)?value as PricingRule[]:[]; }
function mergeSchemas(parent: FormSchema, child: FormSchema): FormSchema { const seen=new Set<string>(); return {...child,fields:[...parent.fields,...child.fields].filter((f:any)=>{if(!f||typeof f!=='object')return false;const k=String(f.name||f.id||'').trim().toLowerCase();if(!k||seen.has(k))return false;seen.add(k);return true})}; }
function buildPricingData(fields: FormField[], validated: Record<string, unknown>): Record<string, unknown> { const out={...validated}; for(const field of fields){const value=validated[field.id];if(value===undefined)continue;out[field.name]=field.type==='repeatable'&&Array.isArray(value)&&field.fields?.length?value.map(row=>row&&typeof row==='object'?buildPricingData(field.fields||[],row as Record<string,unknown>):row):value;} return out; }
function generateTrackingCode(){return `TUS-${Date.now().toString().slice(-6)}-${Math.floor(100000+Math.random()*900000)}`;}
async function readBoundedJson(request:Request){const len=request.headers.get('content-length');if(len&&Number.isFinite(Number(len))&&Number(len)>MAX_ORDER_BODY_BYTES)throw new Error('REQUEST_BODY_TOO_LARGE');const body=await request.arrayBuffer();if(body.byteLength>MAX_ORDER_BODY_BYTES)throw new Error('REQUEST_BODY_TOO_LARGE');return JSON.parse(new TextDecoder().decode(body));}

export async function POST(request:Request):Promise<Response>{try{
 const userClient=await createSupabaseServerClient(); const {data:{user}}=await userClient.auth.getUser(); if(!user)return NextResponse.json({error:'برای ثبت سفارش ابتدا وارد حساب شوید.'},{status:401});
 const body=await readBoundedJson(request) as {serviceId?:string;formId?:string|null;formData?:Record<string,unknown>;idempotencyKey?:string};
 if(!body.serviceId||!body.formData||typeof body.formData!=='object'||Array.isArray(body.formData))return NextResponse.json({error:'اطلاعات فرم ناقص است.'},{status:400});
 if(!validateFormDataShape(body.formData))return NextResponse.json({error:'حجم یا ساختار اطلاعات فرم نامعتبر است.'},{status:413});
 const idempotencyKey=String(body.idempotencyKey||request.headers.get('x-idempotency-key')||'').trim();if(idempotencyKey.length>128)return NextResponse.json({error:'شناسه تکرارنشدنی نامعتبر است.'},{status:400});
 const db=supabaseAdmin();
 if(idempotencyKey){const {data:existing,error}=await db.from('orders').select('id,tracking_code,price,form_version_id').eq('user_id',user.id).eq('idempotency_key',idempotencyKey).maybeSingle();if(error)throw new Error(error.message);if(existing)return NextResponse.json({order:existing,idempotent:true});}
 const {data:service,error:serviceError}=await db.from('services').select('id,title,price,form_schema,is_active,parent_service_id,parent_form_id,pricing_rules').eq('id',body.serviceId).eq('is_active',true).maybeSingle();if(serviceError)throw new Error(serviceError.message);if(!service)return NextResponse.json({error:'خدمت انتخاب‌شده در دسترس نیست.'},{status:404});
 let schema=normalizeSchema(service.form_schema);let formId:string|null=body.formId??null;let formVersionId:string|null=null;let orderPrice=Number(service.price||0);const pricingRules=normalizeRules(service.pricing_rules);
 if(formId){const {data:cf,error}=await db.from('custom_forms').select('id,schema,service_id,is_public,price,active_version_id,parent_form_id').eq('id',formId).eq('service_id',service.id).eq('is_public',true).maybeSingle();if(error)throw new Error(error.message);if(!cf)return NextResponse.json({error:'فرم انتخاب‌شده معتبر نیست.'},{status:400});formId=cf.id;orderPrice=Number(cf.price??service.price??0);schema=normalizeSchema(cf.schema);if(cf.active_version_id){const {data:v,error:ve}=await db.from('form_versions').select('id,schema,price').eq('id',cf.active_version_id).eq('form_id',cf.id).maybeSingle();if(ve)throw new Error(ve.message);if(!v)return NextResponse.json({error:'نسخه فعال فرم پیدا نشد.'},{status:409});formVersionId=v.id;schema=normalizeSchema(v.schema);orderPrice=Number(v.price??orderPrice);}if(cf.parent_form_id||service.parent_form_id){const pid=cf.parent_form_id||service.parent_form_id;const {data:pf,error:pe}=await db.from('custom_forms').select('id,schema,is_public,active_version_id').eq('id',pid).eq('is_public',true).maybeSingle();if(pe)throw new Error(pe.message);if(pf){let ps=normalizeSchema(pf.schema);if(pf.active_version_id){const {data:pv,error:pve}=await db.from('form_versions').select('schema').eq('id',pf.active_version_id).eq('form_id',pf.id).maybeSingle();if(pve)throw new Error(pve.message);if(!pv)return NextResponse.json({error:'نسخه فعال فرم مادر پیدا نشد.'},{status:409});ps=normalizeSchema(pv.schema);}schema=mergeSchemas(ps,schema);}}}
 const validation=validateFormData(schema,body.formData);if(!validation.valid)return NextResponse.json({error:'اطلاعات فرم کامل یا معتبر نیست.',errors:validation.errors},{status:422});
 const finalPrice=calculateServicePrice(orderPrice,pricingRules,buildPricingData(schema.fields,validation.data));if(!Number.isFinite(finalPrice)||finalPrice<0)return NextResponse.json({error:'مبلغ سفارش نامعتبر است.'},{status:422});
 const {data:order,error:orderError}=await db.from('orders').insert({user_id:user.id,service_id:service.id,form_id:formId,form_version_id:formVersionId,idempotency_key:idempotencyKey||null,tracking_code:generateTrackingCode(),status:'registered',form_data:validation.data,form_schema_snapshot:schema,price:finalPrice}).select('id,tracking_code,price,form_version_id').single();
 if(orderError){if(orderError.code==='23505'&&idempotencyKey){const {data:concurrent}=await db.from('orders').select('id,tracking_code,price,form_version_id').eq('user_id',user.id).eq('idempotency_key',idempotencyKey).maybeSingle();if(concurrent)return NextResponse.json({order:concurrent,idempotent:true});}throw new Error(orderError.message);}return NextResponse.json({order});
}catch(error){if(error instanceof Error&&error.message==='REQUEST_BODY_TOO_LARGE')return NextResponse.json({error:'حجم درخواست بیش از حد مجاز است.'},{status:413});console.error('Order creation error:',error);return NextResponse.json({error:error instanceof Error?error.message:'خطایی هنگام ثبت سفارش رخ داد.'},{status:500});}}
