-- Tusan Website - Phase 2 service/form seed
-- Scope: vehicle + government/social-security + tax + insurance + university services.
-- Parent/child hierarchy and conditional rules remain intentionally excluded.
-- New services use price=0; existing prices are preserved.
-- Schemas use only field types currently supported by the Tusan form builder.

DO $$
DECLARE
  item jsonb;
  v_service_id uuid;
BEGIN
  FOR item IN SELECT value FROM jsonb_array_elements($services$
[
  {"title":"ثبت‌نام ایران‌خودرو","category":"خدمات خودرو","description":"ثبت اطلاعات متقاضی برای فرآیندهای فروش ایران‌خودرو.","icon":"🚗","fields":[{"id":"ikco_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"ikco_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"ikco_birth_date","type":"date","label":"تاریخ تولد","name":"birth_date","required":true},{"id":"ikco_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"ikco_address","type":"textarea","label":"آدرس","name":"address","required":true},{"id":"ikco_postal_code","type":"text","label":"کد پستی","name":"postal_code","required":true},{"id":"ikco_vehicle","type":"text","label":"خودرو/محصول موردنظر","name":"vehicle","required":true}]},
  {"title":"ثبت‌نام سایپا","category":"خدمات خودرو","description":"ثبت اطلاعات متقاضی برای فرآیندهای فروش سایپا.","icon":"🚘","fields":[{"id":"saipa_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"saipa_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"saipa_birth_date","type":"date","label":"تاریخ تولد","name":"birth_date","required":true},{"id":"saipa_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"saipa_address","type":"textarea","label":"آدرس","name":"address","required":true},{"id":"saipa_postal_code","type":"text","label":"کد پستی","name":"postal_code","required":true},{"id":"saipa_vehicle","type":"text","label":"خودرو/محصول موردنظر","name":"vehicle","required":true}]},
  {"title":"ثبت‌نام خودروهای وارداتی","category":"خدمات خودرو","description":"ثبت اطلاعات متقاضی برای فرآیندهای مربوط به خودروهای وارداتی.","icon":"🌐","fields":[{"id":"import_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"import_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"import_birth_date","type":"date","label":"تاریخ تولد","name":"birth_date","required":true},{"id":"import_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"import_postal_code","type":"text","label":"کد پستی","name":"postal_code","required":true},{"id":"import_vehicle","type":"text","label":"خودرو/محصول موردنظر","name":"vehicle","required":true}]},
  {"title":"ثبت‌نام خودروهای برقی","category":"خدمات خودرو","description":"ثبت اطلاعات متقاضی برای طرح‌های فروش خودروهای برقی.","icon":"🔋","fields":[{"id":"ev_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"ev_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"ev_birth_date","type":"date","label":"تاریخ تولد","name":"birth_date","required":true},{"id":"ev_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"ev_postal_code","type":"text","label":"کد پستی","name":"postal_code","required":true},{"id":"ev_vehicle","type":"text","label":"خودرو/محصول موردنظر","name":"vehicle","required":true}]},
  {"title":"ثبت‌نام طرح جوانی جمعیت خودرو","category":"خدمات خودرو","description":"ثبت درخواست در طرح حمایت از خانواده و جوانی جمعیت؛ شرایط اختصاصی طرح در زمان ثبت‌نام بررسی می‌شود.","icon":"👨‍👩‍👧","fields":[{"id":"young_national_code","type":"national_code","label":"کد ملی متقاضی","name":"national_code","required":true},{"id":"young_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"young_birth_date","type":"date","label":"تاریخ تولد","name":"birth_date","required":true},{"id":"young_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"young_child_birth_date","type":"date","label":"تاریخ تولد فرزند","name":"child_birth_date","required":true},{"id":"young_postal_code","type":"text","label":"کد پستی","name":"postal_code","required":true},{"id":"young_vehicle","type":"text","label":"خودرو/محصول موردنظر","name":"vehicle","required":true}]},
  {"title":"ثبت‌نام طرح فرسوده خودرو","category":"خدمات خودرو","description":"ثبت اطلاعات متقاضی طرح جایگزینی خودروهای فرسوده.","icon":"♻️","fields":[{"id":"scrap_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"scrap_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"scrap_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"scrap_vehicle_type","type":"text","label":"نوع خودرو فرسوده","name":"vehicle_type","required":true},{"id":"scrap_plate","type":"text","label":"شماره پلاک","name":"plate","required":true},{"id":"scrap_vin","type":"text","label":"VIN در صورت وجود","name":"vin","required":false}]},
  {"title":"نوبت تعویض پلاک","category":"خدمات خودرو","description":"ثبت اطلاعات لازم برای دریافت نوبت مرکز تعویض پلاک.","icon":"🔢","fields":[{"id":"plate_national_code","type":"national_code","label":"کد ملی مالک","name":"national_code","required":true},{"id":"plate_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"plate_number","type":"text","label":"شماره پلاک","name":"plate_number","required":true},{"id":"plate_vehicle_type","type":"text","label":"نوع خودرو","name":"vehicle_type","required":true},{"id":"plate_city","type":"text","label":"شهر/استان مرکز","name":"city","required":true},{"id":"plate_preferred_date","type":"date","label":"تاریخ ترجیحی","name":"preferred_date","required":false}]},
  {"title":"استعلام خلافی خودرو","category":"خدمات خودرو","description":"ثبت اطلاعات موردنیاز برای استعلام خلافی خودرو.","icon":"📋","fields":[{"id":"fine_national_code","type":"national_code","label":"کد ملی مالک","name":"national_code","required":true},{"id":"fine_plate","type":"text","label":"شماره پلاک","name":"plate_number","required":true}]},
  {"title":"پرداخت خلافی خودرو","category":"خدمات خودرو","description":"ثبت درخواست پرداخت خلافی خودرو پس از دریافت مبلغ قابل پرداخت.","icon":"💳","fields":[{"id":"payfine_national_code","type":"national_code","label":"کد ملی مالک","name":"national_code","required":true},{"id":"payfine_plate","type":"text","label":"شماره پلاک","name":"plate_number","required":true},{"id":"payfine_reference","type":"text","label":"شناسه/کد قبض در صورت وجود","name":"reference","required":false}]},
  {"title":"ثبت‌نام خدمات دولت الکترونیک","category":"خدمات دولتی و اداری","description":"ثبت درخواست ایجاد یا تکمیل حساب در یک سامانه دولتی مشخص.","icon":"🏛️","fields":[{"id":"gov_system","type":"text","label":"نام سامانه","name":"system_name","required":true},{"id":"gov_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"gov_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"gov_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"gov_request","type":"textarea","label":"شرح درخواست","name":"request_description","required":true}]},
  {"title":"پیگیری درخواست دولتی","category":"خدمات دولتی و اداری","description":"پیگیری یک درخواست ثبت‌شده در سامانه دولتی مشخص.","icon":"🔎","fields":[{"id":"govtrack_system","type":"text","label":"نام سامانه","name":"system_name","required":true},{"id":"govtrack_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"govtrack_tracking","type":"text","label":"کد رهگیری/شماره درخواست","name":"tracking_code","required":true}]},
  {"title":"ثبت‌نام تأمین اجتماعی","category":"خدمات تأمین اجتماعی","description":"ثبت درخواست ایجاد حساب و انجام خدمات اولیه تأمین اجتماعی.","icon":"🛡️","fields":[{"id":"ss_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"ss_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"ss_birth_date","type":"date","label":"تاریخ تولد","name":"birth_date","required":true},{"id":"ss_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"ss_postal_code","type":"text","label":"کد پستی","name":"postal_code","required":true},{"id":"ss_address","type":"textarea","label":"آدرس","name":"address","required":true}]},
  {"title":"دریافت سابقه بیمه تأمین اجتماعی","category":"خدمات تأمین اجتماعی","description":"ثبت درخواست دریافت سوابق بیمه‌شده.","icon":"📑","fields":[{"id":"history_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"history_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"history_insurance_no","type":"text","label":"شماره بیمه در صورت وجود","name":"insurance_number","required":false}]},
  {"title":"دریافت فیش حقوقی تأمین اجتماعی","category":"خدمات تأمین اجتماعی","description":"ثبت درخواست دریافت فیش حقوقی.","icon":"🧾","fields":[{"id":"pension_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"pension_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"pension_month","type":"text","label":"ماه/دوره موردنظر","name":"period","required":true}]},
  {"title":"ثبت‌نام در سامانه مالیاتی","category":"خدمات مالیاتی","description":"ثبت درخواست ایجاد یا تکمیل پرونده مالیاتی.","icon":"🧾","fields":[{"id":"tax_national_code","type":"national_code","label":"کد ملی/شناسه ملی","name":"national_or_entity_id","required":true},{"id":"tax_full_name","type":"text","label":"نام شخص/نام شرکت","name":"full_name","required":true},{"id":"tax_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"tax_activity","type":"text","label":"نوع فعالیت","name":"activity","required":true},{"id":"tax_postal_code","type":"text","label":"کد پستی محل فعالیت","name":"postal_code","required":true},{"id":"tax_address","type":"textarea","label":"آدرس محل فعالیت","name":"address","required":true}]},
  {"title":"تشکیل پرونده مالیاتی","category":"خدمات مالیاتی","description":"ثبت اطلاعات لازم برای تشکیل پرونده مالیاتی.","icon":"📂","fields":[{"id":"case_id","type":"text","label":"کد ملی/شناسه ملی","name":"national_or_entity_id","required":true},{"id":"case_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"case_activity","type":"text","label":"نوع فعالیت","name":"activity","required":true},{"id":"case_start_date","type":"date","label":"تاریخ شروع فعالیت","name":"activity_start_date","required":true},{"id":"case_postal_code","type":"text","label":"کد پستی","name":"postal_code","required":true},{"id":"case_address","type":"textarea","label":"آدرس","name":"address","required":true}]},
  {"title":"ثبت اظهارنامه مالیاتی","category":"خدمات مالیاتی","description":"ثبت درخواست تهیه و ارسال اظهارنامه؛ نوع اظهارنامه باید در زمان سفارش مشخص شود.","icon":"📊","fields":[{"id":"decl_id","type":"text","label":"کد ملی/شناسه ملی","name":"national_or_entity_id","required":true},{"id":"decl_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"decl_type","type":"select","label":"نوع اظهارنامه","name":"declaration_type","required":true,"options":[{"label":"اشخاص حقیقی","value":"individual"},{"label":"اشخاص حقوقی","value":"legal"},{"label":"ارزش افزوده","value":"vat"}]},{"id":"decl_year","type":"number","label":"سال مالی","name":"financial_year","required":true},{"id":"decl_description","type":"textarea","label":"توضیحات","name":"description","required":false}]},
  {"title":"ثبت‌نام سامانه مؤدیان","category":"خدمات مالیاتی","description":"ثبت درخواست فعال‌سازی/تکمیل کارپوشه و خدمات پایه سامانه مؤدیان.","icon":"💼","fields":[{"id":"mytax_id","type":"text","label":"کد ملی/شناسه ملی","name":"national_or_entity_id","required":true},{"id":"mytax_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"mytax_tax_number","type":"text","label":"شماره پرونده/شماره اقتصادی در صورت وجود","name":"tax_number","required":false},{"id":"mytax_request","type":"textarea","label":"شرح درخواست","name":"request_description","required":true}]},
  {"title":"ارسال صورتحساب الکترونیکی","category":"خدمات مالیاتی","description":"ثبت درخواست آماده‌سازی/ارسال صورتحساب الکترونیکی.","icon":"🧮","fields":[{"id":"invoice_id","type":"text","label":"کد ملی/شناسه ملی مؤدی","name":"national_or_entity_id","required":true},{"id":"invoice_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"invoice_count","type":"number","label":"تعداد صورتحساب","name":"invoice_count","required":true},{"id":"invoice_description","type":"textarea","label":"توضیحات","name":"description","required":false}]},
  {"title":"ثبت‌نام بیمه سلامت","category":"خدمات بیمه","description":"ثبت درخواست ثبت‌نام یا پیگیری پوشش بیمه سلامت.","icon":"🏥","fields":[{"id":"health_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"health_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"health_birth_date","type":"date","label":"تاریخ تولد","name":"birth_date","required":true},{"id":"health_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"health_address","type":"textarea","label":"آدرس","name":"address","required":false}]},
  {"title":"استعلام بیمه شخص ثالث","category":"خدمات بیمه","description":"ثبت اطلاعات لازم برای استعلام وضعیت بیمه شخص ثالث.","icon":"🚗","fields":[{"id":"third_party_plate","type":"text","label":"شماره پلاک","name":"plate_number","required":true},{"id":"third_party_national_code","type":"national_code","label":"کد ملی مالک","name":"national_code","required":true}]},
  {"title":"تمدید بیمه خودرو","category":"خدمات بیمه","description":"ثبت درخواست تمدید بیمه خودرو.","icon":"🛡️","fields":[{"id":"renew_plate","type":"text","label":"شماره پلاک","name":"plate_number","required":true},{"id":"renew_national_code","type":"national_code","label":"کد ملی مالک","name":"national_code","required":true},{"id":"renew_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"renew_insurance","type":"text","label":"شماره بیمه‌نامه قبلی در صورت وجود","name":"previous_policy_number","required":false}]},
  {"title":"ثبت‌نام دانشگاه آزاد","category":"خدمات آموزشی و دانشگاهی","description":"ثبت اطلاعات اولیه متقاضی برای فرآیند ثبت‌نام دانشگاه آزاد.","icon":"🎓","fields":[{"id":"iau_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"iau_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"iau_birth_date","type":"date","label":"تاریخ تولد","name":"birth_date","required":true},{"id":"iau_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"iau_degree","type":"text","label":"مقطع تحصیلی","name":"degree","required":true},{"id":"iau_field","type":"text","label":"رشته تحصیلی","name":"field_of_study","required":true},{"id":"iau_gpa","type":"number","label":"معدل","name":"gpa","required":true},{"id":"iau_city","type":"text","label":"شهر محل سکونت","name":"city","required":true}]},
  {"title":"ثبت‌نام دانشگاه پیام نور","category":"خدمات آموزشی و دانشگاهی","description":"ثبت اطلاعات اولیه متقاضی برای فرآیند ثبت‌نام دانشگاه پیام نور.","icon":"🎓","fields":[{"id":"pnu_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"pnu_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"pnu_birth_date","type":"date","label":"تاریخ تولد","name":"birth_date","required":true},{"id":"pnu_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"pnu_degree","type":"text","label":"مقطع تحصیلی","name":"degree","required":true},{"id":"pnu_field","type":"text","label":"رشته تحصیلی","name":"field_of_study","required":true}]},
  {"title":"ثبت‌نام دانشگاه علمی‌کاربردی","category":"خدمات آموزشی و دانشگاهی","description":"ثبت اطلاعات اولیه متقاضی برای فرآیند ثبت‌نام دانشگاه علمی‌کاربردی.","icon":"🎓","fields":[{"id":"uast_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"uast_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"uast_birth_date","type":"date","label":"تاریخ تولد","name":"birth_date","required":true},{"id":"uast_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"uast_degree","type":"text","label":"مقطع تحصیلی","name":"degree","required":true},{"id":"uast_field","type":"text","label":"رشته تحصیلی","name":"field_of_study","required":true}]},
  {"title":"ثبت‌نام بدون کنکور","category":"خدمات آموزشی و دانشگاهی","description":"ثبت درخواست پذیرش بدون آزمون؛ دانشگاه و مقطع باید مشخص شود.","icon":"📚","fields":[{"id":"noc_exam_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"noc_exam_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"noc_exam_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"noc_exam_university","type":"text","label":"دانشگاه موردنظر","name":"university","required":true},{"id":"noc_exam_degree","type":"text","label":"مقطع","name":"degree","required":true},{"id":"noc_exam_field","type":"text","label":"رشته موردنظر","name":"field_of_study","required":true},{"id":"noc_exam_gpa","type":"number","label":"معدل","name":"gpa","required":true}]},
  {"title":"ثبت درخواست نقل‌وانتقال دانشگاه","category":"خدمات آموزشی و دانشگاهی","description":"ثبت اطلاعات اولیه برای درخواست انتقال یا مهمانی دانشگاه.","icon":"🔄","fields":[{"id":"transfer_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"transfer_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"transfer_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"transfer_current_university","type":"text","label":"دانشگاه مبدأ","name":"current_university","required":true},{"id":"transfer_target_university","type":"text","label":"دانشگاه مقصد","name":"target_university","required":true},{"id":"transfer_reason","type":"textarea","label":"دلیل درخواست","name":"reason","required":true}]},
  {"title":"درخواست وام دانشجویی","category":"خدمات دانشجویی","description":"ثبت اطلاعات اولیه برای درخواست تسهیلات دانشجویی.","icon":"💰","fields":[{"id":"loan_national_code","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"loan_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"loan_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"loan_university","type":"text","label":"دانشگاه","name":"university","required":true},{"id":"loan_student_no","type":"text","label":"شماره دانشجویی","name":"student_number","required":true},{"id":"loan_type","type":"text","label":"نوع وام","name":"loan_type","required":true}]}
]$services$::jsonb) LOOP
    SELECT id INTO v_service_id FROM services WHERE title = item->>'title' LIMIT 1;
    IF v_service_id IS NULL THEN
      INSERT INTO services (title,category,description,price,icon,is_active,form_schema,parent_service_id)
      VALUES (item->>'title',item->>'category',item->>'description',0,item->>'icon',true,item->'fields',NULL)
      RETURNING id INTO v_service_id;
    ELSE
      UPDATE services SET category=item->>'category',description=item->>'description',icon=item->>'icon',is_active=true,form_schema=item->'fields' WHERE id=v_service_id;
    END IF;
    IF EXISTS (SELECT 1 FROM custom_forms WHERE service_id=v_service_id AND title=item->>'title') THEN
      UPDATE custom_forms SET description=item->>'description',schema=item->'fields',is_public=true,form_type='normal',parent_form_id=NULL WHERE service_id=v_service_id AND title=item->>'title';
    ELSE
      INSERT INTO custom_forms (title,description,schema,created_by,is_public,form_type,parent_form_id,service_id,sort_order)
      VALUES (item->>'title',item->>'description',item->'fields',NULL,true,'normal',NULL,v_service_id,0);
    END IF;
  END LOOP;
END $$;

-- Notes:
-- 1) طرح‌های خودرو، مالیاتی و دانشگاهی می‌توانند بر اساس دفترچه/بخشنامه دوره‌ای فیلدهای اختصاصی داشته باشند.
-- 2) فیلدهای شرطی عمداً در این seed فعال نشده‌اند و از Form Builder تنظیم خواهند شد.
-- 3) اطلاعات حساس مانند password, OTP و card credentials جمع‌آوری نمی‌شوند.
