-- Tusan Website - Phase 4 service/form seed
-- Scope: business + banking/loans + real estate + travel + photos/documents + resume/employment + printing + domain/IT + AI/account assistance.
-- Social media services are intentionally excluded because the project already has a dedicated social-services integration.
DO $$
DECLARE item jsonb; v_service_id uuid;
BEGIN
FOR item IN SELECT value FROM jsonb_array_elements($services$
[
{"title":"ثبت شرکت با مسئولیت محدود","category":"خدمات کسب‌وکار","description":"جمع‌آوری اطلاعات لازم برای شروع فرآیند ثبت شرکت با مسئولیت محدود.","icon":"🏢","fields":[{"id":"llc_name","type":"text","label":"نام پیشنهادی شرکت","name":"company_name","required":true},{"id":"llc_partners","type":"number","label":"تعداد شرکا","name":"partner_count","required":true},{"id":"llc_activity","type":"textarea","label":"موضوع فعالیت","name":"activity","required":true},{"id":"llc_address","type":"textarea","label":"آدرس مرکز اصلی","name":"address","required":true},{"id":"llc_postal","type":"text","label":"کد پستی","name":"postal_code","required":true},{"id":"llc_mobile","type":"phone","label":"شماره تماس متقاضی","name":"mobile","required":true}]},
{"title":"ثبت شرکت سهامی خاص","category":"خدمات کسب‌وکار","description":"جمع‌آوری اطلاعات لازم برای شروع فرآیند ثبت شرکت سهامی خاص.","icon":"🏢","fields":[{"id":"jsc_name","type":"text","label":"نام پیشنهادی شرکت","name":"company_name","required":true},{"id":"jsc_members","type":"number","label":"تعداد اعضا/سهامداران","name":"member_count","required":true},{"id":"jsc_activity","type":"textarea","label":"موضوع فعالیت","name":"activity","required":true},{"id":"jsc_capital","type":"number","label":"سرمایه ثبتی پیشنهادی","name":"capital","required":true},{"id":"jsc_address","type":"textarea","label":"آدرس مرکز اصلی","name":"address","required":true},{"id":"jsc_mobile","type":"phone","label":"شماره تماس","name":"mobile","required":true}]},
{"title":"تغییرات شرکت","category":"خدمات کسب‌وکار","description":"ثبت اطلاعات اولیه برای انجام تغییرات ثبتی شرکت.","icon":"🔄","fields":[{"id":"company_change_name","type":"text","label":"نام شرکت","name":"company_name","required":true},{"id":"company_change_id","type":"text","label":"شناسه ملی شرکت","name":"national_entity_id","required":true},{"id":"company_change_type","type":"text","label":"نوع تغییر","name":"change_type","required":true},{"id":"company_change_notes","type":"textarea","label":"شرح تغییرات","name":"description","required":true},{"id":"company_change_mobile","type":"phone","label":"شماره تماس","name":"mobile","required":true}]},
{"title":"درخواست مجوز کسب‌وکار","category":"خدمات مجوز","description":"ثبت اطلاعات اولیه برای پیگیری مجوز کسب‌وکار مشخص.","icon":"📜","fields":[{"id":"permit_national","type":"text","label":"کد ملی/شناسه ملی","name":"national_or_entity_id","required":true},{"id":"permit_business","type":"text","label":"نوع کسب‌وکار","name":"business_type","required":true},{"id":"permit_title","type":"text","label":"عنوان مجوز","name":"permit_title","required":true},{"id":"permit_city","type":"text","label":"شهر محل فعالیت","name":"city","required":true},{"id":"permit_mobile","type":"phone","label":"شماره تماس","name":"mobile","required":true},{"id":"permit_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"ثبت درخواست افتتاح حساب","category":"خدمات بانکی و مالی","description":"ثبت اطلاعات اولیه برای راهنمایی و انجام فرآیند افتتاح حساب آنلاین.","icon":"🏦","fields":[{"id":"bank_account_fullname","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"bank_account_national","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"bank_account_birth","type":"date","label":"تاریخ تولد","name":"birth_date","required":true},{"id":"bank_account_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"bank_account_bank","type":"text","label":"بانک موردنظر","name":"bank","required":true}]},
{"title":"ثبت درخواست تسهیلات","category":"تسهیلات و وام","description":"ثبت اطلاعات اولیه برای پیگیری درخواست تسهیلات؛ شرایط نهایی وابسته به بانک/طرح است.","icon":"💰","fields":[{"id":"loanreq_fullname","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"loanreq_national","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"loanreq_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"loanreq_bank","type":"text","label":"بانک/مؤسسه","name":"bank","required":true},{"id":"loanreq_amount","type":"number","label":"مبلغ تقریبی تسهیلات","name":"amount","required":true},{"id":"loanreq_purpose","type":"textarea","label":"هدف/نوع تسهیلات","name":"purpose","required":true}]},
{"title":"ثبت اطلاعات ملک در سامانه املاک","category":"خدمات املاک","description":"ثبت اطلاعات پایه ملک و مالک برای خدمات مرتبط با سامانه املاک و اسکان.","icon":"🏠","fields":[{"id":"amlak_national","type":"national_code","label":"کد ملی مالک/سرپرست","name":"national_code","required":true},{"id":"amlak_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"amlak_postal","type":"text","label":"کد پستی ملک","name":"postal_code","required":true},{"id":"amlak_address","type":"textarea","label":"نشانی ملک","name":"address","required":true},{"id":"amlak_property_type","type":"text","label":"نوع ملک","name":"property_type","required":true}]},
{"title":"ثبت اقامتگاه","category":"خدمات املاک","description":"ثبت اطلاعات اقامتگاه و محل سکونت.","icon":"🏡","fields":[{"id":"residence_national","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"residence_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"residence_postal","type":"text","label":"کد پستی","name":"postal_code","required":true},{"id":"residence_address","type":"textarea","label":"نشانی","name":"address","required":true},{"id":"residence_status","type":"select","label":"وضعیت سکونت","name":"residence_status","required":true,"options":[{"label":"مالک","value":"owner"},{"label":"مستأجر","value":"tenant"},{"label":"سایر","value":"other"}]}]},
{"title":"آماده‌سازی قرارداد اجاره","category":"خدمات اجاره و قرارداد","description":"تنظیم و آماده‌سازی متن قرارداد اجاره بر اساس اطلاعات طرفین و ملک.","icon":"📄","fields":[{"id":"rent_landlord","type":"text","label":"نام موجر","name":"landlord","required":true},{"id":"rent_tenant","type":"text","label":"نام مستأجر","name":"tenant","required":true},{"id":"rent_property","type":"textarea","label":"مشخصات ملک","name":"property_description","required":true},{"id":"rent_amount","type":"number","label":"مبلغ ودیعه","name":"deposit","required":true},{"id":"rent_monthly","type":"number","label":"اجاره ماهانه","name":"monthly_rent","required":true},{"id":"rent_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"خدمات بلیت سفر","category":"خدمات سفر و گردشگری","description":"ثبت درخواست جستجو و رزرو بلیت؛ نوع وسیله و مسیر باید مشخص شود.","icon":"✈️","fields":[{"id":"travel_passenger","type":"text","label":"نام و نام خانوادگی مسافر","name":"passenger_name","required":true},{"id":"travel_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"travel_mode","type":"select","label":"نوع سفر","name":"mode","required":true,"options":[{"label":"هواپیما","value":"flight"},{"label":"قطار","value":"train"},{"label":"اتوبوس","value":"bus"}]},{"id":"travel_origin","type":"text","label":"مبدأ","name":"origin","required":true},{"id":"travel_destination","type":"text","label":"مقصد","name":"destination","required":true},{"id":"travel_date","type":"date","label":"تاریخ سفر","name":"travel_date","required":true}]},
{"title":"پیگیری گذرنامه","category":"خدمات گذرنامه","description":"ثبت اطلاعات لازم برای پیگیری وضعیت گذرنامه.","icon":"🛂","fields":[{"id":"passport_national","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"passport_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"passport_tracking","type":"text","label":"کد رهگیری/شماره درخواست","name":"tracking_code","required":true}]},
{"title":"عکس پرسنلی ۳×۴","category":"خدمات عکس و مدارک","description":"آماده‌سازی عکس پرسنلی با ابعاد و استاندارد موردنظر.","icon":"📸","fields":[{"id":"photo34_count","type":"number","label":"تعداد خروجی","name":"count","required":true},{"id":"photo34_usage","type":"text","label":"کاربرد عکس","name":"usage","required":true},{"id":"photo34_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"آماده‌سازی عکس پاسپورت/ویزا","category":"خدمات عکس و مدارک","description":"تنظیم ابعاد و خروجی عکس مطابق نیاز مدرک یا سامانه.","icon":"📷","fields":[{"id":"passportphoto_usage","type":"text","label":"کشور/نوع مدرک","name":"document_type","required":true},{"id":"passportphoto_count","type":"number","label":"تعداد خروجی","name":"count","required":true},{"id":"passportphoto_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"ویرایش و حذف پس‌زمینه عکس","category":"ویرایش عکس","description":"حذف یا اصلاح پس‌زمینه و آماده‌سازی تصویر.","icon":"🖼️","fields":[{"id":"bgedit_usage","type":"text","label":"کاربرد تصویر","name":"usage","required":true},{"id":"bgedit_background","type":"text","label":"پس‌زمینه موردنظر","name":"background","required":false},{"id":"bgedit_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"اسکن و تبدیل مدارک به PDF","category":"خدمات مدارک","description":"مرتب‌سازی و آماده‌سازی تصاویر/اسکن مدارک در قالب PDF.","icon":"📄","fields":[{"id":"scan_doc_count","type":"number","label":"تعداد مدارک/صفحات","name":"page_count","required":true},{"id":"scan_order","type":"textarea","label":"ترتیب مدارک","name":"order_notes","required":false},{"id":"scan_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"مرتب‌سازی و ادغام مدارک","category":"خدمات مدارک","description":"مرتب‌سازی چند تصویر یا PDF و تولید فایل نهایی.","icon":"📑","fields":[{"id":"docs_count","type":"number","label":"تعداد فایل/مدرک","name":"file_count","required":true},{"id":"docs_order","type":"textarea","label":"ترتیب موردنظر","name":"order_notes","required":true}]},
{"title":"آماده‌سازی مدارک برای سامانه","category":"خدمات مدارک","description":"تنظیم حجم، فرمت و ترتیب مدارک برای بارگذاری در سامانه مشخص.","icon":"📤","fields":[{"id":"upload_system","type":"text","label":"نام سامانه","name":"system_name","required":true},{"id":"upload_docs","type":"textarea","label":"نوع مدارک","name":"documents","required":true},{"id":"upload_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"طراحی رزومه فارسی","category":"رزومه و استخدام","description":"طراحی رزومه فارسی بر اساس اطلاعات حرفه‌ای مشتری.","icon":"💼","fields":[{"id":"cvfa_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"cvfa_job","type":"text","label":"عنوان شغلی","name":"job_title","required":true},{"id":"cvfa_experience","type":"textarea","label":"سوابق کاری","name":"experience","required":true},{"id":"cvfa_education","type":"textarea","label":"سوابق تحصیلی","name":"education","required":true}]},
{"title":"طراحی رزومه انگلیسی","category":"رزومه و استخدام","description":"طراحی رزومه انگلیسی برای کاربرد شغلی یا تحصیلی.","icon":"🌍","fields":[{"id":"cven_name","type":"text","label":"Full Name","name":"full_name","required":true},{"id":"cven_job","type":"text","label":"Job Title","name":"job_title","required":true},{"id":"cven_experience","type":"textarea","label":"Work Experience","name":"experience","required":true},{"id":"cven_education","type":"textarea","label":"Education","name":"education","required":true}]},
{"title":"ثبت‌نام آزمون استخدامی","category":"خدمات استخدام","description":"ثبت اطلاعات اولیه برای ثبت‌نام آزمون استخدامی مشخص.","icon":"🧑‍💼","fields":[{"id":"emp_national","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"emp_full_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"emp_birth","type":"date","label":"تاریخ تولد","name":"birth_date","required":true},{"id":"emp_mobile","type":"phone","label":"شماره موبایل","name":"mobile","required":true},{"id":"emp_exam","type":"text","label":"عنوان آزمون","name":"exam","required":true},{"id":"emp_degree","type":"text","label":"مدرک تحصیلی","name":"degree","required":true},{"id":"emp_field","type":"text","label":"رشته تحصیلی","name":"field","required":true}]},
{"title":"چاپ سیاه‌وسفید","category":"خدمات چاپ و خروجی","description":"ثبت سفارش چاپ سیاه‌وسفید.","icon":"🖨️","fields":[{"id":"bw_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"bw_copies","type":"number","label":"تعداد نسخه","name":"copies","required":true},{"id":"bw_size","type":"select","label":"اندازه کاغذ","name":"paper_size","required":true,"options":[{"label":"A4","value":"A4"},{"label":"A3","value":"A3"}]},{"id":"bw_sides","type":"select","label":"چاپ","name":"sides","required":true,"options":[{"label":"یک‌رو","value":"single"},{"label":"دو‌رو","value":"double"}]}]},
{"title":"چاپ رنگی","category":"خدمات چاپ و خروجی","description":"ثبت سفارش چاپ رنگی.","icon":"🖨️","fields":[{"id":"color_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"color_copies","type":"number","label":"تعداد نسخه","name":"copies","required":true},{"id":"color_size","type":"select","label":"اندازه کاغذ","name":"paper_size","required":true,"options":[{"label":"A4","value":"A4"},{"label":"A3","value":"A3"}]},{"id":"color_sides","type":"select","label":"چاپ","name":"sides","required":true,"options":[{"label":"یک‌رو","value":"single"},{"label":"دو‌رو","value":"double"}]}]},
{"title":"چاپ پایان‌نامه","category":"خدمات چاپ دانشگاهی","description":"ثبت سفارش چاپ پایان‌نامه.","icon":"🎓","fields":[{"id":"thprint_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"thprint_copies","type":"number","label":"تعداد نسخه","name":"copies","required":true},{"id":"thprint_binding","type":"text","label":"نوع صحافی","name":"binding","required":true},{"id":"thprint_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"ثبت دامنه","category":"خدمات دامنه و سایت","description":"ثبت درخواست ثبت دامنه با پسوند مشخص.","icon":"🌐","fields":[{"id":"domain_name","type":"text","label":"نام دامنه پیشنهادی","name":"domain","required":true},{"id":"domain_extension","type":"text","label":"پسوند","name":"extension","required":true},{"id":"domain_owner","type":"text","label":"نام مالک دامنه","name":"owner_name","required":true},{"id":"domain_mobile","type":"phone","label":"شماره تماس","name":"mobile","required":true}]},
{"title":"تنظیم DNS و اتصال دامنه","category":"خدمات دامنه و سایت","description":"تنظیم رکوردهای DNS و اتصال دامنه به سرویس مقصد.","icon":"🔗","fields":[{"id":"dns_domain","type":"text","label":"دامنه","name":"domain","required":true},{"id":"dns_target","type":"text","label":"سرویس/مقصد","name":"target","required":true},{"id":"dns_records","type":"textarea","label":"رکوردهای موردنیاز","name":"records","required":false}]},
{"title":"راه‌اندازی ایمیل سازمانی","category":"خدمات دامنه و سایت","description":"ثبت درخواست ایجاد ایمیل سازمانی روی دامنه.","icon":"✉️","fields":[{"id":"email_domain","type":"text","label":"دامنه","name":"domain","required":true},{"id":"email_count","type":"number","label":"تعداد حساب‌ها","name":"account_count","required":true},{"id":"email_names","type":"textarea","label":"نام حساب‌ها","name":"account_names","required":true}]},
{"title":"خدمات Microsoft Office","category":"خدمات نرم‌افزاری","description":"کمک در تنظیم، قالب‌بندی و رفع مشکلات Word/Excel/PowerPoint.","icon":"💻","fields":[{"id":"office_app","type":"select","label":"نرم‌افزار","name":"application","required":true,"options":[{"label":"Word","value":"word"},{"label":"Excel","value":"excel"},{"label":"PowerPoint","value":"powerpoint"}]},{"id":"office_task","type":"textarea","label":"شرح مشکل/درخواست","name":"task","required":true}]},
{"title":"تولید متن با هوش مصنوعی","category":"خدمات هوش مصنوعی","description":"تولید و بازنویسی محتوای متنی برای کاربردهای مجاز.","icon":"🤖","fields":[{"id":"ai_text_topic","type":"text","label":"موضوع","name":"topic","required":true},{"id":"ai_text_type","type":"select","label":"نوع محتوا","name":"content_type","required":true,"options":[{"label":"مقاله","value":"article"},{"label":"کپشن","value":"caption"},{"label":"متن تبلیغاتی","value":"ad"},{"label":"توضیحات محصول","value":"product"}]},{"id":"ai_text_length","type":"number","label":"طول تقریبی (کلمه)","name":"word_count","required":false},{"id":"ai_text_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"خلاصه‌سازی و تحلیل فایل","category":"خدمات هوش مصنوعی","description":"استخراج نکات، خلاصه و تحلیل محتوای فایل‌های مجاز.","icon":"🧠","fields":[{"id":"ai_file_type","type":"text","label":"نوع فایل","name":"file_type","required":true},{"id":"ai_file_goal","type":"textarea","label":"هدف تحلیل","name":"goal","required":true},{"id":"ai_file_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"راهنمای بازیابی حساب کاربری","category":"امنیت و حساب‌های کاربری","description":"راهنمایی و انجام مراحل مجاز بازیابی حساب کاربری.","icon":"🔐","fields":[{"id":"account_platform","type":"text","label":"نام سرویس/سامانه","name":"platform","required":true},{"id":"account_username","type":"text","label":"شناسه کاربری/ایمیل","name":"username","required":true},{"id":"account_mobile","type":"phone","label":"شماره موبایل مرتبط","name":"mobile","required":false},{"id":"account_notes","type":"textarea","label":"شرح مشکل","name":"problem","required":true}]},
{"title":"فعال‌سازی احراز هویت دومرحله‌ای","category":"امنیت و حساب‌های کاربری","description":"راهنمای فعال‌سازی 2FA برای حساب کاربری.","icon":"🔒","fields":[{"id":"twofa_platform","type":"text","label":"نام سرویس","name":"platform","required":true},{"id":"twofa_method","type":"select","label":"روش موردنظر","name":"method","required":true,"options":[{"label":"برنامه Authenticator","value":"authenticator"},{"label":"پیامک","value":"sms"},{"label":"سایر روش‌های رسمی","value":"other"}]},{"id":"twofa_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]}
]$services$::jsonb) LOOP
SELECT id INTO v_service_id FROM services WHERE title=item->>'title' LIMIT 1;
IF v_service_id IS NULL THEN INSERT INTO services(title,category,description,price,icon,is_active,form_schema,parent_service_id) VALUES(item->>'title',item->>'category',item->>'description',0,item->>'icon',true,item->'fields',NULL) RETURNING id INTO v_service_id;
ELSE UPDATE services SET category=item->>'category',description=item->>'description',icon=item->>'icon',is_active=true,form_schema=item->'fields' WHERE id=v_service_id; END IF;
IF EXISTS(SELECT 1 FROM custom_forms WHERE service_id=v_service_id AND title=item->>'title') THEN UPDATE custom_forms SET description=item->>'description',schema=item->'fields',is_public=true,form_type='normal',parent_form_id=NULL WHERE service_id=v_service_id AND title=item->>'title';
ELSE INSERT INTO custom_forms(title,description,schema,created_by,is_public,form_type,parent_form_id,service_id,sort_order) VALUES(item->>'title',item->>'description',item->'fields',NULL,true,'normal',NULL,v_service_id,0); END IF;
END LOOP; END $$;
