-- Tusan Website - Phase 3 service/form seed
-- Scope: typing/text + research/editing + graphic/design + file/computer + data entry.
-- Parent/child and conditional rules are intentionally excluded.
DO $$
DECLARE item jsonb; v_service_id uuid;
BEGIN
FOR item IN SELECT value FROM jsonb_array_elements($services$
[
{"title":"تایپ فارسی","category":"تایپ و خدمات متنی","description":"تایپ و تبدیل محتوای فارسی به فایل قابل ویرایش.","icon":"⌨️","fields":[{"id":"type_fa_source","type":"text","label":"نوع فایل ورودی","name":"source_type","required":true},{"id":"type_fa_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"type_fa_output","type":"select","label":"خروجی","name":"output","required":true,"options":[{"label":"Word","value":"word"},{"label":"Text","value":"text"}]},{"id":"type_fa_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"تایپ انگلیسی","category":"تایپ و خدمات متنی","description":"تایپ محتوای انگلیسی و تحویل فایل قابل ویرایش.","icon":"⌨️","fields":[{"id":"type_en_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"type_en_output","type":"select","label":"خروجی","name":"output","required":true,"options":[{"label":"Word","value":"word"},{"label":"Text","value":"text"}]},{"id":"type_en_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"تایپ پایان‌نامه","category":"تایپ و خدمات متنی","description":"تایپ و آماده‌سازی متن پایان‌نامه برای ویرایش بعدی.","icon":"🎓","fields":[{"id":"thesis_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"thesis_language","type":"select","label":"زبان","name":"language","required":true,"options":[{"label":"فارسی","value":"fa"},{"label":"انگلیسی","value":"en"}]},{"id":"thesis_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"تایپ دست‌نوشته","category":"تایپ و خدمات متنی","description":"تبدیل دست‌نوشته خوانا به متن دیجیتال.","icon":"✍️","fields":[{"id":"hand_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"hand_quality","type":"select","label":"کیفیت دست‌نوشته","name":"quality","required":true,"options":[{"label":"خوانا","value":"clear"},{"label":"متوسط","value":"medium"},{"label":"نیازمند بررسی","value":"review"}]},{"id":"hand_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"ویراستاری فارسی","category":"ویرایش متن","description":"ویرایش نگارشی و زبانی متن فارسی.","icon":"📝","fields":[{"id":"edit_fa_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"edit_fa_level","type":"select","label":"سطح ویرایش","name":"editing_level","required":true,"options":[{"label":"نگارشی","value":"copy"},{"label":"ادبی","value":"literary"},{"label":"تخصصی","value":"technical"}]},{"id":"edit_fa_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"ویراستاری انگلیسی","category":"ویرایش متن","description":"ویرایش زبانی و نگارشی متن انگلیسی.","icon":"📝","fields":[{"id":"edit_en_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"edit_en_level","type":"select","label":"سطح ویرایش","name":"editing_level","required":true,"options":[{"label":"گرامری","value":"grammar"},{"label":"آکادمیک","value":"academic"},{"label":"تخصصی","value":"technical"}]},{"id":"edit_en_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"قالب‌بندی Word","category":"ویرایش متن","description":"تنظیم قالب، فونت، فاصله، Heading و ساختار سند Word.","icon":"📄","fields":[{"id":"word_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"word_requirements","type":"textarea","label":"الزامات قالب‌بندی","name":"requirements","required":true}]},
{"title":"تحقیق دانش‌آموزی","category":"تحقیق و پژوهش","description":"پشتیبانی در گردآوری و تنظیم تحقیق دانش‌آموزی.","icon":"🔬","fields":[{"id":"research_school_topic","type":"text","label":"موضوع تحقیق","name":"topic","required":true},{"id":"research_school_grade","type":"text","label":"مقطع/پایه","name":"grade","required":true},{"id":"research_school_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"research_school_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"جستجوی منابع علمی","category":"پژوهش","description":"جستجو و فهرست‌کردن منابع علمی مرتبط با موضوع پژوهش.","icon":"🔎","fields":[{"id":"refs_topic","type":"text","label":"موضوع","name":"topic","required":true},{"id":"refs_count","type":"number","label":"تعداد منابع موردنظر","name":"source_count","required":true},{"id":"refs_language","type":"select","label":"زبان منابع","name":"language","required":true,"options":[{"label":"فارسی","value":"fa"},{"label":"انگلیسی","value":"en"},{"label":"هر دو","value":"both"}]},{"id":"refs_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"خلاصه‌سازی مقاله","category":"پژوهش","description":"خلاصه‌سازی و استخراج نکات اصلی مقاله.","icon":"📚","fields":[{"id":"summary_pages","type":"number","label":"تعداد صفحات مقاله","name":"page_count","required":true},{"id":"summary_output","type":"select","label":"نوع خروجی","name":"output_type","required":true,"options":[{"label":"خلاصه فارسی","value":"fa"},{"label":"خلاصه انگلیسی","value":"en"}]},{"id":"summary_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"تدوین پروپوزال","category":"پژوهش","description":"خدمات نگارشی و ساختاری پروپوزال پژوهشی.","icon":"📑","fields":[{"id":"proposal_topic","type":"text","label":"عنوان/موضوع پژوهش","name":"topic","required":true},{"id":"proposal_field","type":"text","label":"رشته/گرایش","name":"field","required":true},{"id":"proposal_university","type":"text","label":"دانشگاه","name":"university","required":true},{"id":"proposal_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"طراحی پاورپوینت دانشجویی","category":"طراحی پاورپوینت","description":"طراحی ارائه دانشجویی با ساختار و قالب حرفه‌ای.","icon":"📊","fields":[{"id":"ppt_student_title","type":"text","label":"عنوان ارائه","name":"title","required":true},{"id":"ppt_student_slides","type":"number","label":"تعداد اسلاید","name":"slide_count","required":true},{"id":"ppt_student_language","type":"select","label":"زبان","name":"language","required":true,"options":[{"label":"فارسی","value":"fa"},{"label":"انگلیسی","value":"en"}]},{"id":"ppt_student_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"پاورپوینت دفاع پایان‌نامه","category":"طراحی پاورپوینت","description":"طراحی ساختار ارائه دفاع پایان‌نامه.","icon":"🎓","fields":[{"id":"ppt_defense_title","type":"text","label":"عنوان پایان‌نامه","name":"title","required":true},{"id":"ppt_defense_slides","type":"number","label":"تعداد اسلاید تقریبی","name":"slide_count","required":true},{"id":"ppt_defense_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"طراحی پوستر","category":"طراحی گرافیکی","description":"طراحی پوستر تبلیغاتی یا اطلاع‌رسانی.","icon":"🎨","fields":[{"id":"poster_size","type":"text","label":"ابعاد","name":"size","required":true},{"id":"poster_title","type":"text","label":"عنوان/متن اصلی","name":"title","required":true},{"id":"poster_usage","type":"select","label":"کاربرد","name":"usage","required":true,"options":[{"label":"چاپ","value":"print"},{"label":"شبکه اجتماعی","value":"social"},{"label":"هر دو","value":"both"}]},{"id":"poster_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"طراحی کارت ویزیت","category":"طراحی گرافیکی","description":"طراحی کارت ویزیت شخصی یا سازمانی.","icon":"💼","fields":[{"id":"card_name","type":"text","label":"نام/نام مجموعه","name":"name","required":true},{"id":"card_phone","type":"phone","label":"شماره تماس","name":"phone","required":true},{"id":"card_role","type":"text","label":"سمت/عنوان","name":"role","required":false},{"id":"card_notes","type":"textarea","label":"اطلاعات تکمیلی","name":"notes","required":false}]},
{"title":"طراحی رزومه","category":"طراحی گرافیکی","description":"طراحی رزومه حرفه‌ای بر اساس اطلاعات ارائه‌شده.","icon":"📄","fields":[{"id":"design_cv_name","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"design_cv_role","type":"text","label":"عنوان شغلی","name":"job_title","required":true},{"id":"design_cv_language","type":"select","label":"زبان","name":"language","required":true,"options":[{"label":"فارسی","value":"fa"},{"label":"انگلیسی","value":"en"}]},{"id":"design_cv_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"PDF به Word","category":"خدمات فایل و کامپیوتر","description":"تبدیل فایل PDF به سند Word قابل ویرایش.","icon":"📄","fields":[{"id":"pdfword_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"pdfword_quality","type":"select","label":"نوع PDF","name":"pdf_type","required":true,"options":[{"label":"متنی","value":"text"},{"label":"اسکن‌شده","value":"scan"}]},{"id":"pdfword_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"PDF به Excel","category":"خدمات فایل و کامپیوتر","description":"تبدیل جداول یا داده‌های PDF به Excel.","icon":"📊","fields":[{"id":"pdfexcel_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"pdfexcel_tables","type":"number","label":"تعداد تقریبی جداول","name":"table_count","required":false},{"id":"pdfexcel_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"ادغام PDF","category":"خدمات فایل و کامپیوتر","description":"ادغام چند فایل PDF در یک فایل.","icon":"🔗","fields":[{"id":"merge_pdf_count","type":"number","label":"تعداد فایل‌ها","name":"file_count","required":true},{"id":"merge_pdf_order","type":"textarea","label":"ترتیب فایل‌ها/توضیحات","name":"order_notes","required":false}]},
{"title":"تقسیم PDF","category":"خدمات فایل و کامپیوتر","description":"تقسیم یک PDF به چند فایل.","icon":"✂️","fields":[{"id":"split_pdf_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"split_pdf_ranges","type":"textarea","label":"بازه‌های صفحات","name":"page_ranges","required":true}]},
{"title":"فشرده‌سازی PDF","category":"خدمات فایل و کامپیوتر","description":"کاهش حجم PDF با حفظ کیفیت مناسب.","icon":"🗜️","fields":[{"id":"compress_pdf_size","type":"number","label":"حجم تقریبی فایل (MB)","name":"file_size_mb","required":true},{"id":"compress_pdf_target","type":"number","label":"حجم هدف تقریبی (MB)","name":"target_size_mb","required":false}]},
{"title":"خدمات Excel","category":"خدمات فایل و کامپیوتر","description":"ورود اطلاعات، فرمول‌نویسی و تنظیم فایل Excel.","icon":"📊","fields":[{"id":"excel_type","type":"select","label":"نوع خدمت","name":"service_type","required":true,"options":[{"label":"ورود اطلاعات","value":"data_entry"},{"label":"فرمول‌نویسی","value":"formula"},{"label":"مرتب‌سازی/پاک‌سازی","value":"cleanup"},{"label":"نمودار","value":"chart"}]},{"id":"excel_rows","type":"number","label":"تعداد تقریبی ردیف","name":"row_count","required":false},{"id":"excel_notes","type":"textarea","label":"توضیحات","name":"notes","required":true}]},
{"title":"ورود اطلاعات از PDF به Excel","category":"خدمات داده و ورود اطلاعات","description":"انتقال داده‌های ساختاریافته از PDF به Excel.","icon":"📥","fields":[{"id":"data_pdf_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"data_pdf_rows","type":"number","label":"تعداد تقریبی ردیف","name":"row_count","required":false},{"id":"data_pdf_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"ورود اطلاعات محصولات","category":"خدمات داده و ورود اطلاعات","description":"ورود اطلاعات کالا یا محصولات به فایل یا فرم مشخص.","icon":"📦","fields":[{"id":"products_count","type":"number","label":"تعداد محصولات","name":"product_count","required":true},{"id":"products_source","type":"text","label":"منبع اطلاعات","name":"source","required":true},{"id":"products_fields","type":"textarea","label":"فیلدهای موردنیاز","name":"fields_required","required":true}]},
{"title":"پاک‌سازی داده","category":"خدمات داده و ورود اطلاعات","description":"پاک‌سازی، حذف موارد تکراری و استانداردسازی داده‌ها.","icon":"🧹","fields":[{"id":"clean_rows","type":"number","label":"تعداد تقریبی رکورد","name":"row_count","required":true},{"id":"clean_tasks","type":"textarea","label":"موارد موردنیاز","name":"tasks","required":true}]},
{"title":"تهیه گزارش داده","category":"خدمات داده و ورود اطلاعات","description":"ساخت گزارش از داده‌های ارائه‌شده.","icon":"📈","fields":[{"id":"report_rows","type":"number","label":"تعداد تقریبی رکورد","name":"row_count","required":true},{"id":"report_goal","type":"textarea","label":"هدف گزارش","name":"goal","required":true},{"id":"report_output","type":"select","label":"خروجی","name":"output","required":true,"options":[{"label":"Excel","value":"excel"},{"label":"PDF","value":"pdf"},{"label":"Excel و PDF","value":"both"}]}]}
]$services$::jsonb) LOOP
SELECT id INTO v_service_id FROM services WHERE title=item->>'title' LIMIT 1;
IF v_service_id IS NULL THEN INSERT INTO services(title,category,description,price,icon,is_active,form_schema,parent_service_id) VALUES(item->>'title',item->>'category',item->>'description',0,item->>'icon',true,item->'fields',NULL) RETURNING id INTO v_service_id;
ELSE UPDATE services SET category=item->>'category',description=item->>'description',icon=item->>'icon',is_active=true,form_schema=item->'fields' WHERE id=v_service_id; END IF;
IF EXISTS(SELECT 1 FROM custom_forms WHERE service_id=v_service_id AND title=item->>'title') THEN UPDATE custom_forms SET description=item->>'description',schema=item->'fields',is_public=true,form_type='normal',parent_form_id=NULL WHERE service_id=v_service_id AND title=item->>'title';
ELSE INSERT INTO custom_forms(title,description,schema,created_by,is_public,form_type,parent_form_id,service_id,sort_order) VALUES(item->>'title',item->>'description',item->'fields',NULL,true,'normal',NULL,v_service_id,0); END IF;
END LOOP; END $$;
