-- Tusan Website - Phase 5 service/form seed
-- Remaining practical services from the catalog: article/editing, social design, Word/Excel utilities, banking follow-up, contract/PDF output, web/technical work and additional AI services.
-- Social media engagement services are NOT duplicated here; the dedicated social-services module owns those orders.
DO $$
DECLARE item jsonb; v_service_id uuid;
BEGIN
FOR item IN SELECT value FROM jsonb_array_elements($services$
[
{"title":"نگارش مقاله","category":"مقاله و پژوهش","description":"خدمات نگارشی و ساختاری مقاله برای کاربردهای مجاز پژوهشی.","icon":"📝","fields":[{"id":"article_topic","type":"text","label":"موضوع مقاله","name":"topic","required":true},{"id":"article_field","type":"text","label":"رشته/حوزه","name":"field","required":true},{"id":"article_type","type":"select","label":"نوع مقاله","name":"article_type","required":true,"options":[{"label":"مروری","value":"review"},{"label":"پژوهشی","value":"research"},{"label":"علمی-تخصصی","value":"technical"}]},{"id":"article_notes","type":"textarea","label":"توضیحات و الزامات","name":"notes","required":false}]},
{"title":"ویرایش مقاله","category":"مقاله و پژوهش","description":"ویرایش نگارشی، ساختاری و قالب‌بندی مقاله.","icon":"✏️","fields":[{"id":"article_edit_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"article_edit_type","type":"select","label":"نوع ویرایش","name":"editing_type","required":true,"options":[{"label":"نگارشی","value":"copy"},{"label":"علمی/ساختاری","value":"academic"},{"label":"قالب‌بندی","value":"formatting"}]},{"id":"article_edit_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"قالب‌بندی مقاله برای ارسال","category":"مقاله و پژوهش","description":"تنظیم مقاله مطابق راهنمای نویسندگان نشریه/همایش.","icon":"📄","fields":[{"id":"format_journal","type":"text","label":"نام نشریه/همایش","name":"journal","required":true},{"id":"format_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"format_notes","type":"textarea","label":"الزامات قالب","name":"requirements","required":false}]},
{"title":"تبدیل پایان‌نامه به مقاله","category":"مقاله و پژوهش","description":"استخراج و تنظیم ساختار مقاله از پایان‌نامه با رویکرد آموزشی/نگارشی.","icon":"🎓","fields":[{"id":"thesis_article_title","type":"text","label":"عنوان پایان‌نامه","name":"thesis_title","required":true},{"id":"thesis_article_field","type":"text","label":"رشته","name":"field","required":true},{"id":"thesis_article_pages","type":"number","label":"تعداد صفحات پایان‌نامه","name":"page_count","required":true},{"id":"thesis_article_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"ترجمه مقاله","category":"مقاله و پژوهش","description":"ترجمه مقاله یا متن تخصصی.","icon":"🌐","fields":[{"id":"translate_article_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"translate_article_from","type":"select","label":"زبان مبدأ","name":"source_language","required":true,"options":[{"label":"فارسی","value":"fa"},{"label":"انگلیسی","value":"en"},{"label":"سایر","value":"other"}]},{"id":"translate_article_to","type":"select","label":"زبان مقصد","name":"target_language","required":true,"options":[{"label":"فارسی","value":"fa"},{"label":"انگلیسی","value":"en"},{"label":"سایر","value":"other"}]},{"id":"translate_article_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"طراحی تراکت","category":"طراحی گرافیکی","description":"طراحی تراکت تبلیغاتی یا اطلاع‌رسانی.","icon":"🎨","fields":[{"id":"flyer_size","type":"text","label":"ابعاد","name":"size","required":true},{"id":"flyer_title","type":"text","label":"عنوان","name":"title","required":true},{"id":"flyer_content","type":"textarea","label":"متن و اطلاعات","name":"content","required":true},{"id":"flyer_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"طراحی بنر","category":"طراحی گرافیکی","description":"طراحی بنر برای چاپ یا استفاده دیجیتال.","icon":"🖼️","fields":[{"id":"banner_size","type":"text","label":"ابعاد","name":"size","required":true},{"id":"banner_title","type":"text","label":"عنوان","name":"title","required":true},{"id":"banner_content","type":"textarea","label":"متن بنر","name":"content","required":true},{"id":"banner_usage","type":"select","label":"کاربرد","name":"usage","required":true,"options":[{"label":"چاپ","value":"print"},{"label":"وب","value":"web"},{"label":"شبکه اجتماعی","value":"social"}]}]},
{"title":"طراحی پست اینستاگرام","category":"طراحی شبکه اجتماعی","description":"طراحی گرافیکی پست برای شبکه اجتماعی.","icon":"📱","fields":[{"id":"igpost_size","type":"text","label":"ابعاد/نسبت تصویر","name":"size","required":true},{"id":"igpost_title","type":"text","label":"موضوع/عنوان","name":"title","required":true},{"id":"igpost_content","type":"textarea","label":"متن روی طرح","name":"content","required":false},{"id":"igpost_count","type":"number","label":"تعداد طرح","name":"count","required":true}]},
{"title":"طراحی استوری","category":"طراحی شبکه اجتماعی","description":"طراحی استوری برای شبکه اجتماعی.","icon":"📱","fields":[{"id":"story_title","type":"text","label":"موضوع","name":"title","required":true},{"id":"story_content","type":"textarea","label":"متن/اطلاعات","name":"content","required":true},{"id":"story_count","type":"number","label":"تعداد استوری","name":"count","required":true}]},
{"title":"طراحی Thumbnail","category":"طراحی شبکه اجتماعی","description":"طراحی تصویر کاور ویدیو/محتوا.","icon":"▶️","fields":[{"id":"thumb_title","type":"text","label":"عنوان محتوا","name":"title","required":true},{"id":"thumb_platform","type":"text","label":"پلتفرم","name":"platform","required":true},{"id":"thumb_count","type":"number","label":"تعداد طرح","name":"count","required":true}]},
{"title":"تنظیم صفحه Word","category":"خدمات Word","description":"تنظیم حاشیه، اندازه کاغذ، فونت و صفحه‌بندی Word.","icon":"📄","fields":[{"id":"wordsetup_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"wordsetup_requirements","type":"textarea","label":"الزامات","name":"requirements","required":true}]},
{"title":"ایجاد فهرست خودکار Word","category":"خدمات Word","description":"تنظیم Heading و فهرست مطالب خودکار.","icon":"📑","fields":[{"id":"toc_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"toc_levels","type":"number","label":"تعداد سطوح فهرست","name":"heading_levels","required":false}]},
{"title":"تنظیم منابع پایان‌نامه","category":"خدمات Word","description":"تنظیم و یکدست‌سازی بخش منابع پایان‌نامه.","icon":"📚","fields":[{"id":"refs_count2","type":"number","label":"تعداد منابع","name":"source_count","required":true},{"id":"refs_style","type":"text","label":"شیوه استناد","name":"citation_style","required":true},{"id":"refs_notes2","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"فرمول‌نویسی Excel","category":"خدمات Excel","description":"طراحی و اصلاح فرمول‌های Excel.","icon":"📊","fields":[{"id":"formula_cells","type":"number","label":"تعداد تقریبی سلول/ردیف","name":"cell_count","required":false},{"id":"formula_goal","type":"textarea","label":"شرح محاسبات","name":"goal","required":true}]},
{"title":"ساخت نمودار Excel","category":"خدمات Excel","description":"ساخت نمودار و گزارش تصویری از داده‌های Excel.","icon":"📈","fields":[{"id":"chart_type","type":"text","label":"نوع نمودار","name":"chart_type","required":true},{"id":"chart_goal","type":"textarea","label":"هدف نمودار","name":"goal","required":true}]},
{"title":"تکمیل فرم‌های بانکی","category":"خدمات بانکی و مالی","description":"کمک در تکمیل فرم‌های بانکی با اطلاعات ارائه‌شده توسط مشتری.","icon":"🏦","fields":[{"id":"bankform_bank","type":"text","label":"نام بانک","name":"bank","required":true},{"id":"bankform_type","type":"text","label":"نوع فرم","name":"form_type","required":true},{"id":"bankform_fullname","type":"text","label":"نام و نام خانوادگی","name":"full_name","required":true},{"id":"bankform_national","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"bankform_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"پیگیری درخواست تسهیلات","category":"تسهیلات و وام","description":"پیگیری درخواست ثبت‌شده تسهیلات.","icon":"🔎","fields":[{"id":"loantrack_bank","type":"text","label":"بانک/مؤسسه","name":"bank","required":true},{"id":"loantrack_national","type":"national_code","label":"کد ملی","name":"national_code","required":true},{"id":"loantrack_reference","type":"text","label":"شماره درخواست/رهگیری","name":"tracking_code","required":true}]},
{"title":"تبدیل قرارداد به PDF","category":"خدمات املاک","description":"تبدیل و آماده‌سازی قرارداد برای خروجی PDF.","icon":"📄","fields":[{"id":"contractpdf_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"contractpdf_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"راه‌اندازی سایت ساده","category":"خدمات وب","description":"طراحی/راه‌اندازی سایت ساده یا صفحه معرفی.","icon":"🌐","fields":[{"id":"site_title","type":"text","label":"نام سایت","name":"site_name","required":true},{"id":"site_pages","type":"number","label":"تعداد صفحات","name":"page_count","required":true},{"id":"site_domain","type":"text","label":"دامنه در صورت وجود","name":"domain","required":false},{"id":"site_features","type":"textarea","label":"امکانات موردنیاز","name":"features","required":true}]},
{"title":"طراحی Landing Page","category":"خدمات وب","description":"طراحی صفحه فرود برای معرفی یا کمپین.","icon":"🖥️","fields":[{"id":"landing_title","type":"text","label":"عنوان پروژه","name":"title","required":true},{"id":"landing_goal","type":"textarea","label":"هدف صفحه","name":"goal","required":true},{"id":"landing_sections","type":"number","label":"تعداد بخش‌ها","name":"section_count","required":false},{"id":"landing_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"رفع خطای سایت","category":"خدمات فنی","description":"بررسی و رفع خطاهای عمومی سایت در محدوده دسترسی مجاز.","icon":"🛠️","fields":[{"id":"bug_url","type":"text","label":"آدرس سایت","name":"url","required":true},{"id":"bug_error","type":"textarea","label":"شرح خطا","name":"error_description","required":true},{"id":"bug_environment","type":"text","label":"محیط/فناوری در صورت اطلاع","name":"environment","required":false}]},
{"title":"خدمات HTML/CSS","category":"خدمات برنامه‌نویسی و فنی","description":"اصلاح یا پیاده‌سازی تغییرات HTML/CSS.","icon":"💻","fields":[{"id":"htmlcss_task","type":"textarea","label":"شرح تغییر","name":"task","required":true},{"id":"htmlcss_url","type":"text","label":"آدرس پروژه در صورت وجود","name":"url","required":false}]},
{"title":"اتوماسیون ساده فایل و Excel","category":"خدمات برنامه‌نویسی و فنی","description":"ساخت اتوماسیون ساده برای پردازش فایل یا داده.","icon":"⚙️","fields":[{"id":"auto_goal","type":"textarea","label":"هدف اتوماسیون","name":"goal","required":true},{"id":"auto_input","type":"text","label":"نوع فایل ورودی","name":"input_type","required":true},{"id":"auto_output","type":"text","label":"خروجی موردنظر","name":"output_type","required":true}]},
{"title":"بازنویسی متن با AI","category":"خدمات هوش مصنوعی","description":"بازنویسی و بهبود متن با توجه به لحن و هدف مشخص.","icon":"🤖","fields":[{"id":"rewrite_goal","type":"text","label":"هدف بازنویسی","name":"goal","required":true},{"id":"rewrite_tone","type":"text","label":"لحن موردنظر","name":"tone","required":true},{"id":"rewrite_notes","type":"textarea","label":"توضیحات","name":"notes","required":false}]},
{"title":"تولید محتوای شبکه اجتماعی با AI","category":"تولید محتوای AI","description":"تولید ایده، کپشن و محتوای متنی شبکه اجتماعی.","icon":"✨","fields":[{"id":"a_social_platform","type":"text","label":"پلتفرم","name":"platform","required":true},{"id":"a_social_topic","type":"text","label":"موضوع","name":"topic","required":true},{"id":"a_social_count","type":"number","label":"تعداد محتوا","name":"count","required":true},{"id":"a_social_tone","type":"text","label":"لحن","name":"tone","required":false}]},
{"title":"تولید توضیحات محصول با AI","category":"تولید محتوای AI","description":"تولید متن معرفی و توضیحات محصول.","icon":"🛍️","fields":[{"id":"a_product_name","type":"text","label":"نام محصول","name":"product_name","required":true},{"id":"a_product_features","type":"textarea","label":"ویژگی‌های محصول","name":"features","required":true},{"id":"a_product_length","type":"number","label":"طول تقریبی متن","name":"word_count","required":false}]},
{"title":"ساخت ارائه با AI","category":"خدمات هوش مصنوعی","description":"کمک در ساخت ساختار و محتوای ارائه با ابزارهای هوش مصنوعی.","icon":"🧠","fields":[{"id":"ai_presentation_topic","type":"text","label":"موضوع ارائه","name":"topic","required":true},{"id":"ai_presentation_slides","type":"number","label":"تعداد اسلاید","name":"slide_count","required":true},{"id":"ai_presentation_audience","type":"text","label":"مخاطب","name":"audience","required":false}]},
{"title":"رفع خطاهای ثبت‌نام و احراز هویت","category":"امنیت و حساب‌های کاربری","description":"بررسی خطاهای عمومی فرآیند ثبت‌نام و احراز هویت در سامانه‌های مجاز.","icon":"🔐","fields":[{"id":"auth_platform","type":"text","label":"نام سامانه","name":"platform","required":true},{"id":"auth_national","type":"national_code","label":"کد ملی در صورت نیاز","name":"national_code","required":false},{"id":"auth_error","type":"textarea","label":"شرح خطا","name":"error","required":true}]}
]$services$::jsonb) LOOP
SELECT id INTO v_service_id FROM services WHERE title=item->>'title' LIMIT 1;
IF v_service_id IS NULL THEN INSERT INTO services(title,category,description,price,icon,is_active,form_schema,parent_service_id) VALUES(item->>'title',item->>'category',item->>'description',0,item->>'icon',true,item->'fields',NULL) RETURNING id INTO v_service_id;
ELSE UPDATE services SET category=item->>'category',description=item->>'description',icon=item->>'icon',is_active=true,form_schema=item->'fields' WHERE id=v_service_id; END IF;
IF EXISTS(SELECT 1 FROM custom_forms WHERE service_id=v_service_id AND title=item->>'title') THEN UPDATE custom_forms SET description=item->>'description',schema=item->'fields',is_public=true,form_type='normal',parent_form_id=NULL WHERE service_id=v_service_id AND title=item->>'title';
ELSE INSERT INTO custom_forms(title,description,schema,created_by,is_public,form_type,parent_form_id,service_id,sort_order) VALUES(item->>'title',item->>'description',item->'fields',NULL,true,'normal',NULL,v_service_id,0); END IF;
END LOOP; END $$;
