"use client";

import { ChangeEvent, PointerEvent, useEffect, useRef, useState } from "react";
import "@fontsource/vazirmatn/400.css";
import "@fontsource/vazirmatn/700.css";
import "@fontsource/vazirmatn/900.css";
import "@fontsource/estedad/400.css";
import "@fontsource/estedad/700.css";
import "@fontsource/estedad/900.css";
import "@fontsource/lalezar/400.css";
import "@fontsource/noto-naskh-arabic/400.css";
import "@fontsource/noto-naskh-arabic/700.css";
import "@fontsource/noto-sans-arabic/400.css";
import "@fontsource/noto-sans-arabic/700.css";
import "@fontsource/noto-sans-arabic/900.css";

type Theme = "election" | "bold" | "school" | "clean" | "bwClassic" | "bwMinimal";
type FontId = "Vazirmatn" | "Estedad" | "Lalezar" | "Noto Naskh Arabic" | "Noto Sans Arabic";
type ElementKind = "ballot" | "check" | "star" | "ribbon" | "pencil" | "school" | "voteBadge" | "circle" | "square";
type GraphicElement = { id:number; kind:ElementKind; x:number; y:number; w:number; h:number; rotation:number; opacity:number; color:string; text?:string };

type ThemeConfig = { title:string; desc:string; bg:string; accent:string; text:string; muted:string; monochrome?:boolean; layout:"badge"|"diagonal"|"friendly"|"clean"|"bwClassic"|"bwMinimal" };

const SITE_URL = "https://tusancn.ir";
const SITE_NAME = "کافی‌نت توسن";
const W = 1240;
const H = 1754;

const fonts: { id: FontId; title: string }[] = [
  { id:"Vazirmatn", title:"وزیرمتن" }, { id:"Estedad", title:"استعداد" }, { id:"Lalezar", title:"لاله‌زار" },
  { id:"Noto Naskh Arabic", title:"نوتو نسخ عربی" }, { id:"Noto Sans Arabic", title:"نوتو سنس عربی" },
];
const themes: Record<Theme,ThemeConfig> = {
  election:{title:"انتخاباتی",desc:"مخصوص شورای دانش‌آموزی",bg:"#fff7ed",accent:"#dc2626",text:"#171717",muted:"#525252",layout:"badge"},
  bold:{title:"جسور",desc:"تیتر بزرگ و پرانرژی",bg:"#eff6ff",accent:"#2563eb",text:"#172033",muted:"#475569",layout:"diagonal"},
  school:{title:"شاد مدرسه‌ای",desc:"مناسب دانش‌آموزان",bg:"#f0fdf4",accent:"#059669",text:"#17332a",muted:"#527267",layout:"friendly"},
  clean:{title:"تمیز",desc:"ساده و حرفه‌ای",bg:"#fff",accent:"#111827",text:"#111827",muted:"#6b7280",layout:"clean"},
  bwClassic:{title:"سیاه و سفید کلاسیک",desc:"کم‌جوهر و مناسب پرینتر",bg:"#fff",accent:"#111",text:"#111",muted:"#444",monochrome:true,layout:"bwClassic"},
  bwMinimal:{title:"سیاه و سفید مینیمال",desc:"چاپ اقتصادی و خوانا",bg:"#fff",accent:"#000",text:"#111",muted:"#555",monochrome:true,layout:"bwMinimal"},
};
const elementLabels: Record<ElementKind,string> = {
  ballot:"برگه رأی", check:"تیک تأیید", star:"ستاره", ribbon:"روبان", pencil:"مداد", school:"مدرسه", voteBadge:"رأی من", circle:"دایره", square:"کادر",
};

function waitForFont(font:FontId){const weights=font==="Lalezar"?["400"]:["400","700","900"];return Promise.all(weights.map(w=>document.fonts.load(`${w} 40px "${font}"`))).then(()=>document.fonts.ready);}
function roundedRect(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){const q=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q);ctx.closePath();}
function fitText(ctx:CanvasRenderingContext2D,text:string,maxWidth:number,start:number,family:string,weight=800){let size=start;while(size>20){ctx.font=`${weight} ${size}px "${family}"`;if(ctx.measureText(text).width<=maxWidth)return size;size-=2;}return size;}
function wrapText(ctx:CanvasRenderingContext2D,text:string,maxWidth:number){const words=text.split(/\s+/).filter(Boolean);const lines:string[]=[];let line="";for(const word of words){const candidate=line?`${line} ${word}`:word;if(ctx.measureText(candidate).width<=maxWidth||!line)line=candidate;else{lines.push(line);line=word;}}if(line)lines.push(line);return lines;}

function drawGraphic(ctx:CanvasRenderingContext2D,e:GraphicElement,family:string,mono:boolean){
  ctx.save();ctx.translate(e.x,e.y);ctx.rotate(e.rotation*Math.PI/180);ctx.globalAlpha=e.opacity;ctx.strokeStyle=e.color;ctx.fillStyle=e.color;ctx.lineWidth=Math.max(4,e.w*0.035);ctx.lineJoin="round";
  const s=Math.min(e.w,e.h);
  if(e.kind==="check"){ctx.strokeStyle=e.color;ctx.lineWidth=Math.max(8,s*.12);ctx.beginPath();ctx.moveTo(-e.w*.35,0);ctx.lineTo(-e.w*.08,e.h*.28);ctx.lineTo(e.w*.42,-e.h*.35);ctx.stroke();}
  else if(e.kind==="star"){ctx.beginPath();for(let i=0;i<10;i++){const r=i%2?s*.5:s*.22;const a=-Math.PI/2+i*Math.PI/5;const x=Math.cos(a)*r,y=Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath();ctx.fill();}
  else if(e.kind==="ballot"){ctx.fillStyle=mono?"#fff":"#fff";ctx.strokeStyle=e.color;ctx.lineWidth=Math.max(4,s*.035);roundedRect(ctx,-e.w/2,-e.h/2,e.w,e.h,18);ctx.fill();ctx.stroke();ctx.strokeStyle=e.color;ctx.beginPath();ctx.moveTo(-e.w*.28,-e.h*.15);ctx.lineTo(e.w*.28,-e.h*.15);ctx.moveTo(-e.w*.28,0);ctx.lineTo(e.w*.2,0);ctx.moveTo(-e.w*.28,e.h*.15);ctx.lineTo(e.w*.1,e.h*.15);ctx.stroke();ctx.lineWidth=Math.max(5,s*.06);ctx.beginPath();ctx.moveTo(e.w*.18,e.h*.05);ctx.lineTo(e.w*.27,e.h*.14);ctx.lineTo(e.w*.43,-e.h*.08);ctx.stroke();}
  else if(e.kind==="ribbon"){ctx.fillStyle=e.color;ctx.beginPath();ctx.moveTo(-e.w/2,-e.h*.32);ctx.lineTo(e.w/2,-e.h*.32);ctx.lineTo(e.w*.35,e.h*.18);ctx.lineTo(e.w*.1,e.h*.03);ctx.lineTo(0,e.h*.38);ctx.lineTo(-e.w*.1,e.h*.03);ctx.lineTo(-e.w*.35,e.h*.18);ctx.closePath();ctx.fill();if(e.text){ctx.fillStyle="#fff";ctx.font=`800 ${Math.max(18,s*.18)}px "${family}"`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(e.text,0,-e.h*.1);}}
  else if(e.kind==="pencil"){ctx.rotate(-Math.PI/4);ctx.fillStyle=e.color;ctx.fillRect(-e.w*.38,-e.h*.12,e.w*.7,e.h*.24);ctx.fillStyle="#fbbf24";ctx.beginPath();ctx.moveTo(e.w*.32,-e.h*.12);ctx.lineTo(e.w*.5,0);ctx.lineTo(e.w*.32,e.h*.12);ctx.fill();ctx.fillStyle="#f8fafc";ctx.fillRect(-e.w*.43,-e.h*.12,e.w*.1,e.h*.24);}
  else if(e.kind==="school"){ctx.fillStyle=e.color;ctx.beginPath();ctx.moveTo(-e.w*.48,-e.h*.05);ctx.lineTo(0,-e.h*.42);ctx.lineTo(e.w*.48,-e.h*.05);ctx.closePath();ctx.fill();ctx.fillRect(-e.w*.4,-e.h*.04,e.w*.8,e.h*.48);ctx.fillStyle="#fff";ctx.fillRect(-e.w*.08,e.h*.16,e.w*.16,e.h*.28);ctx.fillRect(-e.w*.28,e.h*.05,e.w*.13,e.h*.13);ctx.fillRect(e.w*.15,e.h*.05,e.w*.13,e.h*.13);}
  else if(e.kind==="voteBadge"){ctx.fillStyle=e.color;ctx.beginPath();ctx.arc(0,0,s*.48,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font=`900 ${Math.max(22,s*.22)}px "${family}"`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(e.text||"رأی من",0,-s*.04);ctx.font=`600 ${Math.max(14,s*.1)}px "${family}"`;ctx.fillText("انتخاب من",0,s*.2);}
  else if(e.kind==="circle"){ctx.strokeStyle=e.color;ctx.lineWidth=Math.max(6,s*.045);ctx.beginPath();ctx.arc(0,0,s*.46,0,Math.PI*2);ctx.stroke();}
  else {ctx.strokeStyle=e.color;ctx.lineWidth=Math.max(6,s*.045);roundedRect(ctx,-e.w/2,-e.h/2,e.w,e.h,20);ctx.stroke();}
  ctx.restore();
}

function makeElement(kind:ElementKind,id:number,color:string):GraphicElement{return {id,kind,x:W/2,y:1180,w:180,h:130,rotation:0,opacity:1,color,text:kind==="voteBadge"?"رأی من":kind==="ribbon"?"انتخاب من":""};}

export default function StudentCouncilPosterPage(){
 const canvasRef=useRef<HTMLCanvasElement>(null);const dragRef=useRef<{id:number;dx:number;dy:number}|null>(null);
 const [name,setName]=useState("");const [school,setSchool]=useState("");const [className,setClassName]=useState("");const [number,setNumber]=useState("");const [slogan,setSlogan]=useState("");const [promises,setPromises]=useState("");const [achievements,setAchievements]=useState("");const [electionDate,setElectionDate]=useState("");
 const [theme,setTheme]=useState<Theme>("election");const [font,setFont]=useState<FontId>("Vazirmatn");const [image,setImage]=useState<HTMLImageElement|null>(null);const [imageUrl,setImageUrl]=useState("");const [accent,setAccent]=useState(themes.election.accent);
 const [showPromises,setShowPromises]=useState(true);const [showAchievements,setShowAchievements]=useState(false);const [showVoteBadge,setShowVoteBadge]=useState(true);const [showNumberBadge,setShowNumberBadge]=useState(true);
 const [elements,setElements]=useState<GraphicElement[]>([]);const [selectedId,setSelectedId]=useState<number|null>(null);const [nextId,setNextId]=useState(1);
 const selected=elements.find(e=>e.id===selectedId)||null;
 useEffect(()=>setAccent(themes[theme].accent),[theme]);
 useEffect(()=>{let cancelled=false;const draw=async()=>{await waitForFont(font);if(cancelled)return;const c=canvasRef.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;const p=themes[theme],primary=p.monochrome?"#111":accent||p.accent,ink=p.monochrome?"#111":p.text,muted=p.monochrome?"#444":p.muted;ctx.clearRect(0,0,W,H);ctx.fillStyle=p.bg;ctx.fillRect(0,0,W,H);ctx.direction="rtl";ctx.textAlign="center";
   if(p.layout==="badge"){ctx.fillStyle=primary;ctx.fillRect(0,0,W,310);ctx.fillStyle="rgba(255,255,255,.11)";ctx.beginPath();ctx.arc(1120,110,300,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(80,250,150,0,Math.PI*2);ctx.fill();}
   else if(p.layout==="diagonal"){ctx.fillStyle=primary;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(W,0);ctx.lineTo(W,420);ctx.lineTo(0,260);ctx.closePath();ctx.fill();}
   else if(p.layout==="friendly"){ctx.fillStyle=primary;ctx.fillRect(0,0,W,220);for(let i=0;i<7;i++){ctx.fillStyle=i%2?"rgba(255,255,255,.22)":"rgba(255,255,255,.12)";ctx.beginPath();ctx.arc(90+i*180,205,45+(i%3)*12,0,Math.PI*2);ctx.fill();}}
   else if(p.layout==="clean"){ctx.fillStyle=primary;ctx.fillRect(0,0,W,18);ctx.fillRect(0,H-18,W,18);ctx.strokeStyle=primary;ctx.lineWidth=5;roundedRect(ctx,45,45,W-90,H-90,28);ctx.stroke();}
   else if(p.layout==="bwClassic"){ctx.strokeStyle=primary;ctx.lineWidth=12;ctx.strokeRect(45,45,W-90,H-90);ctx.lineWidth=3;ctx.strokeRect(70,70,W-140,H-140);ctx.fillStyle=primary;ctx.fillRect(90,115,W-180,215);}
   else{ctx.strokeStyle=primary;ctx.lineWidth=6;ctx.setLineDash([18,14]);ctx.strokeRect(55,55,W-110,H-110);ctx.setLineDash([]);ctx.fillStyle=primary;ctx.fillRect(0,0,W,12);}
   const classic=p.layout==="bwClassic";const headerDark=p.layout==="clean"||p.layout==="bwMinimal"?ink:"#fff";const headerY=classic?225:135;const schoolY=classic?275:195;ctx.fillStyle=headerDark;ctx.font=`800 62px "${font}"`;ctx.fillText("انتخابات شورای دانش‌آموزی",W/2,headerY);ctx.font=`500 30px "${font}"`;ctx.fillText(school||"نام مدرسه",W/2,schoolY);
   const photoSize=410,photoX=W/2,photoY=p.layout==="badge"?500:520;if(image){ctx.save();ctx.beginPath();if(p.layout==="diagonal")ctx.arc(photoX,photoY,photoSize/2,0,Math.PI*2);else roundedRect(ctx,photoX-photoSize/2,photoY-photoSize/2,photoSize,photoSize,42);ctx.clip();const scale=Math.max(photoSize/image.width,photoSize/image.height),iw=image.width*scale,ih=image.height*scale;ctx.drawImage(image,photoX-iw/2,photoY-ih/2,iw,ih);ctx.restore();ctx.strokeStyle=primary;ctx.lineWidth=12;if(p.layout==="diagonal"){ctx.beginPath();ctx.arc(photoX,photoY,photoSize/2,0,Math.PI*2);ctx.stroke();}else{roundedRect(ctx,photoX-photoSize/2,photoY-photoSize/2,photoSize,photoSize,42);ctx.stroke();}}else{ctx.fillStyle=p.monochrome?"#eee":"#e5e7eb";ctx.beginPath();ctx.arc(photoX,photoY,photoSize/2,0,Math.PI*2);ctx.fill();ctx.fillStyle=muted;ctx.font=`700 34px "${font}"`;ctx.fillText("عکس کاندیدا",photoX,photoY+12);}
   const nameSize=fitText(ctx,name||"نام کاندیدا",W-180,78,font,900);ctx.fillStyle=ink;ctx.font=`900 ${nameSize}px "${font}"`;ctx.fillText(name||"نام کاندیدا",W/2,820);ctx.fillStyle=primary;ctx.font=`800 38px "${font}"`;ctx.fillText(slogan||"شعار انتخاباتی شما",W/2,890);ctx.fillStyle=muted;ctx.font=`600 27px "${font}"`;const meta=[className&&`پایه/کلاس: ${className}`,electionDate&&`تاریخ انتخابات: ${electionDate}`].filter(Boolean).join("   •   ");ctx.fillText(meta||"پایه / کلاس",W/2,945);
   if(showNumberBadge&&number){ctx.fillStyle=primary;ctx.beginPath();ctx.arc(170,860,92,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font=`900 58px "${font}"`;ctx.fillText(number,170,880);ctx.font=`600 22px "${font}"`;ctx.fillText("شماره",170,925);}
   let y=1015;const drawBox=(title:string,body:string)=>{if(!body.trim())return;ctx.fillStyle=p.monochrome?"#fff":"rgba(255,255,255,.72)";ctx.strokeStyle=primary;ctx.lineWidth=3;roundedRect(ctx,120,y,W-240,145,28);ctx.fill();ctx.stroke();ctx.fillStyle=primary;ctx.font=`800 28px "${font}"`;ctx.fillText(title,W/2,y+42);ctx.fillStyle=ink;ctx.font=`500 24px "${font}"`;wrapText(ctx,body.replace(/\n+/g," • "),W-300).slice(0,3).forEach((line,i)=>ctx.fillText(line,W/2,y+82+i*30));y+=165;};
   if(showPromises)drawBox("برنامه‌ها و وعده‌ها",promises);if(showAchievements)drawBox("سوابق و توانمندی‌ها",achievements);if(showVoteBadge){ctx.fillStyle=primary;roundedRect(ctx,290,H-150,W-580,75,38);ctx.fill();ctx.fillStyle="#fff";ctx.font=`800 27px "${font}"`;ctx.fillText("رأی شما، انتخاب فردای بهتر",W/2,H-101);}
   elements.forEach(e=>drawGraphic(ctx,e,font,p.monochrome));ctx.fillStyle=muted;ctx.font=`500 19px "${font}"`;ctx.fillText(`${SITE_NAME} | ${SITE_URL}`,W/2,H-55);
  };void draw();return()=>{cancelled=true;};},[name,school,className,number,slogan,promises,achievements,electionDate,theme,font,image,accent,showPromises,showAchievements,showVoteBadge,showNumberBadge,elements]);
 const onImage=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file||!file.type.startsWith("image/"))return;if(imageUrl)URL.revokeObjectURL(imageUrl);const url=URL.createObjectURL(file);setImageUrl(url);const img=new Image();img.onload=()=>setImage(img);img.src=url;};
 const addElement=(kind:ElementKind)=>{const id=nextId;setNextId(v=>v+1);setElements(v=>[...v,makeElement(kind,id,theme.startsWith("bw")?"#111":accent)]);setSelectedId(id);};
 const updateSelected=(patch:Partial<GraphicElement>)=>{if(selectedId===null)return;setElements(v=>v.map(e=>e.id===selectedId?{...e,...patch}:e));};
 const removeSelected=()=>{if(selectedId===null)return;setElements(v=>v.filter(e=>e.id!==selectedId));setSelectedId(null);};
 const moveLayer=(dir:-1|1)=>{if(selectedId===null)return;setElements(v=>{const i=v.findIndex(e=>e.id===selectedId);const j=i+dir;if(i<0||j<0||j>=v.length)return v;const a=[...v];[a[i],a[j]]=[a[j],a[i]];return a;});};
 const hitTest=(x:number,y:number)=>{for(let i=elements.length-1;i>=0;i--){const e=elements[i];const dx=x-e.x,dy=y-e.y;const a=-e.rotation*Math.PI/180;const rx=dx*Math.cos(a)-dy*Math.sin(a),ry=dx*Math.sin(a)+dy*Math.cos(a);if(Math.abs(rx)<=e.w/2&&Math.abs(ry)<=e.h/2)return e;}return null;};
 const pointerDown=(e:PointerEvent<HTMLCanvasElement>)=>{const c=canvasRef.current;if(!c)return;const r=c.getBoundingClientRect();const x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;const hit=hitTest(x,y);setSelectedId(hit?.id??null);if(hit){dragRef.current={id:hit.id,dx:x-hit.x,dy:y-hit.y};c.setPointerCapture(e.pointerId);}};
 const pointerMove=(e:PointerEvent<HTMLCanvasElement>)=>{const d=dragRef.current;if(!d)return;const c=canvasRef.current;if(!c)return;const r=c.getBoundingClientRect();const x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;setElements(v=>v.map(el=>el.id===d.id?{...el,x:Math.max(50,Math.min(W-50,x-d.dx)),y:Math.max(50,Math.min(H-50,y-d.dy))}:el));};
 const pointerUp=()=>{dragRef.current=null;};
 const download=(type:"png"|"jpeg")=>{const c=canvasRef.current;if(!c)return;const a=document.createElement("a");a.download=`poster-shora-${Date.now()}.${type==="png"?"png":"jpg"}`;a.href=c.toDataURL(type==="png"?"image/png":"image/jpeg",.96);a.click();};
 const print=()=>{const c=canvasRef.current;if(!c)return;const w=window.open("","_blank","width=900,height=1200");if(!w)return;w.document.write(`<html dir="rtl"><head><title>پوستر انتخابات شورای دانش‌آموزی</title><style>@page{size:A4 portrait;margin:0}body{margin:0;background:#fff}img{display:block;width:210mm;height:297mm;object-fit:contain}</style></head><body><img src="${c.toDataURL('image/png')}" onload="window.print();setTimeout(window.close,500)"></body></html>`);w.document.close();};
 return <main className="min-h-screen bg-[var(--background)] px-4 py-8" dir="rtl"><div className="mx-auto max-w-7xl"><header className="mb-8"><h1 className="text-3xl font-black text-[var(--text)]">پوستر انتخابات شورای دانش‌آموزی</h1><p className="mt-2 text-[var(--text-muted)]">پوستر انتخاباتی بساز، فونت فارسی انتخاب کن و المان‌های گرافیکی را آزادانه روی طرح قرار بده.</p></header>
 <div className="grid gap-6 lg:grid-cols-[400px_minmax(0,1fr)]"><aside className="order-2 h-fit space-y-4 lg:order-1">
  <section className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><h2 className="text-lg font-black">اطلاعات کاندیدا</h2><div className="mt-4 grid gap-3">{[["نام کاندیدا",name,setName],["نام مدرسه",school,setSchool],["پایه / کلاس",className,setClassName],["شماره کاندیدا",number,setNumber],["شعار انتخاباتی",slogan,setSlogan],["تاریخ انتخابات",electionDate,setElectionDate]].map(([label,value,setter])=><label key={label as string} className="block text-sm font-bold">{label as string}<input value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2.5 outline-none"/></label>)}</div><label className="mt-3 block text-sm font-bold">برنامه‌ها و وعده‌ها<textarea value={promises} onChange={e=>setPromises(e.target.value)} placeholder="هر برنامه در یک خط" className="mt-1 min-h-24 w-full rounded-xl border border-[var(--border)] p-3"/></label><label className="mt-3 block text-sm font-bold">سوابق و توانمندی‌ها<textarea value={achievements} onChange={e=>setAchievements(e.target.value)} placeholder="سوابق، افتخارات و مهارت‌ها" className="mt-1 min-h-20 w-full rounded-xl border border-[var(--border)] p-3"/></label><label className="mt-3 block text-sm font-bold">عکس کاندیدا<input type="file" accept="image/*" onChange={onImage} className="mt-1 block w-full text-sm"/></label></section>
  <section className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><h2 className="text-lg font-black">فونت و تم</h2><select value={font} onChange={e=>setFont(e.target.value as FontId)} className="mt-3 w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] p-3">{fonts.map(f=><option key={f.id} value={f.id}>{f.title}</option>)}</select><div className="mt-3 grid grid-cols-2 gap-2">{Object.entries(themes).map(([id,t])=><button key={id} onClick={()=>setTheme(id as Theme)} className={`rounded-xl border p-3 text-right ${theme===id?"ring-2 ring-[var(--primary)]":""}`}><b className="block">{t.title}</b><span className="text-xs text-[var(--text-muted)]">{t.desc}</span></button>)}</div></section>
  <section className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-lg font-black">المان‌های گرافیکی</h2><span className="text-xs text-[var(--text-muted)]">کلیک کنید و سپس جابه‌جا کنید</span></div><div className="mt-3 grid grid-cols-3 gap-2">{(Object.keys(elementLabels) as ElementKind[]).map(k=><button key={k} onClick={()=>addElement(k)} className="rounded-xl border border-[var(--border)] px-2 py-3 text-sm font-bold hover:bg-[var(--background)]">＋ {elementLabels[k]}</button>)}</div>{selected&&<div className="mt-4 border-t border-[var(--border)] pt-4"><div className="flex items-center justify-between"><b>ویرایش: {elementLabels[selected.kind]}</b><button onClick={removeSelected} className="text-sm font-bold text-red-600">حذف</button></div><label className="mt-3 block text-sm">اندازه<input type="range" min="60" max="500" value={selected.w} onChange={e=>updateSelected({w:+e.target.value,h:Math.round(+e.target.value*.72)})} className="w-full"/></label><label className="mt-2 block text-sm">چرخش<input type="range" min="-180" max="180" value={selected.rotation} onChange={e=>updateSelected({rotation:+e.target.value})} className="w-full"/></label><label className="mt-2 block text-sm">شفافیت<input type="range" min="0.1" max="1" step="0.05" value={selected.opacity} onChange={e=>updateSelected({opacity:+e.target.value})} className="w-full"/></label><label className="mt-2 block text-sm">رنگ<input type="color" value={selected.color} onChange={e=>updateSelected({color:e.target.value})} className="mt-1 h-10 w-full rounded-lg"/></label><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>moveLayer(1)} className="rounded-xl border p-2 text-sm font-bold">جلوتر</button><button onClick={()=>moveLayer(-1)} className="rounded-xl border p-2 text-sm font-bold">عقب‌تر</button></div></div>}</section>
  <section className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><h2 className="text-lg font-black">نمایش بخش‌ها</h2><div className="mt-3 grid gap-2 text-sm">{[[showPromises,setShowPromises,"برنامه‌ها و وعده‌ها"],[showAchievements,setShowAchievements,"سوابق و توانمندی‌ها"],[showVoteBadge,setShowVoteBadge,"نوار رأی"],[showNumberBadge,setShowNumberBadge,"شماره کاندیدا"]].map(([checked,setter,label])=><label key={label as string} className="flex items-center gap-2"><input type="checkbox" checked={checked as boolean} onChange={e=>(setter as (v:boolean)=>void)(e.target.checked)}/>{label as string}</label>)}</div></section>
 </aside><section className="order-1 lg:order-2 rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-4 shadow-sm"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-black">پیش‌نمایش پوستر</h2><p className="text-xs text-[var(--text-muted)]">المان انتخاب‌شده را با ماوس جابه‌جا کنید.</p></div><div className="flex gap-2"><button onClick={()=>download("png")} className="rounded-xl bg-[var(--primary)] px-4 py-2 text-sm font-bold text-white">PNG</button><button onClick={()=>download("jpeg")} className="rounded-xl border px-4 py-2 text-sm font-bold">JPG</button><button onClick={print} className="rounded-xl border px-4 py-2 text-sm font-bold">چاپ</button></div></div><div className="mx-auto max-w-[620px] overflow-hidden rounded-2xl bg-slate-100 p-2"><canvas ref={canvasRef} width={W} height={H} className="block h-auto w-full cursor-move rounded-xl" onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}/></div><p className="mt-3 text-center text-xs text-[var(--text-muted)]">در خروجی چاپی نیز «کافی‌نت توسن | https://tusancn.ir» درج می‌شود.</p></section></div></div></main>;
}
