"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";

type Theme = "election" | "bold" | "school" | "clean" | "bwClassic" | "bwMinimal";
type FontId = "Vazirmatn" | "Estedad" | "Lalezar" | "Noto Naskh Arabic" | "Noto Sans Arabic";
type ThemeConfig = { title:string; desc:string; bg:string; accent:string; text:string; muted:string; monochrome?:boolean; layout:"badge"|"diagonal"|"friendly"|"clean"|"bwClassic"|"bwMinimal" };

const SITE_URL = "https://tusancn.ir";
const SITE_NAME = "کافی‌نت توسن";
const fonts: { id: FontId; title: string }[] = [
  { id:"Vazirmatn", title:"وزیرمتن" }, { id:"Estedad", title:"استعداد" }, { id:"Lalezar", title:"لاله‌زار" },
  { id:"Noto Naskh Arabic", title:"نوتو نسخ عربی" }, { id:"Noto Sans Arabic", title:"نوتو سنس عربی" },
];
const themes: Record<Theme,ThemeConfig> = {
  election:{title:"انتخاباتی",desc:"مخصوص شورای دانش‌آموزی",bg:"#fff7ed",accent:"#dc2626",text:"#171717",muted:"#525252",layout:"badge"},
  bold:{title:"جسور",desc:"تیتر بزرگ و پرانرژی",bg:"#eff6ff",accent:"#2563eb",text:"#172033",muted:"#475569",layout:"diagonal"},
  school:{title:"شاد مدرسه‌ای",desc:"مناسب دانش‌آموزان",bg:"#f0fdf4",accent:"#059669",text:"#17332a",muted:"#527267",layout:"friendly"},
  clean:{title:"تمیز",desc:"ساده و حرفه‌ای",bg:"#fff",accent:"#111827",text:"#111827",muted:"#6b7280",layout:"clean"},
  bwClassic:{title:"سیاه و سفید کلاسیک",desc:"کم‌جوهر و مناسب پرینتر",bg:"#fff",accent:"#111",text:"#111",muted:"#444",monochrome:true,layout:"bwClassic"},
  bwMinimal:{title:"سیاه و سفید مینیمال",desc:"چاپ اقتصادی و خوانا",bg:"#fff",accent:"#000",text:"#111",muted:"#555",monochrome:true,layout:"bwMinimal"},
};
const fontUrls: Record<FontId,string> = {
  Vazirmatn:"https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;500;600;700;800;900&display=swap",
  Estedad:"https://fonts.googleapis.com/css2?family=Estedad:wght@400;500;600;700;800;900&display=swap",
  Lalezar:"https://fonts.googleapis.com/css2?family=Lalezar&display=swap",
  "Noto Naskh Arabic":"https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;500;600;700&display=swap",
  "Noto Sans Arabic":"https://fonts.googleapis.com/css2?family=Noto+Sans+Arabic:wght@400;500;600;700;800;900&display=swap",
};

async function loadFont(font: FontId) {
  const id=`poster-font-${font.replace(/\s+/g,"-")}`;
  if(!document.getElementById(id)){ const link=document.createElement("link"); link.id=id; link.rel="stylesheet"; link.href=fontUrls[font]; document.head.appendChild(link); }
  await document.fonts.load(`800 48px "${font}"`);
  await document.fonts.load(`500 28px "${font}"`);
  await document.fonts.ready;
}
function roundedRect(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){const q=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q);ctx.closePath();}
function fitText(ctx:CanvasRenderingContext2D,text:string,maxWidth:number,start:number,family:string,weight=800){let size=start;while(size>20){ctx.font=`${weight} ${size}px "${family}"`;if(ctx.measureText(text).width<=maxWidth)return size;size-=2;}return size;}
function wrapText(ctx:CanvasRenderingContext2D,text:string,maxWidth:number){const words=text.split(/\s+/).filter(Boolean);const lines:string[]=[];let line="";for(const word of words){const candidate=line?`${line} ${word}`:word;if(ctx.measureText(candidate).width<=maxWidth||!line)line=candidate;else{lines.push(line);line=word;}}if(line)lines.push(line);return lines;}

export default function StudentCouncilPosterPage(){
 const canvasRef=useRef<HTMLCanvasElement>(null);
 const [name,setName]=useState(""); const [school,setSchool]=useState(""); const [className,setClassName]=useState(""); const [number,setNumber]=useState(""); const [slogan,setSlogan]=useState(""); const [promises,setPromises]=useState(""); const [achievements,setAchievements]=useState(""); const [electionDate,setElectionDate]=useState("");
 const [theme,setTheme]=useState<Theme>("election"); const [font,setFont]=useState<FontId>("Vazirmatn"); const [image,setImage]=useState<HTMLImageElement|null>(null); const [imageUrl,setImageUrl]=useState(""); const [accent,setAccent]=useState(themes.election.accent);
 const [showPromises,setShowPromises]=useState(true); const [showAchievements,setShowAchievements]=useState(false); const [showVoteBadge,setShowVoteBadge]=useState(true); const [showNumberBadge,setShowNumberBadge]=useState(true);
 useEffect(()=>{setAccent(themes[theme].accent);},[theme]);
 useEffect(()=>{let cancelled=false;const draw=async()=>{await loadFont(font);if(cancelled)return;const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d");if(!ctx)return;const p=themes[theme],W=canvas.width,H=canvas.height,family=font,primary=p.monochrome?"#111":accent||p.accent,ink=p.monochrome?"#111":p.text,muted=p.monochrome?"#444":p.muted;ctx.clearRect(0,0,W,H);ctx.fillStyle=p.bg;ctx.fillRect(0,0,W,H);ctx.direction="rtl";ctx.textAlign="center";
   if(p.layout==="badge"){ctx.fillStyle=primary;ctx.fillRect(0,0,W,310);ctx.fillStyle="rgba(255,255,255,.11)";ctx.beginPath();ctx.arc(1120,110,300,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(80,250,150,0,Math.PI*2);ctx.fill();}
   else if(p.layout==="diagonal"){ctx.fillStyle=primary;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(W,0);ctx.lineTo(W,420);ctx.lineTo(0,260);ctx.closePath();ctx.fill();}
   else if(p.layout==="friendly"){ctx.fillStyle=primary;ctx.fillRect(0,0,W,220);for(let i=0;i<7;i++){ctx.fillStyle=i%2?"rgba(255,255,255,.22)":"rgba(255,255,255,.12)";ctx.beginPath();ctx.arc(90+i*180,205,45+(i%3)*12,0,Math.PI*2);ctx.fill();}}
   else if(p.layout==="clean"){ctx.fillStyle=primary;ctx.fillRect(0,0,W,18);ctx.fillRect(0,H-18,W,18);ctx.strokeStyle=primary;ctx.lineWidth=5;roundedRect(ctx,45,45,W-90,H-90,28);ctx.stroke();}
   else if(p.layout==="bwClassic"){ctx.strokeStyle=primary;ctx.lineWidth=12;ctx.strokeRect(45,45,W-90,H-90);ctx.lineWidth=3;ctx.strokeRect(70,70,W-140,H-140);ctx.fillStyle=primary;ctx.fillRect(90,115,W-180,215);}
   else{ctx.strokeStyle=primary;ctx.lineWidth=6;ctx.setLineDash([18,14]);ctx.strokeRect(55,55,W-110,H-110);ctx.setLineDash([]);ctx.fillStyle=primary;ctx.fillRect(0,0,W,12);}
   const isBwClassic=p.layout==="bwClassic"; const headerDark=p.layout==="clean"||p.layout==="bwMinimal"?ink:"#fff";
   const headerY=isBwClassic?225:135; const schoolY=isBwClassic?275:195;
   ctx.fillStyle=headerDark;ctx.font=`800 62px "${family}"`;ctx.fillText("انتخابات شورای دانش‌آموزی",W/2,headerY);ctx.font=`500 30px "${family}"`;ctx.fillText(school||"نام مدرسه",W/2,schoolY);
   const photoSize=410,photoX=W/2,photoY=p.layout==="badge"?500:520;
   if(image){ctx.save();ctx.beginPath();if(p.layout==="diagonal")ctx.arc(photoX,photoY,photoSize/2,0,Math.PI*2);else roundedRect(ctx,photoX-photoSize/2,photoY-photoSize/2,photoSize,photoSize,42);ctx.clip();const scale=Math.max(photoSize/image.width,photoSize/image.height),iw=image.width*scale,ih=image.height*scale;ctx.drawImage(image,photoX-iw/2,photoY-ih/2,iw,ih);ctx.restore();ctx.strokeStyle=primary;ctx.lineWidth=12;if(p.layout==="diagonal"){ctx.beginPath();ctx.arc(photoX,photoY,photoSize/2,0,Math.PI*2);ctx.stroke();}else{roundedRect(ctx,photoX-photoSize/2,photoY-photoSize/2,photoSize,photoSize,42);ctx.stroke();}}
   else{ctx.fillStyle=p.monochrome?"#eee":"#e5e7eb";ctx.beginPath();ctx.arc(photoX,photoY,photoSize/2,0,Math.PI*2);ctx.fill();ctx.fillStyle=muted;ctx.font=`700 34px "${family}"`;ctx.fillText("عکس کاندیدا",photoX,photoY+12);}
   const nameSize=fitText(ctx,name||"نام کاندیدا",W-180,78,family,900);ctx.fillStyle=ink;ctx.font=`900 ${nameSize}px "${family}"`;ctx.fillText(name||"نام کاندیدا",W/2,820);ctx.fillStyle=primary;ctx.font=`800 38px "${family}"`;ctx.fillText(slogan||"شعار انتخاباتی شما",W/2,890);ctx.fillStyle=muted;ctx.font=`600 27px "${family}"`;const meta=[className&&`پایه/کلاس: ${className}`,electionDate&&`تاریخ انتخابات: ${electionDate}`].filter(Boolean).join("   •   ");ctx.fillText(meta||"پایه / کلاس",W/2,945);
   if(showNumberBadge&&number){ctx.fillStyle=primary;ctx.beginPath();ctx.arc(170,860,92,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font=`900 58px "${family}"`;ctx.fillText(number,170,880);ctx.font=`600 22px "${family}"`;ctx.fillText("شماره",170,925);}
   let y=1015;const drawBox=(title:string,body:string)=>{if(!body.trim())return;ctx.fillStyle=p.monochrome?"#fff":"rgba(255,255,255,.72)";ctx.strokeStyle=primary;ctx.lineWidth=3;roundedRect(ctx,120,y,W-240,145,28);ctx.fill();ctx.stroke();ctx.fillStyle=primary;ctx.font=`800 28px "${family}"`;ctx.fillText(title,W/2,y+42);ctx.fillStyle=ink;ctx.font=`500 24px "${family}"`;wrapText(ctx,body.replace(/\n+/g," • "),W-300).slice(0,3).forEach((line,i)=>ctx.fillText(line,W/2,y+82+i*30));y+=165;};
   if(showPromises)drawBox("برنامه‌ها و وعده‌ها",promises);if(showAchievements)drawBox("سوابق و توانمندی‌ها",achievements);
   if(showVoteBadge){ctx.fillStyle=primary;roundedRect(ctx,290,H-150,W-580,75,38);ctx.fill();ctx.fillStyle="#fff";ctx.font=`800 27px "${family}"`;ctx.fillText("رأی شما، انتخاب فردای بهتر",W/2,H-101);}
   ctx.fillStyle=muted;ctx.font=`500 19px "${family}"`;ctx.fillText(`${SITE_NAME} | ${SITE_URL}`,W/2,H-55);
  };void draw();return()=>{cancelled=true;};},[name,school,className,number,slogan,promises,achievements,electionDate,theme,font,image,accent,showPromises,showAchievements,showVoteBadge,showNumberBadge]);
 const onImage=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file||!file.type.startsWith("image/"))return;if(imageUrl)URL.revokeObjectURL(imageUrl);const url=URL.createObjectURL(file);setImageUrl(url);const img=new Image();img.onload=()=>setImage(img);img.src=url;};
 const download=(type:"png"|"jpeg")=>{const canvas=canvasRef.current;if(!canvas)return;const a=document.createElement("a");a.download=`poster-shora-${Date.now()}.${type==="png"?"png":"jpg"}`;a.href=canvas.toDataURL(type==="png"?"image/png":"image/jpeg",0.96);a.click();};
 return <main className="min-h-screen bg-[var(--background)] px-4 py-8" dir="rtl"><div className="mx-auto max-w-7xl"><header className="mb-8"><h1 className="text-3xl font-black text-[var(--text)]">پوستر انتخابات شورای دانش‌آموزی</h1><p className="mt-2 text-[var(--text-muted)]">پوستر واقعی انتخاباتی بساز، فونت فارسی انتخاب کن، برنامه‌ها و مشخصات کاندیدا را اضافه کن و برای چاپ خروجی بگیر.</p></header><div className="grid gap-6 lg:grid-cols-[380px_minmax(0,1fr)]"><aside className="order-2 h-fit rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm lg:order-1"><h2 className="text-lg font-black">اطلاعات کاندیدا</h2><div className="mt-4 space-y-3">{[["نام کاندیدا",name,setName],["نام مدرسه",school,setSchool],["پایه / کلاس",className,setClassName],["شماره کاندیدا",number,setNumber],["شعار انتخاباتی",slogan,setSlogan],["تاریخ انتخابات",electionDate,setElectionDate]].map(([label,value,setter])=><label key={label as string} className="block text-sm font-bold text-[var(--text)]">{label as string}<input value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2.5 outline-none focus:border-[var(--primary)]"/></label>)}</div><label className="mt-3 block text-sm font-bold">برنامه‌ها و وعده‌ها<textarea value={promises} onChange={e=>setPromises(e.target.value)} placeholder="مثلاً: برگزاری مسابقات ورزشی\nبهبود کتابخانه\nایجاد صندوق پیشنهادات" className="mt-1 min-h-24 w-full rounded-xl border border-[var(--border)] px-3 py-2.5 text-sm outline-none"/></label><label className="mt-3 block text-sm font-bold">سوابق و توانمندی‌ها<textarea value={achievements} onChange={e=>setAchievements(e.target.value)} placeholder="مثلاً: عضو شورای کلاس، مسئول انجمن..." className="mt-1 min-h-20 w-full rounded-xl border border-[var(--border)] px-3 py-2.5 text-sm outline-none"/></label><label className="mt-3 block text-sm font-bold">عکس کاندیدا<input type="file" accept="image/*" onChange={onImage} className="mt-1 block w-full text-sm"/></label>{imageUrl&&<button type="button" onClick={()=>{setImage(null);URL.revokeObjectURL(imageUrl);setImageUrl("");}} className="text-sm font-bold text-red-600">حذف عکس</button>}
 <h2 className="mt-7 text-lg font-black">فونت فارسی</h2><select value={font} onChange={e=>setFont(e.target.value as FontId)} className="mt-3 w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-3 text-sm font-bold">{fonts.map(f=><option key={f.id} value={f.id}>{f.title}</option>)}</select><p className="mt-2 text-xs leading-5 text-[var(--text-muted)]">فونت انتخابی پس از بارگذاری واقعی فونت روی Canvas اعمال می‌شود.</p>
 <h2 className="mt-7 text-lg font-black">اجزای انتخاباتی</h2><div className="mt-3 space-y-2 text-sm font-bold"><label className="flex items-center justify-between rounded-xl border border-[var(--border)] p-3"><span>نمایش برنامه‌ها</span><input type="checkbox" checked={showPromises} onChange={e=>setShowPromises(e.target.checked)}/></label><label className="flex items-center justify-between rounded-xl border border-[var(--border)] p-3"><span>نمایش سوابق</span><input type="checkbox" checked={showAchievements} onChange={e=>setShowAchievements(e.target.checked)}/></label><label className="flex items-center justify-between rounded-xl border border-[var(--border)] p-3"><span>نشان شماره رأی</span><input type="checkbox" checked={showNumberBadge} onChange={e=>setShowNumberBadge(e.target.checked)}/></label><label className="flex items-center justify-between rounded-xl border border-[var(--border)] p-3"><span>نوار «رأی شما...»</span><input type="checkbox" checked={showVoteBadge} onChange={e=>setShowVoteBadge(e.target.checked)}/></label></div>
 <h2 className="mt-7 text-lg font-black">قالب پوستر</h2><div className="mt-3 grid grid-cols-2 gap-2">{Object.entries(themes).map(([id,t])=><button key={id} type="button" onClick={()=>setTheme(id as Theme)} className={`rounded-xl border p-3 text-right transition ${theme===id?"border-[var(--primary)] bg-[var(--primary)]/10":"border-[var(--border)]"}`}><b className="block text-sm">{t.title}</b><span className="text-xs text-[var(--text-muted)]">{t.desc}</span></button>)}</div>{!themes[theme].monochrome&&<label className="mt-4 block text-sm font-bold">رنگ اصلی<input type="color" value={accent} onChange={e=>setAccent(e.target.value)} className="mt-2 h-10 w-full cursor-pointer rounded-lg"/></label>}
 <div className="mt-6 grid grid-cols-2 gap-2"><button type="button" onClick={()=>download("png")} className="rounded-xl bg-[var(--primary)] px-3 py-3 text-sm font-black text-white">دانلود PNG</button><button type="button" onClick={()=>download("jpeg")} className="rounded-xl border border-[var(--border)] px-3 py-3 text-sm font-black">دانلود JPG</button></div><button type="button" onClick={()=>window.print()} className="mt-2 w-full rounded-xl border border-[var(--border)] px-3 py-3 text-sm font-black">چاپ پوستر</button></aside><section className="order-1 flex items-center justify-center rounded-3xl border border-[var(--border)] bg-[var(--surface-secondary)] p-3 sm:p-6 lg:order-2"><canvas ref={canvasRef} width={1240} height={1754} className="h-auto w-full max-w-[700px] rounded-xl shadow-2xl" aria-label="پیش‌نمایش پوستر"/></section></div></div><style jsx global>{`@media print{@page{size:A4 portrait;margin:0}body{margin:0!important}body *{visibility:hidden!important}canvas{visibility:visible!important;position:fixed;inset:0;width:210mm!important;height:297mm!important;max-width:none!important;border-radius:0!important;box-shadow:none!important}}`}</style></main>;
}
