"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { GripVertical, LayoutTemplate, Palette, Plus, Printer, Trash2, UserRound } from "lucide-react";

type Experience={id:string;title:string;company:string;start:string;end:string;description:string};
type Education={id:string;degree:string;field:string;school:string;year:string;description:string};
type Skill={id:string;name:string;level:number};
type Project={id:string;title:string;link:string;description:string};
type SectionId="summary"|"experience"|"projects"|"education"|"research"|"skills"|"languages"|"certifications"|"interests";
type Resume={name:string;role:string;phone:string;email:string;city:string;website:string;summary:string;photo:string;experiences:Experience[];education:Education[];skills:Skill[];projects:Project[];research:string;languages:string;certifications:string;interests:string;template:"modern"|"classic"|"minimal";accent:string;sectionVisibility:Record<SectionId,boolean>;sectionOrder:SectionId[]};

const uid=()=>Math.random().toString(36).slice(2,10);
const defaultOrder:SectionId[]=["summary","experience","projects","education","research","skills","languages","certifications","interests"];
const sectionLabels:Record<SectionId,string>={summary:"درباره من",experience:"سوابق کاری",projects:"پروژه‌ها",education:"تحصیلات",research:"تحقیقات و مقالات",skills:"مهارت‌ها",languages:"زبان‌ها",certifications:"دوره‌ها و گواهینامه‌ها",interests:"علایق"};
const initial:Resume={name:"",role:"",phone:"",email:"",city:"",website:"",summary:"",photo:"",experiences:[{id:uid(),title:"",company:"",start:"",end:"",description:""}],education:[{id:uid(),degree:"",field:"",school:"",year:"",description:""}],skills:[{id:uid(),name:"",level:80}],projects:[{id:uid(),title:"",link:"",description:""}],research:"",languages:"",certifications:"",interests:"",template:"modern",accent:"#09967c",sectionVisibility:Object.fromEntries(defaultOrder.map(x=>[x,true])) as Record<SectionId,boolean>,sectionOrder:defaultOrder};

function Field({label,value,onChange,placeholder,type="text"}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;type?:string}){return <label className="block"><span className="mb-1.5 block text-sm font-bold">{label}</span><input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2.5 text-sm outline-none focus:border-[var(--primary)]"/></label>}
function EditorSection({title,onAdd,children}:{title:string;onAdd:()=>void;children:React.ReactNode}){return <div className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><h2 className="font-black">{title}</h2><button onClick={onAdd} className="inline-flex items-center gap-1 rounded-xl bg-[var(--primary)]/10 px-3 py-2 text-xs font-black text-[var(--primary)]"><Plus size={15}/>افزودن</button></div>{children}</div>}
function Textarea({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="block"><span className="mb-1.5 block text-sm font-bold">{label}</span><textarea rows={4} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] p-3 text-sm leading-7 outline-none focus:border-[var(--primary)]"/></label>}

export default function ResumeBuilderPage(){
 const [data,setData]=useState<Resume>(initial); const [saved,setSaved]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem("tusan-resume-builder");if(raw){const r=JSON.parse(raw);setData({...initial,...r,sectionVisibility:{...initial.sectionVisibility,...r.sectionVisibility},sectionOrder:Array.isArray(r.sectionOrder)?r.sectionOrder:defaultOrder})}}catch{}},[]);
 useEffect(()=>{const t=window.setTimeout(()=>{try{localStorage.setItem("tusan-resume-builder",JSON.stringify(data));setSaved(true);window.setTimeout(()=>setSaved(false),1000)}catch{}},400);return()=>window.clearTimeout(t)},[data]);
 const set=<K extends keyof Resume>(key:K,value:Resume[K])=>setData(d=>({...d,[key]:value}));
 const updateItem=<K extends "experiences"|"education"|"skills"|"projects">(key:K,id:string,patch:Partial<Resume[K][number]>)=>setData(d=>({...d,[key]:d[key].map(item=>item.id===id?{...item,...patch}:item)}));
 const removeItem=<K extends "experiences"|"education"|"skills"|"projects">(key:K,id:string)=>setData(d=>({...d,[key]:d[key].filter(item=>item.id!==id)}));
 const photo=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>set("photo",String(reader.result||""));reader.readAsDataURL(file)};
 const hasContent=useMemo(()=>Boolean(data.name||data.role||data.summary||data.experiences.some(x=>x.title||x.company)||data.education.some(x=>x.degree||x.school)||data.projects.some(x=>x.title)||data.skills.some(x=>x.name)),[data]);
 const toggle=(id:SectionId)=>set("sectionVisibility",{...data.sectionVisibility,[id]:!data.sectionVisibility[id]});
 const move=(id:SectionId,dir:-1|1)=>{const a=[...data.sectionOrder],i=a.indexOf(id),j=i+dir;if(i<0||j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];set("sectionOrder",a)};
 const resetSections=()=>setData(d=>({...d,sectionOrder:defaultOrder,sectionVisibility:{...initial.sectionVisibility}}));
 const show=(id:SectionId)=>data.sectionVisibility[id];
 const preview=(id:SectionId,content:React.ReactNode)=>{if(!show(id))return null;return <section key={id} className="mb-6"><h3 className="mb-3 border-b border-slate-200 pb-2 text-sm font-black" style={{color:data.accent}}>{sectionLabels[id]}</h3>{content}</section>};
 const previewSection=(id:SectionId)=>{switch(id){case"summary":return preview(id,<p className="whitespace-pre-line text-sm leading-7">{data.summary}</p>);case"experience":return preview(id,<>{data.experiences.filter(x=>x.title||x.company).map(x=><div key={x.id} className="mb-5 border-r-2 border-slate-200 pr-4"><div className="flex justify-between gap-3"><h4 className="font-black">{x.title}</h4><span className="text-xs text-slate-500">{x.start}{x.start&&x.end?" — ":""}{x.end}</span></div><p className="mt-1 text-sm font-bold" style={{color:data.accent}}>{x.company}</p><p className="mt-2 whitespace-pre-line text-xs leading-6 text-slate-600">{x.description}</p></div>)}</>);case"projects":return preview(id,<>{data.projects.filter(x=>x.title).map(x=><div key={x.id} className="mb-4"><div className="flex justify-between gap-2"><h4 className="font-black">{x.title}</h4>{x.link&&<span className="text-[10px] text-slate-500">{x.link}</span>}</div><p className="mt-1 whitespace-pre-line text-xs leading-6 text-slate-600">{x.description}</p></div>)}</>);case"education":return preview(id,<>{data.education.filter(x=>x.degree||x.school).map(x=><div key={x.id} className="mb-4"><h4 className="font-black">{[x.degree,x.field].filter(Boolean).join(" — ")}</h4><p className="mt-1 text-sm" style={{color:data.accent}}>{x.school}{x.year&&` · ${x.year}`}</p><p className="mt-1 whitespace-pre-line text-xs leading-6 text-slate-600">{x.description}</p></div>)}</>);case"research":return preview(id,<p className="whitespace-pre-line text-xs leading-6">{data.research}</p>);case"skills":return preview(id,<>{data.skills.filter(x=>x.name).map(x=><div key={x.id} className="mb-3"><div className="mb-1 flex justify-between text-xs font-bold"><span>{x.name}</span><span>{x.level}%</span></div><div className="h-1.5 rounded-full bg-slate-200"><div className="h-full rounded-full" style={{width:`${x.level}%`,backgroundColor:data.accent}}/></div></div>)}</>);case"languages":return preview(id,<p className="whitespace-pre-line text-xs leading-6">{data.languages}</p>);case"certifications":return preview(id,<p className="whitespace-pre-line text-xs leading-6">{data.certifications}</p>);case"interests":return preview(id,<p className="whitespace-pre-line text-xs leading-6">{data.interests}</p>);}}
 return <main dir="rtl" className="min-h-screen page-background py-8 md:py-12 print:bg-white print:p-0"><div className="mx-auto max-w-7xl px-4 lg:px-6 print:max-w-none print:px-0"><header className="mb-7 flex flex-wrap items-center justify-between gap-4 print:hidden"><div><h1 className="text-3xl font-black">رزومه‌ساز توسن</h1><p className="mt-2 text-sm text-[var(--text-muted)]">ساخت رزومه حرفه‌ای با پیش‌نمایش زنده، قالب‌های مختلف و ذخیره خودکار.</p></div><div className="flex gap-2"><button onClick={()=>window.print()} disabled={!hasContent} className="inline-flex items-center gap-2 rounded-xl bg-[var(--primary)] px-4 py-2.5 text-sm font-black text-white disabled:opacity-50"><Printer size={17}/>چاپ / ذخیره PDF</button><button onClick={()=>{setData(initial);localStorage.removeItem("tusan-resume-builder")}} className="rounded-xl border border-[var(--border)] px-4 py-2.5 text-sm font-bold">شروع مجدد</button></div></header>
 <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_560px] print:block"><section className="space-y-5 print:hidden">
 <div className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><div className="mb-5 flex items-center gap-3"><UserRound className="text-[var(--primary)]"/><div><h2 className="font-black">اطلاعات شخصی</h2><p className="text-xs text-[var(--text-muted)]">اطلاعات اصلی رزومه</p></div></div><div className="grid gap-4 sm:grid-cols-2"><Field label="نام و نام خانوادگی" value={data.name} onChange={v=>set("name",v)}/><Field label="عنوان شغلی" value={data.role} onChange={v=>set("role",v)}/><Field label="شماره تماس" value={data.phone} onChange={v=>set("phone",v)}/><Field label="ایمیل" value={data.email} onChange={v=>set("email",v)} type="email"/><Field label="شهر" value={data.city} onChange={v=>set("city",v)}/><Field label="وب‌سایت / لینکدین" value={data.website} onChange={v=>set("website",v)}/></div><label className="mt-4 block"><span className="mb-1.5 block text-sm font-bold">عکس پروفایل</span><input type="file" accept="image/*" onChange={photo} className="block w-full rounded-xl border border-[var(--border)] p-2 text-sm"/></label><Textarea label="خلاصه حرفه‌ای" value={data.summary} onChange={v=>set("summary",v)}/></div>
 <div className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><LayoutTemplate size={19} className="text-[var(--primary)]"/><h2 className="font-black">قالب و رنگ</h2></div><div className="grid grid-cols-3 gap-2">{([['modern','مدرن'],['classic','کلاسیک'],['minimal','مینیمال']] as const).map(([id,label])=><button key={id} onClick={()=>set("template",id)} className={`rounded-xl border px-3 py-3 text-sm font-bold ${data.template===id?'border-[var(--primary)] bg-[var(--primary)]/10 text-[var(--primary)]':'border-[var(--border)]'}`}>{label}</button>)}</div><div className="mt-5 flex items-center gap-3"><Palette size={18} className="text-[var(--primary)]"/><span className="text-sm font-bold">رنگ اصلی</span><div className="flex gap-2">{['#09967c','#2563eb','#7c3aed','#b45309','#334155'].map(c=><button key={c} aria-label={c} onClick={()=>set("accent",c)} className={`h-8 w-8 rounded-full border-2 ${data.accent===c?'border-slate-900 scale-110':'border-transparent'}`} style={{backgroundColor:c}}/>)}</div></div></div>
 <div className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black">مدیریت بخش‌های رزومه</h2><p className="mt-1 text-xs text-[var(--text-muted)]">نمایش/مخفی‌سازی و ترتیب بخش‌ها</p></div><button onClick={resetSections} className="rounded-xl border border-[var(--border)] px-3 py-2 text-xs font-bold">بازنشانی</button></div><div className="space-y-2">{data.sectionOrder.map((id,i)=><div key={id} className="flex items-center gap-2 rounded-xl border border-[var(--border)] p-2"><GripVertical size={16} className="text-slate-400"/><button onClick={()=>toggle(id)} className={`flex-1 text-right text-sm font-bold ${show(id)?'':'text-slate-400 line-through'}`}>{sectionLabels[id]}</button><button disabled={i===0} onClick={()=>move(id,-1)} className="rounded-lg border px-2 py-1 text-xs disabled:opacity-30">↑</button><button disabled={i===data.sectionOrder.length-1} onClick={()=>move(id,1)} className="rounded-lg border px-2 py-1 text-xs disabled:opacity-30">↓</button><span className={`h-2 w-2 rounded-full ${show(id)?'bg-emerald-500':'bg-slate-300'}`}/></div>)}</div></div>
 <EditorSection title="سوابق کاری" onAdd={()=>set("experiences",[...data.experiences,{id:uid(),title:"",company:"",start:"",end:"",description:""}])}>{data.experiences.map((x,i)=><div key={x.id} className="mb-3 rounded-2xl border border-[var(--border)] p-4"><div className="mb-3 flex justify-between"><span className="text-xs font-black">سابقه {i+1}</span>{data.experiences.length>1&&<button onClick={()=>removeItem("experiences",x.id)} className="text-red-500"><Trash2 size={16}/></button>}</div><div className="grid gap-4 sm:grid-cols-2"><Field label="عنوان شغلی" value={x.title} onChange={v=>updateItem("experiences",x.id,{title:v})}/><Field label="شرکت / سازمان" value={x.company} onChange={v=>updateItem("experiences",x.id,{company:v})}/><Field label="شروع" value={x.start} onChange={v=>updateItem("experiences",x.id,{start:v})}/><Field label="پایان" value={x.end} onChange={v=>updateItem("experiences",x.id,{end:v})}/></div><textarea value={x.description} onChange={e=>updateItem("experiences",x.id,{description:e.target.value})} rows={3} className="mt-3 w-full rounded-xl border p-3 text-sm" placeholder="شرح مسئولیت‌ها و دستاوردها..."/></div>)}</EditorSection>
 <EditorSection title="تحصیلات" onAdd={()=>set("education",[...data.education,{id:uid(),degree:"",field:"",school:"",year:"",description:""}])}>{data.education.map((x,i)=><div key={x.id} className="mb-3 rounded-2xl border p-4"><div className="mb-3 flex justify-between"><span className="text-xs font-black">تحصیلات {i+1}</span>{data.education.length>1&&<button onClick={()=>removeItem("education",x.id)} className="text-red-500"><Trash2 size={16}/></button>}</div><div className="grid gap-4 sm:grid-cols-2"><Field label="مقطع" value={x.degree} onChange={v=>updateItem("education",x.id,{degree:v})}/><Field label="رشته" value={x.field} onChange={v=>updateItem("education",x.id,{field:v})}/><Field label="دانشگاه / مدرسه" value={x.school} onChange={v=>updateItem("education",x.id,{school:v})}/><Field label="سال" value={x.year} onChange={v=>updateItem("education",x.id,{year:v})}/></div></div>)}</EditorSection>
 <EditorSection title="پروژه‌ها" onAdd={()=>set("projects",[...data.projects,{id:uid(),title:"",link:"",description:""}])}>{data.projects.map((x,i)=><div key={x.id} className="mb-3 rounded-2xl border p-4"><div className="mb-3 flex justify-between"><span className="text-xs font-black">پروژه {i+1}</span>{data.projects.length>1&&<button onClick={()=>removeItem("projects",x.id)} className="text-red-500"><Trash2 size={16}/></button>}</div><div className="grid gap-4 sm:grid-cols-2"><Field label="نام پروژه" value={x.title} onChange={v=>updateItem("projects",x.id,{title:v})}/><Field label="لینک پروژه" value={x.link} onChange={v=>updateItem("projects",x.id,{link:v})}/></div><textarea value={x.description} onChange={e=>updateItem("projects",x.id,{description:e.target.value})} rows={3} className="mt-3 w-full rounded-xl border p-3 text-sm"/></div>)}</EditorSection>
 <EditorSection title="مهارت‌ها" onAdd={()=>set("skills",[...data.skills,{id:uid(),name:"",level:80}])}>{data.skills.map((x,i)=><div key={x.id} className="mb-3 grid grid-cols-[1fr_110px_auto] items-end gap-3"><Field label={i===0?'نام مهارت':''} value={x.name} onChange={v=>updateItem("skills",x.id,{name:v})}/><label><span className="mb-1 block text-sm font-bold">سطح {x.level}%</span><input type="range" min="10" max="100" value={x.level} onChange={e=>updateItem("skills",x.id,{level:Number(e.target.value)})}/></label><button onClick={()=>removeItem("skills",x.id)} className="mb-2 text-red-500"><Trash2 size={16}/></button></div>)}</EditorSection>
 <div className="grid gap-5 md:grid-cols-2"><Textarea label="تحقیقات / مقالات" value={data.research} onChange={v=>set("research",v)}/><Textarea label="زبان‌ها" value={data.languages} onChange={v=>set("languages",v)}/><Textarea label="دوره‌ها و گواهینامه‌ها" value={data.certifications} onChange={v=>set("certifications",v)}/><Textarea label="علایق" value={data.interests} onChange={v=>set("interests",v)}/></div>{saved&&<div className="text-center text-xs font-bold text-[var(--primary)]">ذخیره شد ✓</div>}
 </section>
 <section className="lg:sticky lg:top-5 lg:self-start print:static"><div className={`mx-auto min-h-[842px] w-full max-w-[595px] bg-white text-slate-800 shadow-xl print:min-h-0 print:max-w-none print:w-[210mm] print:shadow-none ${data.template==='classic'?'font-serif':''}`}><div className={`${data.template==='classic'?'border-b px-8 pb-6 pt-8 text-center':data.template==='minimal'?'px-8 pb-4 pt-8':'border-b-8 px-8 pb-6 pt-8'}`} style={{borderColor:data.accent}}><Header data={data}/></div><div className="grid grid-cols-[1fr_150px] gap-7 px-8 py-7"><div className="min-w-0">{data.sectionOrder.filter(id=>['summary','experience','projects','education','research'].includes(id)).map(previewSection)}</div><aside>{data.sectionOrder.filter(id=>['skills','languages','certifications','interests'].includes(id)).map(previewSection)}</aside></div></div><div className="mt-3 text-center text-xs text-[var(--text-muted)] print:hidden">بخش‌های خاموش‌شده در پیش‌نمایش و چاپ نمایش داده نمی‌شوند.</div></section></div></div></main>
}
function Header({data}:{data:Resume}){return <div className={`flex items-start gap-5 ${data.template==='classic'?'justify-center':''}`}>{data.photo?<img src={data.photo} className="h-24 w-24 rounded-2xl object-cover"/>:<div className="flex h-24 w-24 shrink-0 items-center justify-center rounded-2xl bg-slate-100 text-slate-400"><UserRound size={34}/></div>}<div className="min-w-0 flex-1"><h2 className="text-3xl font-black">{data.name||"نام و نام خانوادگی"}</h2><p className="mt-1 text-lg font-bold" style={{color:data.accent}}>{data.role||"عنوان شغلی"}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500">{data.phone&&<span>{data.phone}</span>}{data.email&&<span>{data.email}</span>}{data.city&&<span>{data.city}</span>}{data.website&&<span>{data.website}</span>}</div></div></div>}
