"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { Download, GripVertical, Plus, Printer, Trash2, UserRound } from "lucide-react";

type Experience = { id: string; title: string; company: string; start: string; end: string; description: string };
type Education = { id: string; degree: string; field: string; school: string; year: string; description: string };
type Skill = { id: string; name: string; level: number };
type Resume = {
  name: string; role: string; phone: string; email: string; city: string; website: string; summary: string;
  photo: string; experiences: Experience[]; education: Education[]; skills: Skill[]; languages: string; certifications: string; interests: string;
};

const uid = () => Math.random().toString(36).slice(2, 10);
const initial: Resume = {
  name: "", role: "", phone: "", email: "", city: "", website: "", summary: "", photo: "",
  experiences: [{ id: uid(), title: "", company: "", start: "", end: "", description: "" }],
  education: [{ id: uid(), degree: "", field: "", school: "", year: "", description: "" }],
  skills: [{ id: uid(), name: "", level: 80 }], languages: "", certifications: "", interests: "",
};

const Field = ({ label, value, onChange, placeholder, type = "text" }: { label: string; value: string; onChange: (v: string) => void; placeholder?: string; type?: string }) => (
  <label className="block"><span className="mb-1.5 block text-sm font-bold">{label}</span><input type={type} value={value} placeholder={placeholder} onChange={e => onChange(e.target.value)} className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2.5 text-sm outline-none transition focus:border-[var(--primary)]" /></label>
);

export default function ResumeBuilderPage() {
  const [data, setData] = useState<Resume>(initial);
  const [saved, setSaved] = useState(false);
  useEffect(() => { try { const raw = localStorage.getItem("tusan-resume-builder"); if (raw) setData({ ...initial, ...JSON.parse(raw) }); } catch {} }, []);
  useEffect(() => { const t = window.setTimeout(() => { try { localStorage.setItem("tusan-resume-builder", JSON.stringify(data)); setSaved(true); window.setTimeout(() => setSaved(false), 1200); } catch {} }, 400); return () => window.clearTimeout(t); }, [data]);
  const set = <K extends keyof Resume>(key: K, value: Resume[K]) => setData(d => ({ ...d, [key]: value }));
  const updateItem = <K extends "experiences" | "education" | "skills",>(key: K, id: string, patch: Partial<Resume[K][number]>) => setData(d => ({ ...d, [key]: d[key].map(item => item.id === id ? { ...item, ...patch } : item) }));
  const removeItem = <K extends "experiences" | "education" | "skills">(key: K, id: string) => setData(d => ({ ...d, [key]: d[key].filter(item => item.id !== id) }));
  const photo = (e: ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => set("photo", String(reader.result || "")); reader.readAsDataURL(file); };
  const hasContent = useMemo(() => Boolean(data.name || data.role || data.summary || data.experiences.some(x => x.title || x.company) || data.education.some(x => x.degree || x.school)), [data]);

  return <main dir="rtl" className="min-h-screen page-background py-8 md:py-12 print:bg-white print:p-0">
    <div className="mx-auto max-w-7xl px-4 lg:px-6 print:max-w-none print:px-0">
      <header className="mb-7 flex flex-wrap items-center justify-between gap-4 print:hidden">
        <div><h1 className="text-3xl font-black">رزومه‌ساز توسن</h1><p className="mt-2 text-sm text-[var(--text-muted)]">ساخت رزومه حرفه‌ای، سریع و قابل چاپ؛ اطلاعات شما در مرورگر ذخیره می‌شود.</p></div>
        <div className="flex gap-2"><button onClick={() => window.print()} disabled={!hasContent} className="inline-flex items-center gap-2 rounded-xl bg-[var(--primary)] px-4 py-2.5 text-sm font-black text-white disabled:opacity-50"><Printer size={17}/> چاپ / ذخیره PDF</button><button onClick={() => { setData(initial); localStorage.removeItem("tusan-resume-builder"); }} className="rounded-xl border border-[var(--border)] px-4 py-2.5 text-sm font-bold">شروع مجدد</button></div>
      </header>

      <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_560px] print:block">
        <section className="space-y-5 print:hidden">
          <div className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><div className="mb-5 flex items-center gap-3"><UserRound className="text-[var(--primary)]"/><div><h2 className="font-black">اطلاعات شخصی</h2><p className="text-xs text-[var(--text-muted)]">اطلاعات اصلی رزومه</p></div></div><div className="grid gap-4 sm:grid-cols-2"><Field label="نام و نام خانوادگی" value={data.name} onChange={v=>set("name",v)} placeholder="مثلاً مهدی احمدی"/><Field label="عنوان شغلی" value={data.role} onChange={v=>set("role",v)} placeholder="طراح رابط کاربری"/><Field label="شماره تماس" value={data.phone} onChange={v=>set("phone",v)}/><Field label="ایمیل" value={data.email} onChange={v=>set("email",v)} type="email"/><Field label="شهر" value={data.city} onChange={v=>set("city",v)}/><Field label="وب‌سایت / لینکدین" value={data.website} onChange={v=>set("website",v)}/></div><label className="mt-4 block"><span className="mb-1.5 block text-sm font-bold">عکس پروفایل</span><input type="file" accept="image/*" onChange={photo} className="block w-full rounded-xl border border-[var(--border)] p-2 text-sm"/></label><label className="mt-4 block"><span className="mb-1.5 block text-sm font-bold">خلاصه حرفه‌ای</span><textarea value={data.summary} onChange={e=>set("summary",e.target.value)} rows={5} placeholder="در چند جمله تجربه، تخصص و ارزش پیشنهادی خود را معرفی کنید..." className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] p-3 text-sm leading-7 outline-none focus:border-[var(--primary)]"/></label></div>

          <EditorSection title="سوابق کاری" onAdd={() => set("experiences", [...data.experiences, { id: uid(), title: "", company: "", start: "", end: "", description: "" }])}>
            {data.experiences.map((x,i)=><div key={x.id} className="rounded-2xl border border-[var(--border)] p-4"><div className="mb-4 flex items-center justify-between"><span className="text-xs font-black text-[var(--text-muted)]">سابقه {i+1}</span>{data.experiences.length>1&&<button onClick={()=>removeItem("experiences",x.id)} className="text-red-500"><Trash2 size={16}/></button>}</div><div className="grid gap-4 sm:grid-cols-2"><Field label="عنوان شغلی" value={x.title} onChange={v=>updateItem("experiences",x.id,{title:v})}/><Field label="شرکت / سازمان" value={x.company} onChange={v=>updateItem("experiences",x.id,{company:v})}/><Field label="شروع" value={x.start} onChange={v=>updateItem("experiences",x.id,{start:v})}/><Field label="پایان" value={x.end} onChange={v=>updateItem("experiences",x.id,{end:v})}/></div><textarea value={x.description} onChange={e=>updateItem("experiences",x.id,{description:e.target.value})} rows={4} placeholder="شرح مسئولیت‌ها و دستاوردها..." className="mt-4 w-full rounded-xl border border-[var(--border)] p-3 text-sm leading-7 outline-none focus:border-[var(--primary)]"/></div>)}
          </EditorSection>

          <EditorSection title="تحصیلات" onAdd={() => set("education", [...data.education, { id: uid(), degree: "", field: "", school: "", year: "", description: "" }])}>{data.education.map((x,i)=><div key={x.id} className="rounded-2xl border border-[var(--border)] p-4"><div className="mb-4 flex justify-between"><span className="text-xs font-black text-[var(--text-muted)]">تحصیلات {i+1}</span>{data.education.length>1&&<button onClick={()=>removeItem("education",x.id)} className="text-red-500"><Trash2 size={16}/></button>}</div><div className="grid gap-4 sm:grid-cols-2"><Field label="مقطع" value={x.degree} onChange={v=>updateItem("education",x.id,{degree:v})}/><Field label="رشته" value={x.field} onChange={v=>updateItem("education",x.id,{field:v})}/><Field label="دانشگاه / مدرسه" value={x.school} onChange={v=>updateItem("education",x.id,{school:v})}/><Field label="سال" value={x.year} onChange={v=>updateItem("education",x.id,{year:v})}/></div><textarea value={x.description} onChange={e=>updateItem("education",x.id,{description:e.target.value})} rows={3} placeholder="توضیحات تکمیلی" className="mt-4 w-full rounded-xl border border-[var(--border)] p-3 text-sm leading-7 outline-none focus:border-[var(--primary)]"/></div>)}</EditorSection>

          <EditorSection title="مهارت‌ها" onAdd={() => set("skills", [...data.skills, { id: uid(), name: "", level: 80 }])}>{data.skills.map((x,i)=><div key={x.id} className="mb-3 grid grid-cols-[1fr_110px_auto] items-end gap-3"><Field label={i===0?"نام مهارت":""} value={x.name} onChange={v=>updateItem("skills",x.id,{name:v})}/><label className="block"><span className="mb-1.5 block text-sm font-bold">سطح</span><input type="range" min="10" max="100" value={x.level} onChange={e=>updateItem("skills",x.id,{level:Number(e.target.value)})} className="w-full"/></label><button onClick={()=>removeItem("skills",x.id)} className="mb-2 text-red-500"><Trash2 size={16}/></button></div>)}</EditorSection>

          <div className="grid gap-5 md:grid-cols-3"><SmallTextarea label="زبان‌ها" value={data.languages} onChange={v=>set("languages",v)} placeholder="انگلیسی — متوسط\nعربی — مقدماتی"/><SmallTextarea label="دوره‌ها و گواهینامه‌ها" value={data.certifications} onChange={v=>set("certifications",v)} placeholder="نام دوره — سال"/><SmallTextarea label="علایق" value={data.interests} onChange={v=>set("interests",v)} placeholder="مطالعه، ورزش، فناوری"/></div>
          {saved&&<div className="text-center text-xs font-bold text-[var(--primary)]">ذخیره شد ✓</div>}
        </section>

        <section className="lg:sticky lg:top-5 lg:self-start print:static"><div id="resume-preview" className="mx-auto min-h-[842px] w-full max-w-[595px] bg-white text-slate-800 shadow-xl print:mx-0 print:min-h-0 print:max-w-none print:w-[210mm] print:shadow-none">
          <div className="border-b-8 border-[var(--primary)] px-8 pb-6 pt-8"><div className="flex items-start gap-5">{data.photo?<img src={data.photo} className="h-24 w-24 rounded-2xl object-cover"/>:<div className="flex h-24 w-24 shrink-0 items-center justify-center rounded-2xl bg-slate-100 text-slate-400"><UserRound size={34}/></div>}<div className="min-w-0 flex-1"><h2 className="text-3xl font-black">{data.name||"نام و نام خانوادگی"}</h2><p className="mt-1 text-lg font-bold text-[var(--primary)]">{data.role||"عنوان شغلی"}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500">{data.phone&&<span>{data.phone}</span>}{data.email&&<span>{data.email}</span>}{data.city&&<span>{data.city}</span>}{data.website&&<span>{data.website}</span>}</div></div></div></div>
          <div className="grid grid-cols-[1fr_150px] gap-7 px-8 py-7"><div className="min-w-0"><PreviewSection title="درباره من" show={!!data.summary}><p className="whitespace-pre-line text-sm leading-7">{data.summary}</p></PreviewSection><PreviewSection title="سوابق کاری" show={data.experiences.some(x=>x.title||x.company)}>{data.experiences.filter(x=>x.title||x.company).map(x=><div key={x.id} className="mb-5 border-r-2 border-slate-200 pr-4"><div className="flex justify-between gap-3"><h4 className="font-black">{x.title||"عنوان شغلی"}</h4><span className="text-xs text-slate-500">{x.start}{x.start&&x.end?" — ":""}{x.end}</span></div><p className="mt-1 text-sm font-bold text-[var(--primary)]">{x.company}</p><p className="mt-2 whitespace-pre-line text-xs leading-6 text-slate-600">{x.description}</p></div>)}</PreviewSection><PreviewSection title="تحصیلات" show={data.education.some(x=>x.degree||x.school)}>{data.education.filter(x=>x.degree||x.school).map(x=><div key={x.id} className="mb-4"><h4 className="font-black">{[x.degree,x.field].filter(Boolean).join(" — ")||"تحصیلات"}</h4><p className="mt-1 text-sm text-[var(--primary)]">{x.school} {x.year&&`· ${x.year}`}</p><p className="mt-1 whitespace-pre-line text-xs leading-6 text-slate-600">{x.description}</p></div>)}</PreviewSection></div><aside><PreviewSection title="مهارت‌ها" show={data.skills.some(x=>x.name)}>{data.skills.filter(x=>x.name).map(x=><div key={x.id} className="mb-3"><div className="mb-1 flex justify-between text-xs font-bold"><span>{x.name}</span><span>{x.level}%</span></div><div className="h-1.5 rounded-full bg-slate-200"><div className="h-full rounded-full bg-[var(--primary)]" style={{width:`${x.level}%`}}/></div></div>)}</PreviewSection><PreviewSection title="زبان‌ها" show={!!data.languages}><p className="whitespace-pre-line text-xs leading-6">{data.languages}</p></PreviewSection><PreviewSection title="دوره‌ها" show={!!data.certifications}><p className="whitespace-pre-line text-xs leading-6">{data.certifications}</p></PreviewSection><PreviewSection title="علایق" show={!!data.interests}><p className="whitespace-pre-line text-xs leading-6">{data.interests}</p></PreviewSection></aside></div>
        </div><div className="mt-3 flex items-center justify-center gap-2 text-xs text-[var(--text-muted)] print:hidden"><Download size={14}/> از گزینه «چاپ / ذخیره PDF» مرورگر برای دریافت فایل استفاده کنید.</div></section>
      </div>
    </div>
  </main>;
}

function EditorSection({ title, onAdd, children }: { title: string; onAdd: () => void; children: React.ReactNode }) { return <div className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><h2 className="font-black">{title}</h2><button onClick={onAdd} className="inline-flex items-center gap-1 rounded-xl bg-[var(--primary)]/10 px-3 py-2 text-xs font-black text-[var(--primary)]"><Plus size={15}/> افزودن</button></div>{children}</div>; }
function SmallTextarea({ label, value, onChange, placeholder }: { label:string; value:string; onChange:(v:string)=>void; placeholder?:string }) { return <label className="block"><span className="mb-1.5 block text-sm font-bold">{label}</span><textarea rows={4} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] p-3 text-sm leading-6 outline-none focus:border-[var(--primary)]"/></label>; }
function PreviewSection({ title, show, children }: { title:string; show:boolean; children:React.ReactNode }) { if (!show) return null; return <section className="mb-6"><h3 className="mb-3 border-b border-slate-200 pb-2 text-sm font-black text-[var(--primary)]">{title}</h3>{children}</section>; }
