"use client";

import { ChangeEvent, PointerEvent as ReactPointerEvent, ReactNode, useEffect, useRef, useState } from "react";
import { CheckCircle2, Download, Film, Loader2, Maximize2, RotateCcw, Scissors, Subtitles, Upload, Volume2, VolumeX } from "lucide-react";
import { convertVideoFormat, makeBrowserPlayable } from "@/lib/video/ffmpeg";

type Meta = { duration: number; width: number; height: number; size: number; type: string };
type Crop = { x: number; y: number; width: number; height: number };
type SubtitleCue = { start: number; end: number; text: string };
const MB = 1024 * 1024;

function formatTime(seconds: number) { if (!Number.isFinite(seconds)) return "00:00"; const s = Math.max(0, Math.floor(seconds)); return `${Math.floor(s / 60).toString().padStart(2, "0")}:${(s % 60).toString().padStart(2, "0")}`; }
function parseTime(value: string) { const p = value.replace(",", ".").split(":").map(Number); if (p.length === 3) return (p[0] || 0) * 3600 + (p[1] || 0) * 60 + (p[2] || 0); if (p.length === 2) return (p[0] || 0) * 60 + (p[1] || 0); return Number(p[0]) || 0; }
function download(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = name; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1500); }
function downloadFromUrl(url: string, name: string) { const a = document.createElement("a"); a.href = url; a.download = name; document.body.appendChild(a); a.click(); a.remove(); }
function isVideoFile(file: File) { return file.type.startsWith("video/") || /\.(mp4|webm|mov|m4v|avi|mkv|mpeg|mpg|ogv|3gp|ts|mts|m2ts)$/i.test(file.name); }
function parseSubtitles(text: string): SubtitleCue[] { const normalized = text.replace(/\r/g, "").trim(); if (!normalized) return []; return normalized.split(/\n\s*\n/).flatMap((block) => { const lines = block.split("\n").map((x) => x.trim()).filter(Boolean); const i = lines.findIndex((x) => x.includes(" --> ")); if (i < 0) return []; const [a, b] = lines[i].split(" --> "); const start = parseTime(a); const end = parseTime((b || "").split(" ")[0]); const cueText = lines.slice(i + 1).join("\n"); return end > start && cueText ? [{ start, end, text: cueText }] : []; }); }
function clamp(v: number, min: number, max: number) { return Math.min(max, Math.max(min, v)); }
function pickWebMMime() { return ["video/webm;codecs=vp9,opus", "video/webm;codecs=vp8,opus", "video/webm"].find((x) => typeof MediaRecorder !== "undefined" && MediaRecorder.isTypeSupported(x)) || ""; }
type FrameVideo = HTMLVideoElement & { requestVideoFrameCallback?: (cb: (now: number, metadata: { mediaTime: number }) => void) => number; cancelVideoFrameCallback?: (id: number) => void; captureStream?: () => MediaStream };

export default function VideoManager() {
  const inputRef = useRef<HTMLInputElement>(null); const subtitleRef = useRef<HTMLInputElement>(null); const videoRef = useRef<HTMLVideoElement>(null); const canvasRef = useRef<HTMLCanvasElement>(null); const cropStageRef = useRef<HTMLDivElement>(null);
  const sourceUrlRef = useRef(""); const outputUrlRef = useRef(""); const [file, setFile] = useState<File | null>(null); const [sourceUrl, setSourceUrl] = useState(""); const [meta, setMeta] = useState<Meta | null>(null); const [output, setOutput] = useState<{ url: string; name: string; size: number } | null>(null); const [thumbnail, setThumbnail] = useState("");
  const [busy, setBusy] = useState(false); const [progress, setProgress] = useState(0); const [message, setMessage] = useState(""); const [operation, setOperation] = useState("آماده"); const [fallbackTried, setFallbackTried] = useState(false);
  const [start, setStart] = useState(0); const [end, setEnd] = useState(0); const [width, setWidth] = useState(0); const [height, setHeight] = useState(0); const [keepRatio, setKeepRatio] = useState(true); const [quality, setQuality] = useState(70); const [fps, setFps] = useState(30); const [format, setFormat] = useState<"webm" | "mp4">("webm"); const [muted, setMuted] = useState(false);
  const [cropEnabled, setCropEnabled] = useState(false); const [crop, setCrop] = useState<Crop>({ x: 0, y: 0, width: 1, height: 1 }); const cropDrag = useRef<{ mode: "move" | "resize"; px: number; py: number; crop: Crop } | null>(null);
  const [subtitleText, setSubtitleText] = useState(""); const [subtitles, setSubtitles] = useState<SubtitleCue[]>([]); const [subtitleStatus, setSubtitleStatus] = useState(""); const [thumbnailTime, setThumbnailTime] = useState(0);
  const duration = meta?.duration || 0;

  useEffect(() => () => { if (sourceUrlRef.current) URL.revokeObjectURL(sourceUrlRef.current); if (outputUrlRef.current) URL.revokeObjectURL(outputUrlRef.current); }, []);

  const reset = () => { if (sourceUrlRef.current) URL.revokeObjectURL(sourceUrlRef.current); if (outputUrlRef.current) URL.revokeObjectURL(outputUrlRef.current); sourceUrlRef.current = outputUrlRef.current = ""; setFile(null); setSourceUrl(""); setMeta(null); setOutput(null); setThumbnail(""); setStart(0); setEnd(0); setWidth(0); setHeight(0); setCrop({ x: 0, y: 0, width: 1, height: 1 }); setCropEnabled(false); setSubtitles([]); setSubtitleText(""); setSubtitleStatus(""); setProgress(0); setMessage(""); setOperation("آماده"); setFallbackTried(false); if (inputRef.current) inputRef.current.value = ""; };

  const applyMetadata = (v: HTMLVideoElement, selected: File) => { if (!Number.isFinite(v.duration) || v.duration <= 0 || v.videoWidth <= 0 || v.videoHeight <= 0) return false; const m = { duration: v.duration, width: v.videoWidth, height: v.videoHeight, size: selected.size, type: selected.type || "video/" }; setMeta(m); setStart(0); setEnd(m.duration); setWidth(m.width); setHeight(m.height); setThumbnailTime(Math.min(m.duration / 2, Math.max(0, m.duration - 0.05))); setCrop({ x: 0, y: 0, width: 1, height: 1 }); setOperation("آماده"); setMessage("ویدیو آماده است و می‌توانید تنظیمات را انجام دهید."); return true; };

  const select = (e: ChangeEvent<HTMLInputElement>) => { const next = e.target.files?.[0]; if (!next) return; if (!isVideoFile(next)) { setMessage("فقط فایل ویدیویی انتخاب کنید."); return; } if (sourceUrlRef.current) URL.revokeObjectURL(sourceUrlRef.current); const url = URL.createObjectURL(next); sourceUrlRef.current = url; setFile(next); setSourceUrl(url); setMeta(null); setOutput(null); setFallbackTried(false); setProgress(0); setOperation("در حال آماده‌سازی"); setMessage("در حال آماده‌سازی ویدیو و خواندن مشخصات فایل..."); };

  const onVideoReady = () => { const v = videoRef.current; if (v && file) applyMetadata(v, file); };
  const fallback = async () => { if (!file || fallbackTried || busy) return; setFallbackTried(true); setBusy(true); setProgress(0); setOperation("در حال سازگار کردن کدک"); setMessage("کدک این فایل توسط مرورگر پشتیبانی نمی‌شود؛ در حال تبدیل موقت با FFmpeg..."); try { const playable = await makeBrowserPlayable(file, (p) => setProgress(Math.round(p * 100))); if (sourceUrlRef.current) URL.revokeObjectURL(sourceUrlRef.current); const url = URL.createObjectURL(playable); sourceUrlRef.current = url; setFile(playable); setSourceUrl(url); setMeta(null); setProgress(0); setOperation("در حال آماده‌سازی"); setMessage("تبدیل کدک انجام شد؛ مشخصات ویدیو در حال خواندن است..."); } catch (err) { setOperation("خطا"); setMessage(err instanceof Error ? `تبدیل کدک انجام نشد: ${err.message}` : "تبدیل کدک انجام نشد."); } finally { setBusy(false); } };

  useEffect(() => { if (!sourceUrl || !file) return; const timer = window.setTimeout(() => { const v = videoRef.current; if (v && !meta && !fallbackTried) { setOperation("در حال بررسی کدک"); fallback(); } }, 12000); return () => clearTimeout(timer); }, [sourceUrl, file, meta, fallbackTried]);

  const updateWidth = (value: number) => { const w = Math.max(2, Math.round(value || 2)); setWidth(w); if (keepRatio && meta) setHeight(Math.max(2, Math.round(w * meta.height / meta.width))); };
  const updateHeight = (value: number) => { const h = Math.max(2, Math.round(value || 2)); setHeight(h); if (keepRatio && meta) setWidth(Math.max(2, Math.round(h * meta.width / meta.height))); };

  const beginCrop = (e: ReactPointerEvent<HTMLDivElement>, mode: "move" | "resize") => { if (!cropEnabled || !cropStageRef.current) return; e.preventDefault(); e.currentTarget.setPointerCapture?.(e.pointerId); cropDrag.current = { mode, px: e.clientX, py: e.clientY, crop: { ...crop } }; };
  const moveCrop = (e: ReactPointerEvent<HTMLDivElement>) => { const d = cropDrag.current; const stage = cropStageRef.current; if (!d || !stage) return; const r = stage.getBoundingClientRect(); const dx = (e.clientX - d.px) / r.width; const dy = (e.clientY - d.py) / r.height; if (d.mode === "move") setCrop({ ...d.crop, x: clamp(d.crop.x + dx, 0, 1 - d.crop.width), y: clamp(d.crop.y + dy, 0, 1 - d.crop.height) }); else setCrop({ ...d.crop, width: clamp(d.crop.width + dx, 0.05, 1 - d.crop.x), height: clamp(d.crop.height + dy, 0.05, 1 - d.crop.y) }); };
  const endCrop = () => { cropDrag.current = null; };

  const seek = async (time: number) => { const v = videoRef.current; if (!v) return; if (Math.abs(v.currentTime - time) < 0.02) return; await new Promise<void>((resolve, reject) => { const timer = window.setTimeout(() => { v.removeEventListener("seeked", done); reject(new Error("جابجایی به زمان انتخاب‌شده انجام نشد.")); }, 8000); const done = () => { clearTimeout(timer); v.removeEventListener("seeked", done); resolve(); }; v.addEventListener("seeked", done); v.currentTime = time; }); };

  const capture = async () => { const v = videoRef.current, c = canvasRef.current; if (!v || !c || !meta) return; setBusy(true); setOperation("استخراج تصویر شاخص"); try { await seek(Math.min(thumbnailTime, Math.max(0, duration - .05))); c.width = meta.width; c.height = meta.height; const ctx = c.getContext("2d"); if (!ctx) throw new Error("Canvas در این مرورگر در دسترس نیست."); ctx.drawImage(v, 0, 0, meta.width, meta.height); const blob = await new Promise<Blob>((resolve, reject) => c.toBlob((b) => b ? resolve(b) : reject(new Error("استخراج فریم ناموفق بود.")), "image/jpeg", .92)); setThumbnail(URL.createObjectURL(blob)); download(blob, "tusan-video-thumbnail.jpg"); setMessage("تصویر شاخص با موفقیت استخراج شد."); } catch (err) { setMessage(err instanceof Error ? err.message : "استخراج فریم انجام نشد."); } finally { setBusy(false); setOperation("آماده"); } };

  const loadSubtitleFile = (e: ChangeEvent<HTMLInputElement>) => { const f = e.target.files?.[0]; if (!f) return; const reader = new FileReader(); reader.onload = () => { const text = String(reader.result || ""); setSubtitleText(text); const parsed = parseSubtitles(text); setSubtitles(parsed); setSubtitleStatus(parsed.length ? `${parsed.length} زیرنویس شناسایی شد.` : "فرمت زیرنویس قابل شناسایی نیست."); }; reader.readAsText(f); };

  const processVideo = async () => {
    const v = videoRef.current, c = canvasRef.current; if (!v || !c || !meta || !file) return;
    const mime = pickWebMMime(); if (!mime) { setMessage("مرورگر شما خروجی WebM را پشتیبانی نمی‌کند."); return; }
    const from = clamp(start, 0, Math.max(0, duration - .05)); const to = clamp(end || duration, from + .05, duration); const outW = Math.max(2, Math.round(width / 2) * 2); const outH = Math.max(2, Math.round(height / 2) * 2);
    setBusy(true); setProgress(0); setOperation("در حال ساخت خروجی"); setMessage("پردازش داخل مرورگر انجام می‌شود؛ فایل به سرور ارسال نمی‌شود."); setOutput(null);
    let raf = 0; let frame = 0; try {
      c.width = outW; c.height = outH; const ctx = c.getContext("2d"); if (!ctx || typeof c.captureStream !== "function") throw new Error("پردازش ویدیویی Canvas در این مرورگر پشتیبانی نمی‌شود.");
      const stream = c.captureStream(fps); if (!muted && v.captureStream) v.captureStream().getAudioTracks().forEach((t) => stream.addTrack(t));
      const recorder = new MediaRecorder(stream, { mimeType: mime, videoBitsPerSecond: Math.max(250000, Math.round(4000000 * (quality / 100) ** 1.7)) }); const chunks: BlobPart[] = []; recorder.ondataavailable = (e) => e.data.size && chunks.push(e.data);
      const stopped = new Promise<void>((resolve) => { recorder.onstop = () => resolve(); });
      const draw = () => { const sx = crop.x * meta.width, sy = crop.y * meta.height, sw = crop.width * meta.width, sh = crop.height * meta.height; ctx.clearRect(0, 0, outW, outH); ctx.drawImage(v, sx, sy, sw, sh, 0, 0, outW, outH); const cue = subtitles.find((x) => v.currentTime >= x.start && v.currentTime <= x.end); if (cue) { ctx.font = `${Math.max(18, Math.round(outW / 38))}px Vazirmatn, sans-serif`; ctx.textAlign = "center"; ctx.textBaseline = "bottom"; cue.text.split("\n").forEach((line, i, lines) => { const y = outH - 35 - (lines.length - 1 - i) * Math.max(28, outH / 22); const m = ctx.measureText(line); ctx.fillStyle = "rgba(0,0,0,.72)"; ctx.fillRect((outW - m.width) / 2 - 14, y - 30, m.width + 28, 36); ctx.fillStyle = "#fff"; ctx.fillText(line, outW / 2, y); }); } };
      const finish = () => { if (v.currentTime >= to - .04) { v.pause(); if (recorder.state === "recording") recorder.stop(); return true; } return false; };
      const render = () => { if (recorder.state !== "recording") return; draw(); setProgress(Math.min(96, Math.round(((v.currentTime - from) / (to - from)) * 96))); if (!finish()) raf = requestAnimationFrame(render); };
      const onFrame = (_now: number, m: { mediaTime: number }) => { if (recorder.state !== "recording") return; draw(); setProgress(Math.min(96, Math.round(((m.mediaTime - from) / (to - from)) * 96))); if (!finish()) frame = vv.requestVideoFrameCallback!(onFrame); };
      const vv = v as FrameVideo; recorder.start(200); await seek(from); await v.play(); if (vv.requestVideoFrameCallback) frame = vv.requestVideoFrameCallback(onFrame); else raf = requestAnimationFrame(render); await new Promise<void>((resolve) => { const timer = window.setInterval(() => { if (recorder.state === "inactive") { clearInterval(timer); resolve(); } }, 100); }); await stopped;
      if (frame && vv.cancelVideoFrameCallback) vv.cancelVideoFrameCallback(frame); if (raf) cancelAnimationFrame(raf); stream.getTracks().forEach((t) => t.stop()); const raw = new Blob(chunks, { type: mime }); if (!raw.size) throw new Error("خروجی خالی تولید شد.");
      let finalFile = new File([raw], `tusan-video-${Date.now()}.webm`, { type: "video/webm" });
      if (format === "mp4") { setOperation("در حال تبدیل به MP4"); setMessage("خروجی WebM ساخته شد؛ در حال تبدیل نهایی به MP4 با FFmpeg..."); finalFile = await convertVideoFormat(finalFile, "mp4", (p) => setProgress(96 + Math.round(p * 4))); }
      if (outputUrlRef.current) URL.revokeObjectURL(outputUrlRef.current); outputUrlRef.current = URL.createObjectURL(finalFile); setOutput({ url: outputUrlRef.current, name: finalFile.name, size: finalFile.size }); setProgress(100); setOperation("تمام شد"); setMessage(`خروجی ${format.toUpperCase()} آماده است؛ حجم ${(finalFile.size / MB).toFixed(2)} MB.`);
    } catch (err) { setOperation("خطا"); setMessage(err instanceof Error ? err.message : "پردازش ویدیو ناموفق بود."); } finally { setBusy(false); }
  };

  return <div className="rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm sm:p-7" dir="rtl">
    <input ref={inputRef} type="file" accept="video/*,.mp4,.webm,.mov,.m4v,.avi,.mkv,.mpeg,.mpg,.ogv,.3gp,.ts,.mts,.m2ts" onChange={select} className="hidden" />
    <input ref={subtitleRef} type="file" accept=".srt,.vtt,text/vtt,application/x-subrip" onChange={loadSubtitleFile} className="hidden" />
    <div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]">
      <div className="space-y-4">
        <div ref={cropStageRef} className="relative overflow-hidden rounded-2xl border border-[var(--border)] bg-black" style={{ aspectRatio: meta ? `${meta.width}/${meta.height}` : "16/9" }} onPointerMove={moveCrop} onPointerUp={endCrop} onPointerCancel={endCrop}>
          {sourceUrl ? <video ref={videoRef} key={sourceUrl} src={sourceUrl} controls playsInline preload="metadata" onLoadedMetadata={onVideoReady} onLoadedData={onVideoReady} onCanPlay={onVideoReady} onError={fallback} className="h-full w-full object-contain" /> : <button type="button" onClick={() => inputRef.current?.click()} className="flex h-full w-full flex-col items-center justify-center text-white"><Upload className="h-12 w-12 text-[var(--primary)]" /><span className="mt-3 font-black">انتخاب ویدیو</span><span className="mt-1 text-xs text-white/60">پردازش مستقیم روی دستگاه شما</span></button>}
          {meta && cropEnabled && <div className="pointer-events-none absolute inset-0"><div className="absolute border-2 border-white shadow-[0_0_0_9999px_rgba(0,0,0,.48)]" style={{ left: `${crop.x * 100}%`, top: `${crop.y * 100}%`, width: `${crop.width * 100}%`, height: `${crop.height * 100}%` }}><div className="pointer-events-auto absolute inset-0 cursor-move" onPointerDown={(e) => beginCrop(e, "move")} /><div className="pointer-events-auto absolute bottom-[-7px] left-[-7px] h-4 w-4 cursor-nwse-resize rounded-full border-2 border-white bg-[var(--primary)]" onPointerDown={(e) => beginCrop(e, "resize")} /></div></div>}
        </div>
        {meta && <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Info label="حجم" value={`${(meta.size / MB).toFixed(2)} MB`} /><Info label="ابعاد" value={`${meta.width}×${meta.height}`} /><Info label="مدت" value={formatTime(meta.duration)} /><Info label="فرمت" value={meta.type.replace("video/", "").toUpperCase() || "—"} /></div>}
        {output && <div className="rounded-2xl border border-[var(--primary)]/30 bg-[var(--primary)]/10 p-4"><div className="flex items-center gap-2 font-black text-[var(--primary)]"><CheckCircle2 className="h-5 w-5" /> خروجی آماده است</div><div className="mt-2 text-xs">{(output.size / MB).toFixed(2)} MB</div><button type="button" onClick={() => downloadFromUrl(output.url, output.name)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--primary)] px-4 py-3 text-sm font-black text-white"><Download className="h-4 w-4" /> دانلود ویدیو</button></div>}
      </div>
      <div className="space-y-4 rounded-2xl border border-[var(--border)] bg-[var(--surface-secondary)] p-4">
        <button type="button" onClick={() => inputRef.current?.click()} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--primary)] px-4 py-3 text-sm font-black text-white"><Upload className="h-4 w-4" /> انتخاب / تغییر ویدیو</button>
        {meta && <>
          <Section icon={<Scissors className="h-4 w-4" />} title="برش زمانی"><div className="grid grid-cols-2 gap-2"><Field label="شروع"><input value={formatTime(start)} onChange={(e) => setStart(clamp(parseTime(e.target.value), 0, Math.max(0, end - .05)))} placeholder="00:00" /></Field><Field label="پایان"><input value={formatTime(end)} onChange={(e) => setEnd(clamp(parseTime(e.target.value), Math.min(duration, start + .05), duration))} placeholder={formatTime(duration)} /></Field></div><div className="mt-3 space-y-2"><label className="block text-[10px] font-bold">شروع: {formatTime(start)}<input className="w-full accent-[var(--primary)]" type="range" min="0" max={Math.max(0, end - .05)} step=".1" value={start} onChange={(e) => setStart(Number(e.target.value))} /></label><label className="block text-[10px] font-bold">پایان: {formatTime(end)}<input className="w-full accent-[var(--primary)]" type="range" min={Math.min(duration, start + .05)} max={duration} step=".1" value={end} onChange={(e) => setEnd(Number(e.target.value))} /></label><div className="rounded-lg bg-[var(--surface)] px-3 py-2 text-[11px] font-bold">مدت خروجی: {formatTime(Math.max(0, end - start))}</div></div></Section>
          <Section icon={<Maximize2 className="h-4 w-4" />} title="تغییر سایز"><div className="grid grid-cols-2 gap-2"><Field label="عرض (px)"><input type="number" min="2" value={width} onChange={(e) => updateWidth(Number(e.target.value))} /></Field><Field label="ارتفاع (px)"><input type="number" min="2" value={height} onChange={(e) => updateHeight(Number(e.target.value))} /></Field></div><label className="mt-2 flex items-center gap-2 text-[11px] font-bold"><input type="checkbox" checked={keepRatio} onChange={(e) => setKeepRatio(e.target.checked)} /> حفظ نسبت تصویر</label><div className="mt-3 flex flex-wrap gap-2">{[[320,180],[480,270],[640,360],[720,405],[1280,720],[1080,1080],[1080,1920]].map(([w,h]) => <button key={`${w}x${h}`} type="button" onClick={() => { setWidth(w); setHeight(h); }} className="rounded-lg border border-[var(--border)] px-2 py-1 text-[11px] font-bold">{w}×{h}</button>)}</div></Section>
          <Section icon={<Maximize2 className="h-4 w-4" />} title="کراپ تصویری"><label className="flex items-center justify-between rounded-xl border border-[var(--border)] p-3 text-xs font-bold"><span>فعال‌سازی کراپ</span><input type="checkbox" checked={cropEnabled} onChange={(e) => { setCropEnabled(e.target.checked); if (e.target.checked && crop.width === 1) setCrop({ x: .1, y: .1, width: .8, height: .8 }); }} /></label><div className="mt-2 text-[11px] text-[var(--text-muted)]">کادر سفید را مستقیماً روی ویدیو بکشید؛ برای تغییر اندازه، گوشه پایین کادر را بکشید.</div></Section>
          <Section icon={<Film className="h-4 w-4" />} title="کیفیت و فرمت"><label className="block text-xs font-bold">کیفیت: {quality}%<input className="mt-2 w-full accent-[var(--primary)]" type="range" min="20" max="100" value={quality} onChange={(e) => setQuality(Number(e.target.value))} /></label><label className="mt-3 block text-xs font-bold">نرخ فریم<select value={fps} onChange={(e) => setFps(Number(e.target.value))} className="mt-2"><option value="24">24 FPS</option><option value="25">25 FPS</option><option value="30">30 FPS</option><option value="60">60 FPS</option></select></label><label className="mt-3 block text-xs font-bold">فرمت خروجی<select value={format} onChange={(e) => setFormat(e.target.value as "webm" | "mp4")} className="mt-2"><option value="webm">WebM</option><option value="mp4">MP4 — تبدیل با FFmpeg</option></select></label><button type="button" onClick={() => setMuted((x) => !x)} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl border border-[var(--border)] px-3 py-2 text-xs font-bold">{muted ? <VolumeX className="h-4 w-4" /> : <Volume2 className="h-4 w-4" />} {muted ? "حذف صدا" : "حفظ صدا"}</button></Section>
          <Section icon={<Subtitles className="h-4 w-4" />} title="زیرنویس"><div className="flex gap-2"><button type="button" onClick={() => subtitleRef.current?.click()} className="flex-1 rounded-xl border border-[var(--border)] px-3 py-2 text-xs font-bold">انتخاب SRT / VTT</button><button type="button" onClick={() => { const parsed = parseSubtitles(subtitleText); setSubtitles(parsed); setSubtitleStatus(parsed.length ? `${parsed.length} زیرنویس آماده درج است.` : "هیچ زیرنویس معتبری پیدا نشد."); }} className="rounded-xl border border-[var(--border)] px-3 py-2 text-xs font-bold">اعمال</button></div><textarea value={subtitleText} onChange={(e) => setSubtitleText(e.target.value)} placeholder="SRT یا VTT..." className="mt-2 min-h-20 w-full resize-y" />{subtitleStatus && <div className="text-[10px] font-bold text-[var(--text-muted)]">{subtitleStatus}</div>}</Section>
          <Section icon={<Film className="h-4 w-4" />} title="تصویر شاخص"><label className="block text-xs font-bold">زمان: {formatTime(thumbnailTime)}<input className="mt-2 w-full accent-[var(--primary)]" type="range" min="0" max={Math.max(0, duration - .05)} step=".1" value={thumbnailTime} onChange={(e) => setThumbnailTime(Number(e.target.value))} /></label><button type="button" disabled={busy} onClick={capture} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-[var(--border)] px-4 py-3 text-xs font-black"><Download className="h-4 w-4" /> استخراج فریم</button>{thumbnail && <img src={thumbnail} alt="تصویر شاخص" className="mt-3 max-h-36 w-full rounded-xl object-contain" />}</Section>
          <button type="button" disabled={busy} onClick={processVideo} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--primary)] px-4 py-3.5 text-sm font-black text-white disabled:opacity-50">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Film className="h-4 w-4" />} {busy ? `در حال پردازش ${progress}%` : "پردازش و ساخت خروجی"}</button>{busy && <div className="h-2 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-[var(--primary)] transition-all" style={{ width: `${progress}%` }} /></div>}
        </>}
        <button type="button" onClick={reset} className="flex w-full items-center justify-center gap-2 rounded-xl border border-[var(--border)] px-4 py-2.5 text-xs font-bold"><RotateCcw className="h-4 w-4" /> پاک کردن</button>
      </div>
    </div>
    {message && <div className="mt-5 rounded-xl bg-[var(--primary)]/10 px-4 py-3 text-sm font-bold text-[var(--primary)]">{operation !== "آماده" && <span className="ml-2 opacity-70">{operation}:</span>} {message}</div>}
    <canvas ref={canvasRef} className="hidden" />
  </div>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[var(--border)] bg-[var(--surface-secondary)] p-3"><div className="text-[10px] text-[var(--text-muted)]">{label}</div><div className="mt-1 text-xs font-black">{value}</div></div>; }
function Section({ icon, title, children }: { icon: ReactNode; title: string; children: ReactNode }) { return <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-3"><div className="flex items-center gap-2 text-sm font-black">{icon}{title}</div><div className="mt-3">{children}</div></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="text-[10px] font-bold text-[var(--text-muted)]">{label}{children}</label>; }
