"use client";
import { useEffect,useState } from "react";
import { supabase } from "@/lib/supabase";
import { GlassPanel,TusanButton } from "@/components/ui";
const STRENGTHS=["سرعت انجام","دقت","پیگیری","برخورد مناسب","تخصص","پاسخگویی"];
const WEAKNESSES=["کندی","عدم پیگیری","نیاز به توضیح بیشتر","پاسخگویی ضعیف","دقت پایین","برخورد نامناسب"];
export default function StaffOrderReview({orderId}:{orderId:string}){
 const[loading,setLoading]=useState(true),[submitted,setSubmitted]=useState(false),[rating,setRating]=useState(0),[comment,setComment]=useState(""),[strengths,setStrengths]=useState<string[]>([]),[weaknesses,setWeaknesses]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{let active=true;(async()=>{const{data,error}=await supabase.from("staff_reviews").select("id").eq("order_id",orderId).maybeSingle();if(active){setSubmitted(Boolean(data)&&!error);setLoading(false)}})();return()=>{active=false}},[orderId]);
 function toggle(value:string,kind:"strengths"|"weaknesses"){const setter=kind==="strengths"?setStrengths:setWeaknesses;setter(current=>current.includes(value)?current.filter(x=>x!==value):[...current,value])}
 async function submit(){if(rating<1||busy)return;setBusy(true);setMessage("");const{error}=await supabase.rpc("submit_staff_review",{p_order_id:orderId,p_rating:rating,p_comment:comment.trim()||null,p_strengths:strengths,p_weaknesses:weaknesses});if(error)setMessage(error.message);else{setSubmitted(true);setMessage("نظر شما با موفقیت ثبت شد. ممنون از بازخورد شما.")}setBusy(false)}
 if(loading)return null;
 if(submitted)return <GlassPanel className="p-6"><h2 className="text-xl font-bold">نظرسنجی سفارش</h2><p className="mt-3 text-sm text-[var(--text-muted)]">نظرسنجی این سفارش قبلاً ثبت شده است.</p>{message&&<p className="mt-3 text-sm">{message}</p>}</GlassPanel>;
 return <GlassPanel className="p-6"><h2 className="text-xl font-bold">نظرسنجی از نحوه انجام سفارش</h2><p className="mt-2 text-sm text-[var(--text-muted)]">امتیاز، نظر و نقاط قوت و ضعف مدیر انجام‌دهنده را ثبت کنید.</p><div className="mt-5"><div className="text-sm font-bold mb-2">امتیاز شما</div><div className="flex gap-1" dir="ltr">{[1,2,3,4,5].map(n=><button key={n} type="button" aria-label={`${n} ستاره`} onClick={()=>setRating(n)} className="text-3xl leading-none">{n<=rating?"★":"☆"}</button>)}</div></div><div className="mt-5"><div className="text-sm font-bold mb-2">نقاط قوت</div><div className="flex flex-wrap gap-2">{STRENGTHS.map(x=><button key={x} type="button" onClick={()=>toggle(x,"strengths")} className={`rounded-full border px-3 py-2 text-sm ${strengths.includes(x)?"bg-[var(--primary)]/10 border-[var(--primary)]":""}`}>{x}</button>)}</div></div><div className="mt-5"><div className="text-sm font-bold mb-2">نقاط ضعف</div><div className="flex flex-wrap gap-2">{WEAKNESSES.map(x=><button key={x} type="button" onClick={()=>toggle(x,"weaknesses")} className={`rounded-full border px-3 py-2 text-sm ${weaknesses.includes(x)?"bg-red-500/10 border-red-500/40":""}`}>{x}</button>)}</div></div><textarea value={comment} onChange={e=>setComment(e.target.value)} className="mt-5 min-h-28 w-full rounded-xl border p-3 bg-[var(--surface)]" placeholder="نظر یا پیشنهاد شما..." maxLength={2000}/>{message&&<div className="mt-3 rounded-xl border p-3 text-sm">{message}</div>}<TusanButton className="mt-4" onClick={()=>void submit()} disabled={rating<1||busy}>{busy?"در حال ثبت...":"ثبت نظرسنجی"}</TusanButton></GlassPanel>
}