"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import OrderStatus from "@/components/OrderStatus";
import OrderMessages from "@/components/OrderMessages";
import OrderFileUpload from "@/components/OrderFileUpload";
import OrderFiles from "@/components/orders/OrderFiles";
import { GlassPanel, TusanCard, TusanButton, SectionHeader } from "@/components/ui";
import { buildFieldLabelMap } from "@/lib/formFieldLabels";
import { getOrderStatusLabel } from "@/lib/orders/statusConfig";

type PaymentMethod = "online" | "card_to_card";

export default function OrderDetailPage() {
  const params = useParams(); const router = useRouter(); const id = params.id as string;
  const [order, setOrder] = useState<any>(null); const [loading, setLoading] = useState(true); const [receipt, setReceipt] = useState<File | null>(null); const [payment, setPayment] = useState<any>(null); const [receiptUploading, setReceiptUploading] = useState(false); const [receiptMessage, setReceiptMessage] = useState("");
  const STATUS_STEPS=["registered","checking","need_documents","processing","ready","completed"];
  useEffect(()=>{if(id) loadOrder();},[id]);
  async function loadOrder(){const {data:{user}}=await supabase.auth.getUser(); if(!user){router.push("/login");return;} const {data,error:orderError}=await supabase.from("orders").select(`*,services(title,icon,description,form_schema),custom_forms:form_id(id,title,schema,price),order_history(id,old_status,new_status,description,created_at)`).eq("id",id).eq("user_id",user.id).single(); if(orderError||!data){setLoading(false);return;} setOrder(data); const {data:p}=await supabase.from("payments").select("id,method,gateway,status,amount,receipt_image_url,paid_at,created_at,admin_note").eq("order_id",id).order("created_at",{ascending:false}).limit(1).maybeSingle(); setPayment(p||null); setLoading(false);}
  async function uploadReceipt(){if(!receipt||!payment){setReceiptMessage("ابتدا یک رسید انتخاب کنید.");return;} if(!["image/jpeg","image/png","image/webp","application/pdf"].includes(receipt.type)){setReceiptMessage("فرمت مجاز رسید: JPG، PNG، WEBP یا PDF است.");return;} if(receipt.size>5*1024*1024){setReceiptMessage("حجم رسید نباید بیشتر از ۵ مگابایت باشد.");return;} setReceiptUploading(true);setReceiptMessage(""); try{const {data:{session},error:sessionError}=await supabase.auth.getSession();if(sessionError||!session?.access_token)throw new Error("لطفاً دوباره وارد حساب کاربری شوید."); const body=new FormData();body.append("paymentId",payment.id);body.append("file",receipt,receipt.name); const response=await fetch("/api/payments/receipt",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`},body}); const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result?.error||"ارسال رسید ناموفق بود.");setPayment({...payment,receipt_image_url:result.filePath,status:"awaiting_manual_verification"});setReceipt(null);setReceiptMessage("رسید با موفقیت ارسال شد و در انتظار بررسی مدیریت است.");}catch(e:any){console.error(e);setReceiptMessage(e?.message||"ارسال رسید ناموفق بود.");}finally{setReceiptUploading(false);}}
  if(loading)return <div dir="rtl" className="min-h-screen page-background flex items-center justify-center text-[var(--text)]"><GlassPanel className="p-10 text-center text-[var(--text-muted)]">در حال دریافت اطلاعات سفارش...</GlassPanel></div>;
  if(!order)return <div dir="rtl" className="min-h-screen page-background p-6 text-[var(--text)]"><div className="max-w-2xl mx-auto"><GlassPanel className="p-8 text-center"><div className="text-5xl mb-4">⚠️</div><h1 className="text-xl font-bold">سفارش پیدا نشد</h1><div className="mt-6"><Link href="/orders"><TusanButton>بازگشت به سفارش‌ها</TusanButton></Link></div></GlassPanel></div></div>;
  const history=[...(order.order_history||[])].sort((a:any,b:any)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime()); const currentStep=STATUS_STEPS.indexOf(order.status); const snapshotSchema=Array.isArray(order.form_schema_snapshot)?order.form_schema_snapshot:[]; const fieldLabelMap=buildFieldLabelMap(snapshotSchema.length?snapshotSchema:order.custom_forms?.schema?.length?order.custom_forms.schema:order.services?.form_schema); const formEntries=Object.entries(order.form_data||{}); const cardPayment=payment?.method==="card_to_card"; const canUpload=cardPayment && ["pending","awaiting_manual_verification","rejected"].includes(payment.status);
  return <div dir="rtl" className="min-h-screen page-background p-6 text-[var(--text)]"><div className="max-w-3xl mx-auto space-y-5"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><SectionHeader title={`${order.services?.icon||"📋"} ${order.custom_forms?.title||order.services?.title||"سفارش"}`} description="جزئیات سفارش و روند انجام آن"/><Link href="/orders"><TusanButton variant="secondary">بازگشت به سفارش‌ها</TusanButton></Link></div>
    <GlassPanel className="p-6"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><h2 className="text-xl font-bold">{order.services?.icon} {order.custom_forms?.title||order.services?.title}</h2>{order.services?.description&&<p className="text-[var(--text-secondary)] mt-2 leading-7">{order.services.description}</p>}</div><OrderStatus status={order.status}/></div><div className="grid md:grid-cols-3 gap-4 mt-6"><TusanCard className="p-4"><div className="text-sm text-[var(--text-secondary)]">کد پیگیری</div><div className="font-bold mt-1">{order.tracking_code}</div></TusanCard><TusanCard className="p-4"><div className="text-sm text-[var(--text-secondary)]">تاریخ ثبت</div><div className="font-bold mt-1">{new Date(order.created_at).toLocaleDateString("fa-IR")}</div></TusanCard><TusanCard className="p-4"><div className="text-sm text-[var(--text-secondary)]">مبلغ سفارش</div><div className="font-bold mt-1">{Number(order.price||0).toLocaleString("fa-IR")} تومان</div></TusanCard></div>{order.status!=="cancelled"&&<div className="mt-8"><h3 className="font-bold mb-4">روند انجام سفارش</h3><div className="grid grid-cols-6 gap-2 text-center">{STATUS_STEPS.map((step,index)=>{const active=index<=currentStep;return <div key={step} className="flex flex-col items-center"><div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold ${active?"bg-[#09967C] text-white":"bg-gray-200 text-gray-500"}`}>{index+1}</div><div className="text-xs mt-2 text-[var(--text-secondary)] leading-5">{getOrderStatusLabel(step)}</div></div>})}</div></div>}</GlassPanel>
    {cardPayment&&<GlassPanel className="p-6 border border-amber-200"><h2 className="text-xl font-bold mb-3">رسید پرداخت کارت‌به‌کارت</h2>{payment.status==="paid"?<div className="rounded-xl bg-green-50 text-green-700 p-4">پرداخت شما تأیید شده است.</div>:<><p className="text-sm text-[var(--text-secondary)] leading-7 mb-4">رسید واریز را حداکثر تا ۲۴ ساعت پس از ثبت سفارش ارسال کنید. پس از بررسی مدیریت، پرداخت تأیید خواهد شد.</p>{payment.receipt_image_url&&<div className="rounded-xl bg-blue-50 text-blue-700 p-4 mb-4">رسید ارسال شده و در انتظار بررسی مدیریت است.</div>}{payment.status==="rejected"&&<div className="rounded-xl bg-red-50 text-red-700 p-4 mb-4">رسید قبلی تأیید نشده است. لطفاً رسید صحیح را دوباره ارسال کنید.</div>}{canUpload&&<div className="space-y-3"><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setReceipt(e.target.files?.[0]||null)} className="block w-full rounded-xl border border-[var(--border)] bg-[var(--surface-strong)] p-3 text-sm text-[var(--text)]"/><div className="text-xs text-[var(--text-muted)]">حداکثر ۵ مگابایت — JPG، PNG، WEBP یا PDF</div><TusanButton type="button" onClick={uploadReceipt} disabled={!receipt||receiptUploading}>{receiptUploading?"در حال ارسال...":"ارسال رسید پرداخت"}</TusanButton>{receiptMessage&&<div className="text-sm leading-6">{receiptMessage}</div>}</div>}</>}</GlassPanel>}
    <GlassPanel className="p-6"><h2 className="text-xl font-bold mb-4">اطلاعات ثبت شده</h2>{formEntries.length===0?<p className="text-[var(--text-muted)]">اطلاعاتی برای این سفارش ثبت نشده است.</p>:<div className="grid md:grid-cols-2 gap-4">{formEntries.map(([key,value]:any)=><div key={key} className="border border-[var(--border)] rounded-xl p-4 bg-[var(--surface)]"><div className="text-sm text-[var(--text-secondary)] mb-1">{fieldLabelMap[key]||key}</div><div className="font-bold break-words">{Array.isArray(value)?value.join("، "):value===true?"بله":value===false?"خیر":String(value??"---")}</div></div>)}</div>}</GlassPanel>
    <OrderMessages orderId={order.id}/><OrderFiles orderId={order.id}/><OrderFileUpload orderId={order.id}/><GlassPanel className="p-6"><h2 className="text-xl font-bold mb-5">تاریخچه سفارش</h2>{history.length===0?<p className="text-[var(--text-muted)]">هنوز تاریخچه‌ای ثبت نشده است.</p>:<div className="space-y-5">{history.map((item:any)=><div key={item.id} className="border-r-4 border-[var(--primary)] pr-4"><p className="font-bold">{item.old_status===item.new_status?"ثبت سفارش":`تغییر وضعیت از ${getOrderStatusLabel(item.old_status)} به ${getOrderStatusLabel(item.new_status)}`}</p>{item.description&&<p className="text-[var(--text-secondary)] text-sm mt-1">{item.description}</p>}<p className="text-[var(--text-muted)] text-sm mt-2">{new Date(item.created_at).toLocaleString("fa-IR")}</p></div>)}</div>}</GlassPanel>
  </div></div>;
}
