"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {GlassPanel,SectionHeader} from "@/components/ui";
import {supabase} from "@/lib/supabase";

type User={id:string;full_name:string|null;phone:string|null;role:string|null};
type StaffRole={code:string;name:string};type RoleAssignment={user_id:string;status:string;commission_percent:number;staff_roles?:StaffRole|StaffRole[]|null};
type Service={id:string;title:string;icon:string|null;category:string|null};type Access={user_id:string;service_id:string;status:string;commission_percent:number};
type CategoryAccess={user_id:string;category:string;status:string;commission_percent:number};type Rating={staff_id:string;full_name:string|null;avatar_url:string|null;review_count:number;average_rating:number};
const roleCode=(r:RoleAssignment)=>Array.isArray(r.staff_roles)?r.staff_roles[0]?.code:r.staff_roles?.code;
export default function StaffAdminPage(){
 const[users,setUsers]=useState<User[]>([]),[roles,setRoles]=useState<RoleAssignment[]>([]),[services,setServices]=useState<Service[]>([]),[access,setAccess]=useState<Access[]>([]),[categories,setCategories]=useState<CategoryAccess[]>([]),[ratings,setRatings]=useState<Rating[]>([]),[tab,setTab]=useState<"users"|"managers">("users"),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);setError("");try{const{data:{user},error:ae}=await supabase.auth.getUser();if(ae||!user)throw new Error("نشست مدیر معتبر نیست. لطفاً دوباره وارد شوید.");const{data:me,error:pe}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(pe||me?.role!=="admin")throw new Error("فقط مدیر اصلی به این بخش دسترسی دارد.");const[{data:u,error:ue},{data:r,error:re},{data:s,error:se},{data:a,error:xe},{data:c,error:ce},{data:rt,error:rte}]=await Promise.all([supabase.rpc("get_staff_candidates"),supabase.from("staff_role_assignments").select("user_id,status,commission_percent,staff_roles(code,name)"),supabase.from("services").select("id,title,icon,category").eq("is_active",true).order("title"),supabase.from("staff_service_access").select("user_id,service_id,status,commission_percent"),supabase.from("staff_category_access").select("user_id,category,status,commission_percent"),supabase.rpc("get_staff_ratings")]);const e=ue||re||se||xe||ce||rte;if(e)throw e;setUsers((u||[])as User[]);setRoles((r||[])as unknown as RoleAssignment[]);setServices((s||[])as Service[]);setAccess((a||[])as Access[]);setCategories((c||[])as CategoryAccess[]);setRatings((rt||[])as Rating[])}catch(e){console.error("Staff admin load failed",e);setError(e instanceof Error?e.message:"خطا در بارگذاری اطلاعات")}finally{setLoading(false)}}
 const managers=useMemo(()=>users.filter(u=>roles.some(r=>r.user_id===u.id&&r.status==="approved")),[users,roles]);
 const normalUsers=useMemo(()=>users.filter(u=>!roles.some(r=>r.user_id===u.id&&r.status==="approved")),[users,roles]);
 const filtered=(tab==="users"?normalUsers:managers).filter(u=>`${u.full_name||""} ${u.phone||""}`.toLowerCase().includes(search.trim().toLowerCase()));
 const managerRole=(id:string)=>roles.find(r=>r.user_id===id&&r.status==="approved"&&roleCode(r)==="order_manager");
 const categoryNames=useMemo(()=>Array.from(new Set(services.map(s=>s.category).filter(Boolean) as string[])).sort((a,b)=>a.localeCompare(b,"fa")),[services]);
 async function setRole(user:User,code:string,approve:boolean){setBusy(user.id+code);setError("");try{let pct=0;if(approve){const raw=window.prompt(`درصد کارمزد ${code==="order_manager"?"مدیر سفارشات":"اپراتور پشتیبانی"} را وارد کنید`,`0`);if(raw===null)return;pct=Number(raw.replace(/,/g,"."));if(!Number.isFinite(pct)||pct<0||pct>100)throw new Error("درصد کارمزد باید بین ۰ تا ۱۰۰ باشد.")}const{error:e}=await supabase.rpc("approve_staff_role",{p_user_id:user.id,p_role_code:code,p_approve:approve,p_commission:pct});if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:"عملیات انجام نشد")}finally{setBusy("")}}
 async function toggleCategory(userId:string,category:string,active:boolean){setBusy(userId+category);setError("");try{let pct=Number(managerRole(userId)?.commission_percent||0);if(!active){const raw=window.prompt(`درصد کارمزد دسته «${category}» را وارد کنید`,String(pct));if(raw===null)return;pct=Number(raw.replace(/,/g,"."));if(!Number.isFinite(pct)||pct<0||pct>100)throw new Error("درصد نامعتبر است")}const{error:e}=await supabase.rpc("set_staff_category_access",{p_user_id:userId,p_category:category,p_approve:!active,p_commission:pct});if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:"عملیات انجام نشد")}finally{setBusy("")}}
 async function toggleService(userId:string,serviceId:string,active:boolean){setBusy(userId+serviceId);setError("");try{const pct=Number(managerRole(userId)?.commission_percent||0);const{error:e}=await supabase.rpc("set_staff_service_access",{p_user_id:userId,p_service_id:serviceId,p_approve:!active,p_commission:pct});if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:"عملیات انجام نشد")}finally{setBusy("")}}
 return <main dir="rtl" className="min-h-screen page-background p-4 sm:p-6 text-[var(--text)]"><div className="mx-auto max-w-7xl space-y-6"><div className="flex items-center justify-between gap-4"><SectionHeader title="مدیریت کاربران و مدیران" description="مدیریت نقش‌ها، کارمزد، خدمات و دسته‌بندی‌های مجاز"/><Link href="/admin" className="text-sm font-bold text-[var(--primary)]">بازگشت به پنل ←</Link></div>{error&&<GlassPanel className="p-4 text-sm font-bold text-red-600">{error}</GlassPanel>}
 <GlassPanel className="p-2"><div className="grid grid-cols-2 gap-2"><button onClick={()=>{setTab("users");setSearch("")}} className={`rounded-xl px-4 py-3 font-bold ${tab==="users"?"bg-[var(--primary)] text-white":"hover:bg-[var(--surface)]"}`}>👤 کاربران <span className="text-xs opacity-80">({normalUsers.length.toLocaleString("fa-IR")})</span></button><button onClick={()=>{setTab("managers");setSearch("")}} className={`rounded-xl px-4 py-3 font-bold ${tab==="managers"?"bg-[var(--primary)] text-white":"hover:bg-[var(--surface)]"}`}>👥 مدیران و اپراتورها <span className="text-xs opacity-80">({managers.length.toLocaleString("fa-IR")})</span></button></div></GlassPanel>
 <GlassPanel className="p-4"><div className="relative"><span className="absolute right-4 top-3.5">🔎</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={tab==="users"?"جستجو بر اساس نام یا شماره تلفن کاربر...":"جستجو بین مدیران بر اساس نام یا شماره تلفن..."} className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] py-3 pr-11 pl-4 outline-none focus:ring-2 focus:ring-[var(--primary)]"/></div><div className="mt-2 text-xs text-[var(--text-muted)]">{filtered.length.toLocaleString("fa-IR")} مورد از { (tab==="users"?normalUsers.length:managers.length).toLocaleString("fa-IR")} مورد</div></GlassPanel>
 {loading?<GlassPanel className="p-10 text-center">در حال بارگذاری...</GlassPanel>:filtered.length===0?<GlassPanel className="p-10 text-center"><div className="text-4xl mb-3">🔍</div><div className="font-bold">موردی پیدا نشد.</div></GlassPanel>:<div className="space-y-4">{filtered.map(u=>{const mr=managerRole(u.id);const op=roles.find(r=>r.user_id===u.id&&r.status==="approved"&&roleCode(r)==="support_operator");return <GlassPanel key={u.id} className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="font-black text-lg">{u.full_name||"کاربر بدون نام"}</div><div className="mt-1 text-xs text-[var(--text-muted)]">{u.phone||"بدون شماره"}</div>{tab==="managers"&&<div className="mt-2 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-[var(--primary)]/10 px-2 py-1">{mr?`مدیر سفارشات · ${Number(mr.commission_percent||0).toLocaleString("fa-IR")}%`:""}</span>{op&&<span className="rounded-full bg-blue-500/10 px-2 py-1 text-blue-700">اپراتور پشتیبانی</span>}{mr&&<span className="rounded-full bg-yellow-500/10 px-2 py-1">⭐ {Number(ratings.find(x=>x.staff_id===u.id)?.average_rating||0).toLocaleString("fa-IR")} ({Number(ratings.find(x=>x.staff_id===u.id)?.review_count||0).toLocaleString("fa-IR")})</span>}</div>}</div><div className="flex flex-wrap gap-2">{tab==="users"?<><button onClick={()=>void setRole(u,"order_manager",true)} disabled={!!busy} className="rounded-xl bg-[var(--primary)] px-4 py-2.5 text-xs font-black text-white">اعطای مدیر سفارشات</button><button onClick={()=>void setRole(u,"support_operator",true)} disabled={!!busy} className="rounded-xl bg-blue-600/10 px-4 py-2.5 text-xs font-black text-blue-700">اعطای پشتیبانی</button></>:<><button onClick={()=>void setRole(u,"order_manager",false)} disabled={!!busy} className="rounded-xl bg-red-500/10 px-4 py-2.5 text-xs font-black text-red-700">لغو مدیر سفارشات</button>{op&&<button onClick={()=>void setRole(u,"support_operator",false)} disabled={!!busy} className="rounded-xl bg-red-500/10 px-4 py-2.5 text-xs font-black text-red-700">لغو پشتیبانی</button>}</>}</div></div>
 {tab==="managers"&&mr&&<div className="mt-5 border-t border-[var(--border)] pt-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div className="font-black">دسترسی خدمات</div><div className="text-xs text-[var(--text-muted)]">کارمزد پایه مدیر: {Number(mr.commission_percent||0).toLocaleString("fa-IR")}% · هنگام اعطای نقش همه خدمات فعال شده‌اند</div></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{categoryNames.map(cat=>{const ca=categories.find(x=>x.user_id===u.id&&x.category===cat),active=ca?.status==="approved";return <button key={cat} onClick={()=>void toggleCategory(u.id,cat,active)} disabled={!!busy} className={`rounded-xl border p-3 text-right ${active?"border-[var(--primary)] bg-[var(--primary)]/8":"border-[var(--border)]"}`}><div className="font-bold">📁 {cat}</div><div className="mt-1 text-[10px] text-[var(--text-muted)]">{active?`محدودسازی دسته فعال · ${Number(ca!.commission_percent).toLocaleString("fa-IR")}% · لغو دسته`:"فعال‌سازی/تخصیص اختصاصی دسته"}</div></button>})}</div><details className="mt-4"><summary className="cursor-pointer text-sm font-bold">نمایش خدمات و تغییر دستی (اختیاری)</summary><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{services.map(s=>{const a=access.find(x=>x.user_id===u.id&&x.service_id===s.id),active=a?.status==="approved";return <button key={s.id} onClick={()=>void toggleService(u.id,s.id,active)} disabled={!!busy} className={`rounded-xl border p-3 text-right ${active?"border-green-500 bg-green-500/5":"border-[var(--border)]"}`}><div className="font-bold">{s.icon} {s.title}</div><div className="mt-1 text-[10px]">{active?"فعال":"غیرفعال"}</div></button>})}</div></details></div>}
 </GlassPanel>})}</div>}
 <GlassPanel className="p-5"><div className="font-black">⭐ رتبه‌بندی مدیران</div><p className="mt-1 text-xs text-[var(--text-muted)]">امتیاز و نظر مشتریان در تکمیل سفارش ثبت می‌شود و در اینجا قابل مشاهده است؛ مبنای تغییر کارمزد یا محدودسازی در مرحله بعدی قابل توسعه است.</p></GlassPanel>
 </div></main>;
}
