"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { supabase } from "@/lib/supabase";
import OrderStatus from "@/components/orders/OrderStatus";
import TusanIcon from "@/components/ui/TusanIcon";
import OrderAssignmentRequests from "@/components/admin/OrderAssignmentRequests";
import ReadyOrders from "@/components/admin/ReadyOrders";
import { GlassPanel,TusanButton,TusanInput,SectionHeader,TusanTable,TusanStatCard } from "@/components/ui";

export default function AdminOrdersPage(){
 const [orders,setOrders]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[statusFilter,setStatusFilter]=useState("all");
 useEffect(()=>{void loadOrders()},[]);
 async function loadOrders(){setLoading(true);setError("");try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("برای مشاهده سفارش‌ها باید وارد حساب کاربری شوید.");const {data,error}=await supabase.rpc("get_staff_orders");if(error)throw new Error(error.message);setOrders(Array.isArray(data)?data:[])}catch(e:any){console.error(e);setError(e?.message||"دریافت سفارش‌ها انجام نشد. لطفاً دوباره تلاش کنید.")}finally{setLoading(false)}}
 const filtered=useMemo(()=>orders.filter(o=>{if(statusFilter!=="all"&&o.status!==statusFilter)return false;const q=search.trim().toLowerCase();if(!q)return true;return [o.tracking_code,o.customer?.full_name,o.customer?.phone,o.customer?.email,o.service?.title].some(v=>String(v||"").toLowerCase().includes(q))}),[orders,search,statusFilter]);
 const counts=useMemo(()=>{const c:any={all:orders.length};orders.forEach(o=>c[o.status]=(c[o.status]||0)+1);return c},[orders]);
 const statuses=["all","registered","checking","need_documents","processing","ready","completed","cancelled"];
 if(loading)return <div dir="rtl" className="min-h-screen flex items-center justify-center page-background"><GlassPanel className="p-8 text-center"><TusanIcon name="clipboard" size={28} className="text-[var(--primary)]"/><p className="mt-4">در حال دریافت سفارش‌ها...</p></GlassPanel></div>;
 return <div dir="rtl" className="min-h-screen page-background p-6 text-[var(--text)]"><div className="max-w-6xl mx-auto"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-6"><SectionHeader title="مدیریت سفارش‌ها" description="مشاهده و مدیریت سفارش‌های ثبت‌شده توسط مشتریان"/><Link href="/admin"><TusanButton variant="outline">← بازگشت به پنل مدیریت</TusanButton></Link></div><OrderAssignmentRequests/>{error&&<GlassPanel className="p-4 mb-5 border-red-500/20 bg-red-500/10 text-red-600">{error}</GlassPanel>}{!error&&<><ReadyOrders orders={orders} onUpdated={()=>void loadOrders()}/><div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6"><TusanStatCard title="کل سفارش‌ها" value={orders.length.toLocaleString("fa-IR")} icon="📋"/><TusanStatCard title="در حال بررسی" value={(counts.checking||0).toLocaleString("fa-IR")} icon="🔎"/><TusanStatCard title="در حال انجام" value={(counts.processing||0).toLocaleString("fa-IR")} icon="⚙️"/><TusanStatCard title="تکمیل شده" value={(counts.completed||0).toLocaleString("fa-IR")} icon="✅"/></div><GlassPanel className="p-5 mb-6"><div className="grid md:grid-cols-2 gap-4"><div><label className="block text-sm font-bold mb-2">جستجو</label><TusanInput icon="🔍" value={search} onChange={e=>setSearch(e.target.value)} placeholder="کد پیگیری، نام مشتری، شماره تماس یا نام خدمت..."/></div><div><label className="block text-sm font-bold mb-2">وضعیت سفارش</label><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="w-full border border-[var(--border)] rounded-xl px-4 py-3 bg-[var(--surface)]">{statuses.map(s=><option key={s} value={s}>{s==="all"?"همه سفارش‌ها":s} ({counts[s]||0})</option>)}</select></div></div></GlassPanel>{orders.length===0?<GlassPanel className="p-10 text-center">📭<h2 className="mt-4 font-bold">هنوز سفارشی ثبت نشده است</h2></GlassPanel>:<TusanTable columns={[{key:"tracking",title:"کد پیگیری"},{key:"customer",title:"مشتری"},{key:"service",title:"خدمت"},{key:"status",title:"وضعیت"},{key:"price",title:"مبلغ",align:"left"},{key:"created",title:"تاریخ ثبت"},{key:"actions",title:"عملیات",align:"left"}]} rows={filtered.map(o=>({tracking:o.tracking_code||"---",customer:<div><div className="font-bold">{o.customer?.full_name||o.customer?.email||"---"}</div><div className="text-xs text-[var(--text-muted)]">{o.customer?.phone||o.customer?.email||"---"}</div></div>,service:<div>{o.service?.icon||"📋"} {o.service?.title||"خدمت نامشخص"}</div>,status:<OrderStatus status={o.status}/>,price:<span className="font-bold text-[var(--primary)]">{Number(o.price||0).toLocaleString("fa-IR")} تومان</span>,created:new Date(o.created_at).toLocaleDateString("fa-IR"),actions:<Link href={`/admin/orders/${o.id}`}><TusanButton size="sm" variant="outline">مدیریت</TusanButton></Link>}))}/>}</>}</div></div>
}