"use client";

import { useState } from "react";

type Kind = "text"|"textarea"|"number"|"date"|"select"|"multi"|"checkbox"|"file"|"section";
type Field = {id:string; kind:Kind; label:string; placeholder:string; help:string; required:boolean; options:string[]; condition?:{fieldId:string; value:string}};
const labels:Record<Kind,string>={text:"متن کوتاه",textarea:"توضیحات",number:"عدد",date:"تاریخ",select:"انتخابی",multi:"چندانتخابی",checkbox:"تأیید",file:"فایل",section:"عنوان بخش"};
const initial:Field[]=[{id:"name",kind:"text",label:"نام و نام خانوادگی",placeholder:"نام را وارد کنید",help:"",required:true,options:[]}];

export default function FormBuilder(){
 const [title,setTitle]=useState("پیش‌فرم ثبت‌نام"),[fields,setFields]=useState<Field[]>(initial),[selected,setSelected]=useState("name"),[mode,setMode]=useState<"edit"|"preview">("edit"),[theme,setTheme]=useState("default");
 const selectedField=fields.find(f=>f.id===selected);
 const add=(kind:Kind)=>{const id=`f-${Date.now()}`,f:Field={id,kind,label:labels[kind],placeholder:"",help:"",required:false,options:kind==="select"||kind==="multi"?["گزینه اول","گزینه دوم"]:[]};setFields(v=>[...v,f]);setSelected(id)};
 const update=(patch:Partial<Field>)=>setFields(v=>v.map(f=>f.id===selected?{...f,...patch}:f));
 const remove=()=>{const next=fields.filter(f=>f.id!==selected);setFields(next);setSelected(next[0]?.id||"")};
 const move=(dir:number)=>{const i=fields.findIndex(f=>f.id===selected),j=i+dir;if(i<0||j<0||j>=fields.length)return;const a=[...fields];[a[i],a[j]]=[a[j],a[i]];setFields(a)};
 const cls=theme==="mono"?"bg-white border-black":theme==="admin"?"bg-slate-50 border-slate-400":"bg-[var(--surface)] border-[var(--border)]";
 return <main dir="rtl" className="min-h-screen bg-[var(--background)] p-4 text-[var(--text)] md:p-8"><style jsx global>{`@media print{body *{visibility:hidden!important}.form-print,.form-print *{visibility:visible!important}.form-print{position:absolute!important;inset:0!important;width:100%!important;padding:10mm!important}.no-print{display:none!important}.form-brand{display:block!important}}.form-brand{display:none}`}</style>
 <div className="no-print mx-auto max-w-7xl"><h1 className="text-3xl font-black">فرم‌ساز کافی‌نت توسن</h1><p className="mt-2 text-sm text-[var(--text-muted)]">یک پیش‌فرم ثبت‌نام بساز، فیلدها را مرتب کن و برای فیلدها نمایش شرطی تعریف کن.</p><div className="mt-5 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4 text-sm leading-7"><b>راهنمای سریع:</b> نوع فیلد را از ستون چپ اضافه کنید، روی فیلد کلیک کنید و تنظیماتش را در ستون راست تغییر دهید. برای نمایش شرطی، یک فیلد وابسته و مقدار شرط را مشخص کنید.</div></div>
 <div className="mx-auto mt-5 grid max-w-7xl gap-5 lg:grid-cols-[240px_1fr_300px]">
 <aside className="no-print rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-4"><h2 className="font-black">افزودن فیلد</h2><div className="mt-3 grid grid-cols-2 gap-2">{(Object.keys(labels) as Kind[]).map(k=><button key={k} onClick={()=>add(k)} className="rounded-xl border border-[var(--border)] p-2 text-xs font-bold hover:border-[var(--primary)]">+ {labels[k]}</button>)}</div><button onClick={()=>setMode(mode==="edit"?"preview":"edit")} className="mt-5 w-full rounded-xl bg-[var(--primary)] p-3 font-bold text-white">{mode==="edit"?"پیش‌نمایش فرم":"بازگشت به ویرایش"}</button><button onClick={()=>window.print()} className="mt-2 w-full rounded-xl border border-[var(--border)] p-3 font-bold">چاپ / PDF</button></aside>
 <section className={`form-print rounded-3xl border p-6 shadow-sm ${cls}`}><header className="mb-6 border-b pb-4 text-center"><h2 className="text-2xl font-black">{title}</h2><div className="mt-2 text-sm text-slate-500">فرم ثبت اطلاعات</div></header>{mode==="edit"?<div className="space-y-3">{fields.map(f=><div key={f.id} onClick={()=>setSelected(f.id)} className={`cursor-pointer rounded-2xl border p-4 ${selected===f.id?"border-[var(--primary)] ring-2 ring-[var(--primary)]/20":"border-[var(--border)]"}`}><div className="flex justify-between"><b>{f.label}{f.required&&<span className="text-red-500"> *</span>}</b><span className="text-xs text-slate-400">{labels[f.kind]}</span></div>{f.help&&<p className="mt-1 text-xs text-slate-500">{f.help}</p>}</div>)}</div>:<FormPreview fields={fields} title={title}/>}<div className="form-brand mt-8 text-center text-xs font-bold">کافی‌نت توسن | tusancn.ir</div></section>
 <aside className="no-print rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-black">تنظیمات فرم</h2><input value={title} onChange={e=>setTitle(e.target.value)} className="mt-3 w-full rounded-xl border border-[var(--border)] bg-transparent p-3" placeholder="عنوان فرم"/><div className="mt-5"><b>قالب</b><div className="mt-2 grid grid-cols-3 gap-2">{[["default","پیش‌فرض"],["admin","اداری"],["mono","سیاه‌وسفید"]].map(([v,l])=><button key={v} onClick={()=>setTheme(v)} className={`rounded-xl border p-2 text-xs ${theme===v?"border-[var(--primary)] bg-[var(--primary)] text-white":"border-[var(--border)]"}`}>{l}</button>)}</div></div>{selectedField&&<div className="mt-5 border-t pt-5"><h3 className="font-black">تنظیم فیلد</h3><label className="mt-3 block text-xs">عنوان<input value={selectedField.label} onChange={e=>update({label:e.target.value})} className="mt-1 w-full rounded-xl border p-2"/></label><label className="mt-3 block text-xs">Placeholder<input value={selectedField.placeholder} onChange={e=>update({placeholder:e.target.value})} className="mt-1 w-full rounded-xl border p-2"/></label><label className="mt-3 block text-xs">راهنما<input value={selectedField.help} onChange={e=>update({help:e.target.value})} className="mt-1 w-full rounded-xl border p-2"/></label><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={selectedField.required} onChange={e=>update({required:e.target.checked})}/> اجباری</label>{(selectedField.kind==="select"||selectedField.kind==="multi")&&<label className="mt-3 block text-xs">گزینه‌ها<textarea value={selectedField.options.join("\n")} onChange={e=>update({options:e.target.value.split(/\n/).filter(Boolean)})} className="mt-1 w-full rounded-xl border p-2" rows={4}/></label>}
 <div className="mt-4 rounded-xl border p-3"><b className="text-sm">نمایش شرطی</b><select value={selectedField.condition?.fieldId||""} onChange={e=>{const fieldId=e.target.value;update({condition:fieldId?{fieldId,value:""}:undefined})}} className="mt-2 w-full rounded-lg border p-2 text-sm"><option value="">بدون شرط</option>{fields.filter(f=>f.id!==selectedField.id&&f.kind!=="section").map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select>{selectedField.condition&&<input value={selectedField.condition.value} onChange={e=>update({condition:{...selectedField.condition!,value:e.target.value}})} placeholder="نمایش وقتی مقدار برابر است با..." className="mt-2 w-full rounded-lg border p-2 text-sm"/>}</div>
 <div className="mt-4 flex gap-2"><button onClick={()=>move(-1)} className="flex-1 rounded-lg border p-2 text-xs">↑ بالا</button><button onClick={()=>move(1)} className="flex-1 rounded-lg border p-2 text-xs">↓ پایین</button></div><button onClick={remove} className="mt-2 w-full rounded-lg bg-red-50 p-2 text-xs font-bold text-red-600">حذف فیلد</button></div>}</aside>
 </div></main>
}
function FormPreview({fields,title}:{fields:Field[];title:string}){const [values,setValues]=useState<Record<string,string>>({});return <div><h3 className="mb-5 text-lg font-black">{title}</h3><div className="space-y-4">{fields.map(f=>{if(f.kind==="section")return <h4 key={f.id} className="border-b pb-2 text-lg font-black">{f.label}</h4>;if(f.condition&&values[f.condition.fieldId]!==f.condition.value)return null;return <label key={f.id} className="block text-sm font-bold">{f.label}{f.required&&<span className="text-red-500"> *</span>}{f.kind==="textarea"?<textarea placeholder={f.placeholder} className="mt-2 min-h-28 w-full rounded-xl border p-3" onChange={e=>setValues(v=>({...v,[f.id]:e.target.value}))}/>:f.kind==="select"?<select className="mt-2 w-full rounded-xl border p-3" onChange={e=>setValues(v=>({...v,[f.id]:e.target.value}))}><option value="">انتخاب کنید</option>{f.options.map(o=><option key={o}>{o}</option>)}</select>:f.kind==="multi"?<div className="mt-2 space-y-2">{f.options.map(o=><label key={o} className="block"><input type="checkbox"/> <span>{o}</span></label>)}</div>:f.kind==="checkbox"?<input type="checkbox" className="mr-2"/>:f.kind==="file"?<input type="file" className="mt-2 block"/>:<input type={f.kind==="number"?"number":f.kind==="date"?"date":"text"} placeholder={f.placeholder} className="mt-2 w-full rounded-xl border p-3" onChange={e=>setValues(v=>({...v,[f.id]:e.target.value}))}/>}</label>})}</div></div>}
