import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabaseServer";
import ServiceOrderClient from "./ServiceOrderClient";

export const revalidate = 300;

type Service = { id: string; title: string; category: string | null; description: string | null; price: number; icon: string | null; form_schema: any[]; is_active: boolean; parent_service_id: string | null; updated_at?: string | null; created_at?: string | null };
function normalizeSchema(value: any): any[] { if (Array.isArray(value)) return value; if (typeof value === "string") { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed : []; } catch { return []; } } return []; }
async function getService(id: string): Promise<Service | null> { const supabase = createSupabaseServerClient(); const { data, error } = await supabase.from("services").select("id,title,category,description,price,icon,form_schema,is_active,parent_service_id,updated_at,created_at").eq("id", id).eq("is_active", true).single(); if (error || !data) return null; return { ...data, price: Number(data.price || 0), form_schema: normalizeSchema(data.form_schema) } as Service; }

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> { const { id } = await params; const service = await getService(id); if (!service) return { title: "خدمت پیدا نشد", robots: { index: false, follow: false } }; const title = `${service.title} | کافی نت توسن`; const description = service.description?.trim() || `ثبت درخواست ${service.title} در کافی نت توسن با امکان ثبت آنلاین و پیگیری سفارش.`; const canonical = `/services/${service.id}`; return { title, description, keywords: [service.title, service.category, "کافی نت توسن", "خدمات آنلاین", "ثبت درخواست آنلاین"].filter(Boolean) as string[], alternates: { canonical }, openGraph: { type: "website", locale: "fa_IR", url: canonical, siteName: "کافی نت توسن", title, description }, robots: { index: true, follow: true } }; }

export default async function ServicePage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const service = await getService(id); if (!service) notFound(); const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://tusan.ir"; const jsonLd = { "@context": "https://schema.org", "@type": "Service", name: service.title, description: service.description || undefined, url: `${siteUrl}/services/${service.id}`, provider: { "@type": "LocalBusiness", name: "کافی نت توسن", url: siteUrl }, areaServed: { "@type": "Country", name: "ایران" }, ...(service.price > 0 ? { offers: { "@type": "Offer", price: service.price, priceCurrency: "IRR", url: `${siteUrl}/services/${service.id}` } } : {}) }; return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><ServiceOrderClient initialService={service} /></>; }
