"use client";
import { useEffect, useRef, useState } from "react";
import { motion, useAnimationFrame, useMotionValue } from "framer-motion";
import Link from "next/link";

type Service={id:string;name:string;description:string|null;customer_unit_price:number|null};
type Platform={id:string;name:string;is_active:boolean;sort_order:number};

export default function SocialServicesRail(){
 const[items,setItems]=useState<Service[]>([]),[platforms,setPlatforms]=useState<Platform[]>([]),[selected,setSelected]=useState<Service|null>(null),ref=useRef<HTMLDivElement>(null),x=useMotionValue(0),[travel,setTravel]=useState(0);
 useEffect(()=>{fetch("/api/social/catalog",{cache:"no-store"}).then(r=>r.json()).then(p=>{if(!p?.ok)return;setItems((p.services||[]).filter((s:Service)=>s?.name));setPlatforms((p.platforms||[]).filter((v:Platform)=>v?.is_active).sort((a:Platform,b:Platform)=>a.sort_order-b.sort_order))}).catch(()=>{setItems([]);setPlatforms([])})},[]);
 useEffect(()=>{const f=()=>setTravel((ref.current?.scrollWidth||0)/2);f();window.addEventListener("resize",f);return()=>window.removeEventListener("resize",f)},[items]);
 useAnimationFrame((_,d)=>{if(selected||!travel)return;const n=x.get()+d*.03;x.set(n>travel?n-travel:n)});
 if(!items.length)return null;
 return <section id="social-services" className="relative py-7 sm:py-9" dir="rtl"><div className="mx-auto max-w-[88rem] px-2 sm:px-4 lg:px-6"><div className="mb-4 text-center"><h2 className="text-2xl font-black">خدمات شبکه‌های اجتماعی</h2><p className="mt-1 text-sm text-[var(--text-muted)]">سرویس‌های محبوب را در ریل ببینید و برای ورود مستقیم به خدمات هر پلتفرم، از بخش زیر انتخاب کنید.</p></div><div className="relative w-full overflow-hidden rounded-3xl border border-[var(--primary)]/20 bg-[var(--primary)] py-3.5 shadow-sm"><motion.div ref={ref} style={{x}} className="flex w-max gap-5 px-5" dir="ltr">{[...items,...items].map((s,i)=><div key={`${s.id}-${i}`} className="relative shrink-0" dir="rtl"><button type="button" onClick={()=>setSelected(v=>v?.id===s.id?null:s)} className="rounded-full border border-white/70 bg-white px-7 py-3.5 text-sm font-black whitespace-nowrap text-slate-900 shadow-sm transition hover:bg-white/90">{s.name}{s.customer_unit_price!=null&&<span className="mr-2 text-[var(--primary)]">{Number(s.customer_unit_price).toLocaleString("fa-IR")} تومان</span>}</button></div>)}</motion.div></div><div className="mt-4 rounded-3xl border border-[var(--border)] bg-[var(--surface)]/70 p-3 sm:p-4"><div className="mb-3 flex items-center justify-between gap-3 px-1"><h3 className="text-sm font-black text-[var(--text)] sm:text-base">پلتفرم‌ها</h3><Link href="/social" className="text-xs font-bold text-[var(--primary)] hover:underline">همه پلتفرم‌ها</Link></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6">{platforms.map(p=><Link key={p.id} href={`/social?platform=${encodeURIComponent(p.id)}`} className="flex min-h-14 items-center justify-center rounded-2xl border border-[var(--border)] bg-[var(--background)] px-3 py-3 text-center text-sm font-black text-[var(--text)] transition hover:-translate-y-0.5 hover:border-[var(--primary)] hover:text-[var(--primary)]">{p.name}</Link>)}</div></div>{selected&&<div className="relative z-40 mx-auto mt-3 w-full max-w-2xl"><motion.div initial={{opacity:0,y:-12,scale:.98}} animate={{opacity:1,y:0,scale:1}} className="rounded-2xl border border-[var(--primary)]/20 bg-[var(--surface)] p-4 text-right shadow-xl"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black">{selected.name}</h3>{selected.customer_unit_price!=null&&<span className="mt-1 block text-sm font-bold text-[var(--primary)]">{Number(selected.customer_unit_price).toLocaleString("fa-IR")} تومان</span>}</div><button type="button" onClick={()=>setSelected(null)} className="rounded-lg px-2 py-1 text-lg" aria-label="بستن">×</button></div><p className="mt-3 text-sm leading-7 text-[var(--text-muted)]">{selected.description||"توضیحات این خدمت در دسترس است."}</p><Link href={`/social?service=${encodeURIComponent(selected.id)}`} className="mt-3 block rounded-xl bg-[var(--primary)] px-4 py-2 text-center text-sm font-black text-white">مشاهده و ثبت سفارش</Link></motion.div></div>}</div></section>;
}
