"use client";
import { useEffect,useRef,useState } from "react";
import Link from "next/link";
import { Bot,MessageCircle,Send,X,CheckCircle,Star,Search,ArrowRight,LifeBuoy,UserRound } from "lucide-react";
import { supabase } from "@/lib/supabase";

type SupportMessage={id:string;conversation_id:string;sender_id:string;sender_role:"user"|"admin"|"staff";message:string;is_read:boolean;created_at:string};
type UserOrder={id:string;tracking_code:string|null;status:string;created_at:string};
type Faq={id:string;category:string;question:string;answer:string;score:number};
type Conversation={id:string;status:"open"|"closed";order_id:string|null;assignment_mode:string|null;assigned_staff_id:string|null};
type AiMessage={role:"user"|"assistant";text:string};
const FAQ_CATEGORIES=["سفارش","پرداخت","حساب کاربری","خدمات","پشتیبانی"];

export default function SupportChatWidget(){
 const [open,setOpen]=useState(false),[userId,setUserId]=useState<string|null>(null),[conversationId,setConversationId]=useState<string|null>(null),[conversation,setConversation]=useState<Conversation|null>(null),[selectedOrderId,setSelectedOrderId]=useState(""),[orders,setOrders]=useState<UserOrder[]>([]),[messages,setMessages]=useState<SupportMessage[]>([]),[draft,setDraft]=useState(""),[loading,setLoading]=useState(false),[sending,setSending]=useState(false),[closing,setClosing]=useState(false),[rating,setRating]=useState(0),[reviewComment,setReviewComment]=useState(""),[reviewSent,setReviewSent]=useState(false),[error,setError]=useState<string|null>(null),[aiMode,setAiMode]=useState(true),[aiMessages,setAiMessages]=useState<AiMessage[]>([]),[aiLoading,setAiLoading]=useState(false),[faqQuery,setFaqQuery]=useState(""),[faqCategory,setFaqCategory]=useState<string|null>(null),[faqs,setFaqs]=useState<Faq[]>([]),[faqLoading,setFaqLoading]=useState(false),[showFaq,setShowFaq]=useState(false),[sessionKey,setSessionKey]=useState(0);
 const scrollRef=useRef<HTMLDivElement>(null);

 useEffect(()=>{let mounted=true;supabase.auth.getUser().then(({data})=>{if(mounted)setUserId(data.user?.id||null)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{if(mounted){setUserId(s?.user?.id||null);setConversationId(null);setConversation(null);setAiMessages([])}});return()=>{mounted=false;subscription.unsubscribe()}},[]);
 useEffect(()=>{if(open&&userId)void loadOrders(userId)},[open,userId]);
 useEffect(()=>{if(!open||!userId)return;void loadConversation(userId,selectedOrderId||null)},[open,userId,selectedOrderId,sessionKey]);
 useEffect(()=>{if(!open||!userId)return;void searchFaqs(faqQuery,faqCategory)},[open,userId,faqCategory]);
 useEffect(()=>{if(!conversationId)return;const cid=conversationId;const ch=supabase.channel(`support-chat-${cid}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"support_messages",filter:`conversation_id=eq.${cid}`},p=>{const n=p.new as SupportMessage;setMessages(c=>c.some(x=>x.id===n.id)?c:[...c,n]);if(n.sender_id!==userId&&open)void markRead(cid)}).on("postgres_changes",{event:"UPDATE",schema:"public",table:"support_conversations",filter:`id=eq.${cid}`},p=>{const n=p.new as Conversation;setConversation(n);if(n.status==="closed"){setConversationId(null);setMessages([]);setAiMode(true);setAiMessages([]);setReviewSent(false);setRating(0);setReviewComment("");setSessionKey(k=>k+1)}}).subscribe();return()=>{void supabase.removeChannel(ch)}},[conversationId,userId,open]);
 useEffect(()=>{scrollRef.current?.scrollTo({top:scrollRef.current.scrollHeight,behavior:"smooth"})},[messages,aiMessages,open,showFaq]);
 async function loadOrders(id:string){const {data,error:e}=await supabase.from("orders").select("id,tracking_code,status,created_at").eq("user_id",id).order("created_at",{ascending:false}).limit(50);if(!e)setOrders((data||[]) as UserOrder[]);else setError(e.message)}
 async function markRead(id:string){const {error:e}=await supabase.rpc("mark_support_messages_read",{p_conversation_id:id});if(e)console.warn(e.message)}
 async function loadConversation(id:string,orderId:string|null){
  setLoading(true);setError(null);setConversationId(null);setConversation(null);setMessages([]);setReviewSent(false);setRating(0);setReviewComment("");
  let q=supabase.from("support_conversations").select("id,status,order_id,assignment_mode,assigned_staff_id").eq("user_id",id).eq("status","open");
  q=orderId?q.eq("order_id",orderId):q.is("order_id",null);
  const {data:existing,error:e}=await q.order("updated_at",{ascending:false}).limit(1).maybeSingle();
  if(e){setError(e.message);setLoading(false);return}
  if(existing?.id){setAiMode(false);await hydrate(existing as Conversation);return}
  setAiMode(true);setLoading(false);
 }
 async function hydrate(c:Conversation){setConversation(c);setConversationId(c.id);setAiMode(false);const {data,error:e}=await supabase.from("support_messages").select("id,conversation_id,sender_id,sender_role,message,is_read,created_at").eq("conversation_id",c.id).order("created_at",{ascending:true}).limit(100);if(e)setError(e.message);else setMessages((data||[]) as SupportMessage[]);await markRead(c.id);setLoading(false)}
 async function searchFaqs(query:string,category:string|null){if(!userId)return;setFaqLoading(true);const {data,error:e}=await supabase.rpc("search_support_faqs",{p_query:query.trim()||null,p_category:category});if(!e)setFaqs((data||[]) as Faq[]);else setError(e.message);setFaqLoading(false)}
 async function sendAiMessage(e:React.FormEvent){e.preventDefault();const text=draft.trim();if(!text||aiLoading||!userId)return;setDraft("");setError(null);const next=[...aiMessages,{role:"user" as const,text}];setAiMessages(next);setAiLoading(true);try{const response=await fetch("/api/support/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,orderId:selectedOrderId||null,history:next})});const data=await response.json();if(!response.ok)throw new Error(data.error||"پاسخ هوش مصنوعی دریافت نشد.");setAiMessages(current=>[...current,{role:"assistant",text:data.reply||"پاسخی دریافت نشد."}]);}catch(e){setError(e instanceof Error?e.message:"پاسخ هوش مصنوعی دریافت نشد.");}finally{setAiLoading(false)}}
 async function startHumanSupport(){
  if(!userId||loading)return;setLoading(true);setError(null);
  const {data:newId,error:e}=await supabase.rpc("start_support_conversation",{p_order_id:selectedOrderId||null});
  if(e||!newId){setError(e?.message||"ایجاد گفتگوی پشتیبانی انجام نشد.");setLoading(false);return}
  const {data:c,error:ce}=await supabase.from("support_conversations").select("id,status,order_id,assignment_mode,assigned_staff_id").eq("id",newId).maybeSingle();
  if(ce||!c){setError(ce?.message||"اطلاعات مسیر پشتیبانی دریافت نشد.");setLoading(false);return}
  await hydrate(c as Conversation);
  if(aiMessages.length){const transcript=aiMessages.map(m=>`${m.role==="user"?"کاربر":"دستیار هوشمند"}: ${m.text}`).join("\n\n");const handoff=`گزارش خودکار پیش از اتصال به پشتیبانی انسانی:\n\n${transcript}`.slice(0,3900);const {error:he}=await supabase.rpc("send_support_message",{p_conversation_id:newId,p_message:handoff});if(he)setError("گفتگو ایجاد شد اما خلاصه گفتگوی هوشمند ارسال نشد.");else{const {data:m}=await supabase.from("support_messages").select("id,conversation_id,sender_id,sender_role,message,is_read,created_at").eq("conversation_id",newId).order("created_at",{ascending:false}).limit(1).maybeSingle();if(m)setMessages(c=>c.some(x=>x.id===m.id)?c:[...c,m as SupportMessage])}}
  setAiMessages([]);setShowFaq(false);
 }
 async function sendHumanMessage(e:React.FormEvent){e.preventDefault();const text=draft.trim();if(!text||!conversationId||sending||conversation?.status!=="open")return;setSending(true);setError(null);const {data:id,error:se}=await supabase.rpc("send_support_message",{p_conversation_id:conversationId,p_message:text});if(se||!id){setError(se?.message||"ارسال پیام انجام نشد.");setSending(false);return}const {data:m}=await supabase.from("support_messages").select("id,conversation_id,sender_id,sender_role,message,is_read,created_at").eq("id",id).maybeSingle();if(m){setDraft("");setMessages(c=>c.some(x=>x.id===m.id)?c:[...c,m as SupportMessage])}setSending(false)}
 async function closeConversation(){if(!conversationId||closing)return;setClosing(true);setError(null);const {error:e}=await supabase.rpc("close_support_conversation",{p_conversation_id:conversationId});if(e)setError(e.message);else{setConversation(null);setConversationId(null);setMessages([]);setAiMode(true);setAiMessages([]);setReviewSent(false);setRating(0);setReviewComment("");setSessionKey(k=>k+1)}setClosing(false)}
 async function submitReview(){if(!conversationId||rating<1||reviewSent)return;const {error:e}=await supabase.rpc("submit_support_review",{p_conversation_id:conversationId,p_rating:rating,p_comment:reviewComment||null,p_strengths:[],p_weaknesses:[]});if(e)setError(e.message);else{setReviewSent(true);setConversationId(null);setConversation(null);setMessages([]);setRating(0);setReviewComment("");setAiMode(true);setAiMessages([]);setSessionKey(k=>k+1)}}
 function routingBanner(){if(!conversation)return null;if(conversation.order_id&&conversation.assigned_staff_id)return <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 px-3 py-2 text-xs leading-6">این گفتگو مستقیماً برای <b>مدیر سفارش</b> اختصاص داده شده است و پیام شما به مدیر مربوط می‌رسد.</div>;if(conversation.order_id)return <div className="rounded-xl border border-amber-500/20 bg-amber-500/10 px-3 py-2 text-xs leading-6">برای این سفارش هنوز مدیر سفارش تعیین/تأیید نشده است؛ بنابراین به <b>اپراتور پشتیبانی</b> متصل شدید تا شما را راهنمایی کند.</div>;return <div className="rounded-xl border border-sky-500/20 bg-sky-500/10 px-3 py-2 text-xs leading-6">این گفتگو در صف <b>پشتیبانی</b> قرار دارد و توسط اپراتور پاسخ داده می‌شود.</div>}
 return <div className="fixed bottom-5 left-5 z-[60]" dir="rtl">{open&&<div className="mb-3 flex h-[min(720px,calc(100vh-110px))] w-[min(410px,calc(100vw-2rem))] flex-col overflow-hidden rounded-3xl border border-[var(--border)] bg-[var(--surface-strong)] shadow-2xl">
  <div className="flex items-center justify-between bg-[var(--primary)] px-5 py-4 text-white"><div><div className="flex items-center gap-2 font-black">{aiMode?<Bot size={19}/>:<MessageCircle size={19}/>}پشتیبانی آنلاین توسن</div><div className="mt-1 text-xs text-white/75">{aiMode?"دستیار هوشمند توسن در خدمت شماست":"پشتیبانی انسانی و پیگیری گفتگو"}</div></div><button type="button" onClick={()=>setOpen(false)} className="rounded-xl p-2"><X size={19}/></button></div>
  {!userId?<div className="flex flex-1 flex-col items-center justify-center px-7 text-center"><MessageCircle size={42}/><h3 className="mt-4 font-black">برای شروع گفتگو وارد شوید</h3><Link href="/auth?mode=login" className="mt-5 rounded-2xl bg-[var(--primary)] px-6 py-3 font-black text-white">ورود به حساب</Link></div>:<>
   {!conversationId&&orders.length>0&&<div className="border-b border-[var(--border)] p-3"><label className="mb-1 block text-xs font-bold">سؤال یا سفارش مرتبط</label><select value={selectedOrderId} onChange={e=>{setSelectedOrderId(e.target.value);setFaqCategory(null);setFaqQuery("");setAiMessages([])}} className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2.5 text-sm"><option value="">گفتگوی عمومی</option>{orders.map(o=><option key={o.id} value={o.id}>{o.tracking_code||o.id.slice(0,8)} — {new Date(o.created_at).toLocaleDateString("fa-IR")}</option>)}</select></div>}
   {error&&<div role="alert" className="mx-3 mt-3 rounded-xl border border-red-500/20 bg-red-500/10 px-3 py-2 text-xs">{error}</div>}
   {aiMode&&!conversationId?<div className="flex flex-1 flex-col overflow-hidden">
    <div ref={scrollRef} className="flex-1 space-y-3 overflow-y-auto p-4">
      {aiMessages.length===0&&!showFaq&&<div className="py-8 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[var(--primary)]/10 text-[var(--primary)]"><Bot size={28}/></div><h3 className="mt-4 font-black">سلام 👋 من دستیار هوشمند توسن هستم</h3><p className="mt-2 text-sm leading-7 text-[var(--text-muted)]">در مورد خدمات، سفارش، پرداخت و روند کارها سؤال کنید. اگر نیاز به بررسی انسانی باشد، شما را مستقیماً به اپراتور وصل می‌کنم.</p></div>}
      {aiMessages.map((m,i)=><div key={`${m.role}-${i}`} className={`flex ${m.role==="user"?"justify-start":"justify-end"}`}><div className={`max-w-[88%] whitespace-pre-wrap rounded-2xl px-4 py-3 text-sm leading-7 ${m.role==="user"?"bg-[var(--primary)] text-white":"bg-[var(--surface-muted)]"}`}>{m.text}</div></div>)}
      {aiLoading&&<div className="flex justify-end"><div className="rounded-2xl bg-[var(--surface-muted)] px-4 py-3 text-sm">در حال بررسی و پاسخ‌گویی…</div></div>}
      {showFaq&&<div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-3"><div className="mb-2 flex items-center gap-2 text-sm font-black"><LifeBuoy size={16}/>پاسخ‌های ثبت‌شده توسن</div><div className="flex items-center gap-2 rounded-xl border border-[var(--border)] px-3 py-2"><Search size={16}/><input value={faqQuery} onChange={e=>{setFaqQuery(e.target.value);void searchFaqs(e.target.value,faqCategory)}} placeholder="مثلاً پیگیری سفارش یا پرداخت" className="w-full bg-transparent text-sm outline-none"/></div><div className="mt-2 flex gap-2 overflow-x-auto pb-1">{FAQ_CATEGORIES.map(c=><button key={c} type="button" onClick={()=>{const next=faqCategory===c?null:c;setFaqCategory(next);void searchFaqs(faqQuery,next)}} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-bold ${faqCategory===c?"bg-[var(--primary)] text-white":"bg-[var(--surface-muted)]"}`}>{c}</button>)}</div><div className="mt-3">{faqLoading?<div className="py-4 text-center text-xs">در حال جستجو...</div>:faqs.length===0?<div className="py-3 text-center text-xs text-[var(--text-muted)]">پاسخی پیدا نشد.</div>:<div className="space-y-2">{faqs.slice(0,5).map(f=><details key={f.id} className="rounded-xl border border-[var(--border)]"><summary className="cursor-pointer px-3 py-2 text-xs font-bold">{f.question}</summary><div className="border-t border-[var(--border)] px-3 py-2 text-xs leading-6 text-[var(--text-muted)]">{f.answer}</div></details>)}</div>}</div></div>}
    </div>
    <div className="border-t border-[var(--border)] p-3"><div className="mb-2 flex gap-2"><button type="button" onClick={()=>setShowFaq(v=>!v)} className="flex-1 rounded-xl border border-[var(--border)] px-3 py-2 text-xs font-bold">{showFaq?"بستن پاسخ‌های متداول":"جستجوی پاسخ‌های متداول"}</button><button type="button" onClick={()=>void startHumanSupport()} disabled={loading||aiLoading} className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-[var(--primary)] px-3 py-2 text-xs font-bold text-[var(--primary)] disabled:opacity-40"><UserRound size={15}/>{loading?"در حال اتصال...":"ارتباط با پشتیبانی انسانی"}</button></div><form onSubmit={sendAiMessage}><div className="flex items-end gap-2 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-2"><textarea value={draft} onChange={e=>setDraft(e.target.value)} rows={2} maxLength={4000} placeholder="سؤال خود را بنویسید..." className="min-h-10 flex-1 resize-none bg-transparent px-2 py-2 text-sm outline-none"/><button type="submit" disabled={!draft.trim()||aiLoading} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[var(--primary)] text-white disabled:opacity-40"><Send size={17}/></button></div></form></div>
   </div>:<>
    <div className="border-b border-[var(--border)] p-3">{routingBanner()}</div>
    <div ref={scrollRef} className="flex-1 space-y-3 overflow-y-auto p-4">{loading?<div className="py-10 text-center text-sm">در حال بارگذاری گفتگو...</div>:messages.length===0?<div className="py-10 text-center text-sm">سلام 👋<br/>پیام خود را بنویسید.</div>:messages.map(m=><div key={m.id} className={`flex ${m.sender_role==="user"?"justify-start":"justify-end"}`}><div className={`max-w-[82%] whitespace-pre-wrap rounded-2xl px-4 py-3 text-sm leading-7 ${m.sender_role==="user"?"bg-[var(--primary)] text-white":"bg-[var(--surface-muted)]"}`}>{m.message}<div className="mt-1 text-[10px] opacity-60">{new Date(m.created_at).toLocaleTimeString("fa-IR",{hour:"2-digit",minute:"2-digit"})}</div></div></div>)}</div>
    <div className="border-t border-[var(--border)] p-3"><button type="button" onClick={()=>void closeConversation()} disabled={closing||loading||!conversationId} className="mb-3 flex w-full items-center justify-center gap-2 rounded-xl border border-[var(--border)] px-3 py-2 text-xs font-bold disabled:opacity-40"><CheckCircle size={16}/>{closing?"در حال اتمام گفتگو...":"اتمام گفتگو"}</button><form onSubmit={sendHumanMessage}><div className="flex items-end gap-2 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-2"><textarea value={draft} onChange={e=>setDraft(e.target.value)} rows={2} maxLength={4000} placeholder="پیام شما..." className="min-h-10 flex-1 resize-none bg-transparent px-2 py-2 text-sm outline-none"/><button type="submit" disabled={!draft.trim()||sending||!conversationId} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[var(--primary)] text-white disabled:opacity-40"><Send size={17}/></button></div></form></div>
   </>}
  </>}</div>}
  <button type="button" onClick={()=>setOpen(v=>!v)} className="relative flex items-center gap-2 rounded-full bg-[var(--primary)] px-5 py-3.5 font-black text-white shadow-lg"><MessageCircle size={20}/><span className="hidden sm:inline">پشتیبانی آنلاین</span></button>
 </div>;
}
