"use client";
import type { ConditionOperator, FormField } from "@/types/forms";
import type { PricingRule, PricingRuleMode } from "@/lib/forms/pricing";
type Props = { fields: FormField[]; value: PricingRule[]; onChange: (rules: PricingRule[]) => void };
const operators: { value: ConditionOperator; label: string }[] = [
  { value: "equals", label: "برابر باشد با" }, { value: "not_equals", label: "برابر نباشد با" }, { value: "contains", label: "شامل باشد" }, { value: "not_contains", label: "شامل نباشد" },
  { value: "gt", label: "بیشتر از" }, { value: "gte", label: "بیشتر یا مساوی" }, { value: "lt", label: "کمتر از" }, { value: "lte", label: "کمتر یا مساوی" },
  { value: "is_true", label: "بله / فعال باشد" }, { value: "is_false", label: "خیر / غیرفعال باشد" },
  { value: "empty", label: "خالی باشد" }, { value: "not_empty", label: "خالی نباشد" },
];
const id = () => `price_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
const fieldLabel = (fields: FormField[], name?: string) => fields.find((field) => field.name === name)?.label || name || "فیلد";
export default function ServicePricingRules({ fields, value, onChange }: Props) {
  const rules = value || [];
  const add = () => onChange([...rules, { id: id(), field: fields[0]?.name || "", operator: "equals", value: fields[0]?.options?.[0]?.value || "", mode: "set", amount: 0, enabled: true }]);
  const update = (index: number, changes: Partial<PricingRule>) => onChange(rules.map((rule, i) => i === index ? { ...rule, ...changes } : rule));
  const remove = (index: number) => onChange(rules.filter((_, i) => i !== index));
  return <div dir="rtl" className="space-y-4"><div className="flex items-center justify-between gap-3"><div><h3 className="font-bold">قیمت‌گذاری شرطی</h3><p className="text-sm text-[var(--muted)] mt-1">قیمت نهایی بر اساس پاسخ فیلدها به‌صورت خودکار محاسبه می‌شود.</p></div><button type="button" onClick={add} disabled={!fields.length} className="rounded-xl bg-[#09967C] text-white px-4 py-2 font-bold disabled:opacity-50">+ قانون قیمت</button></div>{!rules.length && <div className="rounded-xl border border-dashed p-5 text-sm text-[var(--muted)]">قانون شرطی ثبت نشده است؛ قیمت پایه خدمت استفاده می‌شود.</div>}{rules.map((rule, index) => { const selectedField = fields.find((field) => field.name === rule.field); const options = selectedField?.options || []; const numericOperator = ["gt", "gte", "lt", "lte"].includes(rule.operator || ""); const noValueOperator = ["is_true", "is_false", "empty", "not_empty"].includes(rule.operator || ""); return <div key={rule.id || index} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4 space-y-3"><div className="grid md:grid-cols-2 gap-3"><div><label className="block text-xs font-bold mb-1">فیلد</label><select value={rule.field || ""} onChange={(e) => update(index, { field: e.target.value, value: fields.find((field) => field.name === e.target.value)?.options?.[0]?.value || "" })} className="w-full rounded-xl border px-3 py-2 bg-white">{fields.map((field) => <option key={field.id} value={field.name}>{field.label}</option>)}</select></div><div><label className="block text-xs font-bold mb-1">شرط</label><select value={rule.operator || "equals"} onChange={(e) => update(index, { operator: e.target.value as ConditionOperator })} className="w-full rounded-xl border px-3 py-2 bg-white">{operators.map((operator) => <option key={operator.value} value={operator.value}>{operator.label}</option>)}</select></div></div>{!noValueOperator && <div><label className="block text-xs font-bold mb-1">مقدار شرط</label>{options.length && !numericOperator ? <select value={String(rule.value ?? "")} onChange={(e) => update(index, { value: e.target.value })} className="w-full rounded-xl border px-3 py-2 bg-white">{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input type={numericOperator ? "number" : "text"} value={String(rule.value ?? "")} onChange={(e) => update(index, { value: e.target.value })} className="w-full rounded-xl border px-3 py-2 bg-white" placeholder="مقدار شرط" /></div>}
      <div className="grid md:grid-cols-3 gap-3"><div><label className="block text-xs font-bold mb-1">نوع تغییر قیمت</label><select value={rule.mode || "set"} onChange={(e) => update(index, { mode: e.target.value as PricingRuleMode })} className="w-full rounded-xl border px-3 py-2 bg-white"><option value="set">تعیین قیمت</option><option value="add">افزایش قیمت</option><option value="per_item">افزایش به ازای هر مورد اضافه</option></select></div><div><label className="block text-xs font-bold mb-1">مبلغ (تومان)</label><input type="number" min="0" value={rule.amount ?? 0} onChange={(e) => update(index, { amount: Number(e.target.value) })} className="w-full rounded-xl border px-3 py-2 bg-white" /></div>{rule.mode === "per_item" && <div><label className="block text-xs font-bold mb-1">تعداد پایه</label><input type="number" min="0" value={rule.includedItems ?? 0} onChange={(e) => update(index, { includedItems: Number(e.target.value) })} className="w-full rounded-xl border px-3 py-2 bg-white" /></div>}</div><div className="grid md:grid-cols-[1fr_auto] gap-3"><input value={rule.label || ""} onChange={(e) => update(index, { label: e.target.value })} className="w-full rounded-xl border px-3 py-2 bg-white" placeholder={`مثلاً ${fieldLabel(fields, rule.field)} — نرخ ویژه`} /><button type="button" onClick={() => remove(index)} className="rounded-xl border border-red-200 px-4 py-2 text-red-600">حذف</button></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={rule.enabled !== false} onChange={(e) => update(index, { enabled: e.target.checked })} className="accent-[#09967C]" />قانون فعال باشد</label></div>; })}</div>;
}
