"use client";

import { useEffect, useMemo, useState } from "react";
import type { ConditionOperator, FieldCondition, FieldValidationRules, FormField, FormOption, FieldType } from "@/types/forms";

type Props = { value: FormField[]; onChange: (fields: FormField[]) => void };

const fieldTypes: { value: FieldType; label: string }[] = [
  { value: "text", label: "متن کوتاه" }, { value: "textarea", label: "متن بلند" }, { value: "number", label: "عدد" },
  { value: "phone", label: "شماره موبایل" }, { value: "national_code", label: "کد ملی" }, { value: "email", label: "ایمیل" },
  { value: "password", label: "رمز عبور" }, { value: "date", label: "تاریخ" }, { value: "select", label: "انتخابی" },
  { value: "multiselect", label: "چندانتخابی" }, { value: "boolean", label: "بله / خیر" }, { value: "checkbox", label: "تیک تأیید" },
];
const operators: { value: ConditionOperator; label: string }[] = [
  { value: "equals", label: "برابر باشد با" }, { value: "not_equals", label: "برابر نباشد با" }, { value: "contains", label: "شامل باشد" },
  { value: "not_contains", label: "شامل نباشد" }, { value: "is_true", label: "فعال / بله باشد" }, { value: "is_false", label: "غیرفعال / خیر باشد" },
];
const id = () => `${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
const cleanName = (v: string) => v.trim().replace(/\s+/g, "_").replace(/[^a-zA-Z0-9_\u0600-\u06FF]/g, "_");
function uniqueName(raw: string, fields: FormField[], currentId: string) { const base = cleanName(raw) || `field_${Date.now()}`; if (!fields.some(f => f.id !== currentId && f.name === base)) return base; let i = 2; while (fields.some(f => f.id !== currentId && f.name === `${base}_${i}`)) i++; return `${base}_${i}`; }
function uniqueOptionValue(raw: string, options: FormOption[], index: number) { const base = cleanName(raw) || `option_${index + 1}`; if (!options.some((o, i) => i !== index && o.value === base)) return base; let i = 2; while (options.some((o, n) => n !== index && o.value === `${base}_${i}`)) i++; return `${base}_${i}`; }
const defaultOptions = (): FormOption[] => [{ label: "گزینه اول", value: "option_1" }];
const newField = (): FormField => ({ id: id(), type: "text", label: "فیلد جدید", name: `field_${Date.now()}`, required: false });

export default function ServiceFormBuilderV2({ value, onChange }: Props) {
  const [fields, setFields] = useState<FormField[]>(value || []);
  const [openFields, setOpenFields] = useState<Set<string>>(new Set());
  const [error, setError] = useState("");
  useEffect(() => setFields(value || []), [value]);

  function commit(next: FormField[]) {
    const names = new Set<string>();
    for (const field of next) {
      if (!field.name.trim()) return setError(`نام فنی فیلد «${field.label || "بدون عنوان"}» الزامی است.`);
      if (names.has(field.name)) return setError(`نام فنی «${field.name}» تکراری است.`);
      names.add(field.name);
      if ((field.type === "select" || field.type === "multiselect") && field.options) {
        const values = new Set<string>();
        for (const option of field.options) { if (!option.value.trim()) return setError(`مقدار فنی گزینه‌های «${field.label}» خالی است.`); if (values.has(option.value)) return setError(`مقدار فنی گزینه‌های «${field.label}» تکراری است.`); values.add(option.value); }
      }
    }
    setError(""); setFields(next); onChange(next);
  }
  const update = (fieldId: string, changes: Partial<FormField>) => commit(fields.map(f => f.id === fieldId ? { ...f, ...changes } : f));
  const toggle = (fieldId: string) => setOpenFields(s => { const n = new Set(s); n.has(fieldId) ? n.delete(fieldId) : n.add(fieldId); return n; });
  const remove = (fieldId: string) => { if (!confirm("آیا از حذف این فیلد مطمئن هستید؟")) return; const removed = fields.find(f => f.id === fieldId); commit(fields.filter(f => f.id !== fieldId).map(f => ({ ...f, conditions: f.conditions?.filter(c => c.field !== removed?.name) }))); };
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= fields.length) return; const next = [...fields]; [next[index], next[target]] = [next[target], next[index]]; commit(next); };
  const addField = () => { const f = newField(); commit([...fields, f]); setOpenFields(s => new Set(s).add(f.id)); };
  const addOption = (fieldId: string) => { const f = fields.find(x => x.id === fieldId); if (!f) return; const options = [...(f.options || []), { label: `گزینه ${(f.options?.length || 0) + 1}`, value: uniqueOptionValue(`option_${(f.options?.length || 0) + 1}`, f.options || [], f.options?.length || 0) }]; update(fieldId, { options }); };
  const updateOption = (fieldId: string, index: number, changes: Partial<FormOption>) => { const f = fields.find(x => x.id === fieldId); if (!f) return; const options = [...(f.options || [])]; options[index] = { ...options[index], ...changes }; update(fieldId, { options }); };
  const removeOption = (fieldId: string, index: number) => { const f = fields.find(x => x.id === fieldId); if (!f) return; const options = [...(f.options || [])]; options.splice(index, 1); update(fieldId, { options }); };
  const addCondition = (fieldId: string) => { const index = fields.findIndex(f => f.id === fieldId); if (index <= 0) return; const parent = fields[index - 1]; const boolean = parent.type === "boolean" || parent.type === "checkbox"; const c: FieldCondition = { field: parent.name, fieldId: parent.id, operator: boolean ? "is_true" : "equals", value: boolean ? true : parent.options?.[0]?.value || "" }; update(fieldId, { conditions: [...(fields[index].conditions || []), c] }); };
  const updateCondition = (fieldId: string, index: number, changes: Partial<FieldCondition>) => { const f = fields.find(x => x.id === fieldId); if (!f) return; const conditions = [...(f.conditions || [])]; conditions[index] = { ...conditions[index], ...changes }; update(fieldId, { conditions }); };
  const removeCondition = (fieldId: string, index: number) => { const f = fields.find(x => x.id === fieldId); if (!f) return; const conditions = [...(f.conditions || [])]; conditions.splice(index, 1); update(fieldId, { conditions: conditions.length ? conditions : undefined }); };
  const updateRule = (fieldId: string, changes: Partial<FieldValidationRules>) => { const f = fields.find(x => x.id === fieldId); if (!f) return; const validation = { ...(f.validation || {}), ...changes }; for (const key of Object.keys(validation) as (keyof FieldValidationRules)[]) if (validation[key] === undefined || validation[key] === null || validation[key] === "") delete validation[key]; update(fieldId, { validation: Object.keys(validation).length ? validation : undefined }); };
  const names = useMemo(() => new Set(fields.map(f => f.name)), [fields]);

  return <div dir="rtl" className="space-y-4">
    <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><h3 className="text-lg font-bold">فرم اطلاعات مشتری</h3><p className="text-sm text-gray-500 mt-1">فیلدها، شرط نمایش و قوانین اعتبارسنجی را مدیریت کنید.</p></div><button type="button" onClick={addField} className="bg-[#09967C] text-white px-4 py-2 rounded-xl">+ افزودن فیلد</button></div>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    {!fields.length && <div className="border border-dashed rounded-xl p-8 text-center text-gray-500">هنوز فیلدی ایجاد نشده است.</div>}
    {fields.map((field, index) => {
      const parents = fields.slice(0, index).filter(f => f.name && f.id !== field.id); const open = openFields.has(field.id); const rules = field.validation || {};
      return <div key={field.id} className={`border rounded-2xl overflow-hidden ${open ? "border-[#09967C]/30 bg-gray-50" : "border-gray-200 bg-white"}`}>
        <div className="flex flex-wrap items-center gap-2 p-4"><button type="button" onClick={() => toggle(field.id)} className="flex-1 min-w-[220px] text-right"><div className="flex items-center gap-3"><span className="bg-gray-100 border rounded-lg px-3 py-1 text-sm">فیلد {index + 1}</span><strong>{field.label || "بدون عنوان"}</strong><span className="text-xs text-gray-500">{fieldTypes.find(t => t.value === field.type)?.label || field.type}</span>{field.required && <span className="text-xs text-[#09967C]">اجباری</span>}{Object.keys(rules).length > 0 && <span className="text-xs text-blue-600">قانون اعتبارسنجی</span>}</div></button><button type="button" disabled={!index} onClick={() => move(index, -1)} className="bg-white border rounded-lg px-3 py-1 disabled:opacity-30">↑</button><button type="button" disabled={index === fields.length - 1} onClick={() => move(index, 1)} className="bg-white border rounded-lg px-3 py-1 disabled:opacity-30">↓</button><button type="button" onClick={() => toggle(field.id)} className="rounded-lg border border-[#09967C]/30 px-3 py-1 text-sm text-[#09967C]">{open ? "بستن" : "ویرایش"}</button><button type="button" onClick={() => remove(field.id)} className="rounded-lg px-3 py-1 text-sm text-red-600">حذف</button></div>
        {open && <div className="border-t p-5 space-y-5 bg-gray-50">
          <div className="grid md:grid-cols-2 gap-4"><div><label className="block text-sm font-bold mb-2">نوع فیلد</label><select value={field.type} onChange={e => { const type = e.target.value as FieldType; update(field.id, { type, options: type === "select" || type === "multiselect" ? (field.options?.length ? field.options : defaultOptions()) : undefined }); }} className="w-full border rounded-xl px-4 py-3 bg-white">{fieldTypes.map(t => <option key={t.value} value={t.value}>{t.label}</option>)}</select></div><div><label className="block text-sm font-bold mb-2">عنوان فیلد</label><input value={field.label} onChange={e => update(field.id, { label: e.target.value })} className="w-full border rounded-xl px-4 py-3 bg-white" /></div><div><label className="block text-sm font-bold mb-2">نام فنی</label><input value={field.name} onChange={e => update(field.id, { name: uniqueName(e.target.value, fields, field.id) })} className="w-full border rounded-xl px-4 py-3 bg-white" dir="ltr" /><p className="text-xs text-gray-500 mt-1">{names.has(field.name) ? "نام فنی باید یکتا باشد." : ""}</p></div>{!['boolean','checkbox'].includes(field.type) && <div><label className="block text-sm font-bold mb-2">Placeholder</label><input value={field.placeholder || ""} onChange={e => update(field.id, { placeholder: e.target.value })} className="w-full border rounded-xl px-4 py-3 bg-white" /></div>}</div>
          <div><label className="block text-sm font-bold mb-2">توضیحات</label><input value={field.description || ""} onChange={e => update(field.id, { description: e.target.value })} className="w-full border rounded-xl px-4 py-3 bg-white" /></div>
          <label className="flex items-center gap-2"><input type="checkbox" checked={field.required} onChange={e => update(field.id, { required: e.target.checked })} className="accent-[#09967C]" /><span className="text-sm">این فیلد اجباری است</span></label>
          {(field.type === "select" || field.type === "multiselect") && <div className="border-t pt-4"><div className="flex justify-between items-center mb-3"><h4 className="font-bold">گزینه‌ها</h4><button type="button" onClick={() => addOption(field.id)} className="text-[#09967C] text-sm font-bold">+ افزودن گزینه</button></div>{(field.options || []).map((o, oi) => <div key={`${field.id}-${oi}`} className="flex flex-col md:flex-row gap-2 mb-2"><input value={o.label} onChange={e => updateOption(field.id, oi, { label: e.target.value })} className="flex-1 border rounded-lg px-3 py-2 bg-white" placeholder="عنوان گزینه" /><input value={o.value} onChange={e => updateOption(field.id, oi, { value: uniqueOptionValue(e.target.value, field.options || [], oi) })} className="flex-1 border rounded-lg px-3 py-2 bg-white" dir="ltr" placeholder="مقدار فنی" /><button type="button" onClick={() => removeOption(field.id, oi)} className="text-red-500 px-2">حذف</button></div>)}</div>}
          <div className="border-t pt-4"><div className="flex items-center justify-between mb-3"><div><h4 className="font-bold text-blue-700">قوانین اعتبارسنجی</h4><p className="text-xs text-gray-500">این قوانین هم در فرم و هم در ثبت نهایی سفارش قابل اعمال هستند.</p></div></div><div className="grid md:grid-cols-2 gap-3"><div><label className="block text-xs font-bold mb-1">حداقل طول</label><input type="number" min="0" value={rules.minLength ?? ""} onChange={e => updateRule(field.id, { minLength: e.target.value === "" ? undefined : Number(e.target.value) })} className="w-full border rounded-lg px-3 py-2 bg-white" /></div><div><label className="block text-xs font-bold mb-1">حداکثر طول</label><input type="number" min="0" value={rules.maxLength ?? ""} onChange={e => updateRule(field.id, { maxLength: e.target.value === "" ? undefined : Number(e.target.value) })} className="w-full border rounded-lg px-3 py-2 bg-white" /></div><div><label className="block text-xs font-bold mb-1">حداقل مقدار عددی</label><input type="number" value={rules.min ?? ""} onChange={e => updateRule(field.id, { min: e.target.value === "" ? undefined : Number(e.target.value) })} className="w-full border rounded-lg px-3 py-2 bg-white" /></div><div><label className="block text-xs font-bold mb-1">حداکثر مقدار عددی</label><input type="number" value={rules.max ?? ""} onChange={e => updateRule(field.id, { max: e.target.value === "" ? undefined : Number(e.target.value) })} className="w-full border rounded-lg px-3 py-2 bg-white" /></div></div><div className="mt-3"><label className="block text-xs font-bold mb-1">Pattern / Regex اختیاری</label><input value={rules.pattern ?? ""} onChange={e => updateRule(field.id, { pattern: e.target.value || undefined })} className="w-full border rounded-lg px-3 py-2 bg-white" dir="ltr" placeholder="مثلاً ^[0-9]{10}$" /><p className="text-xs text-gray-500 mt-1">برای الگوهای خاص مثل کد ملی، VIN یا شناسه سفارشی استفاده کنید.</p></div></div>
          {parents.length > 0 && <div className="border-t pt-4"><div className="flex items-center justify-between mb-3"><div><h4 className="font-bold text-[#09967C]">نمایش شرطی</h4><p className="text-xs text-gray-500">شرط‌های قبلی فرم می‌توانند نمایش این فیلد را کنترل کنند.</p></div><button type="button" onClick={() => addCondition(field.id)} className="text-[#09967C] text-sm font-bold border border-[#09967C]/30 rounded-lg px-3 py-2">+ افزودن شرط</button></div>{(field.conditions || []).map((c, ci) => <div key={`${field.id}-condition-${ci}`} className="grid md:grid-cols-[1fr_1fr_1fr_auto] gap-2 mb-2 items-center"><select value={c.fieldId || c.field} onChange={e => { const p = fields.find(x => x.id === e.target.value); updateCondition(field.id, ci, { fieldId: p?.id, field: p?.name || e.target.value, operator: p?.type === "boolean" || p?.type === "checkbox" ? "is_true" : "equals", value: p?.type === "boolean" || p?.type === "checkbox" ? true : p?.options?.[0]?.value || "" }); }} className="border rounded-lg px-3 py-2 bg-white">{parents.map(p => <option key={p.id} value={p.id}>{p.label}</option>)}</select><select value={c.operator} onChange={e => updateCondition(field.id, ci, { operator: e.target.value as ConditionOperator })} className="border rounded-lg px-3 py-2 bg-white">{operators.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select><input value={typeof c.value === "boolean" ? (c.value ? "true" : "false") : String(c.value ?? "")} onChange={e => updateCondition(field.id, ci, { value: e.target.value })} className="border rounded-lg px-3 py-2 bg-white" dir="ltr" /><button type="button" onClick={() => removeCondition(field.id, ci)} className="text-red-500">حذف</button></div>)}</div>}
        </div>}
      </div>;
    })}
  </div>;
}
