import type { ToolDefinition } from "@/lib/tools";

export const extraTools: ToolDefinition[] = [
  { id: "percentage-calculator", title: "محاسبه درصد", description: "محاسبه درصد، افزایش، کاهش و اختلاف درصدی به‌صورت سریع.", icon: "%", category: "general", type: "normal", href: "/tools/percentage-calculator", featured: true, enabled: true, seoTitle: "محاسبه درصد آنلاین | Percentage Calculator | توسن", seoDescription: "درصد یک عدد، درصد افزایش و کاهش و اختلاف درصدی را آنلاین و سریع محاسبه کنید.", indexable: true },
  { id: "loan-calculator", title: "محاسبه اقساط وام", description: "محاسبه قسط ماهانه، سود کل و جدول بازپرداخت وام.", icon: "💳", category: "general", type: "normal", href: "/tools/loan-calculator", featured: true, enabled: true, seoTitle: "محاسبه اقساط وام آنلاین | Loan Calculator | توسن", seoDescription: "مبلغ قسط ماهانه، سود کل و مجموع بازپرداخت وام را با نرخ سود و مدت بازپرداخت محاسبه کنید.", indexable: true },
  { id: "qr-code-generator", title: "ساخت QR Code", description: "تبدیل لینک، متن، شماره تلفن و اطلاعات کاربردی به QR Code قابل دانلود.", icon: "▦", category: "general", type: "normal", href: "/tools/qr-code-generator", featured: true, enabled: true, seoTitle: "ساخت QR Code آنلاین | QR Code Generator | توسن", seoDescription: "لینک، متن و اطلاعات خود را به QR Code تبدیل کنید و تصویر آن را دانلود کنید؛ بدون ثبت‌نام و با پردازش در مرورگر.", indexable: true },
  { id: "unit-converter", title: "تبدیل واحد", description: "تبدیل طول، وزن، دما، حجم، مساحت، سرعت، زمان و حجم داده.", icon: "⇄", category: "general", type: "normal", href: "/tools/unit-converter", featured: true, enabled: true, seoTitle: "تبدیل واحد آنلاین | Unit Converter | طول، وزن، دما و حجم | توسن", seoDescription: "واحدهای طول، وزن، دما، حجم، مساحت، سرعت، زمان و داده را آنلاین و سریع تبدیل کنید.", indexable: true },
  { id: "pdf-to-image", title: "تبدیل PDF به عکس", description: "تبدیل صفحات PDF به تصاویر PNG یا JPG با کیفیت انتخابی و دانلود جداگانه هر صفحه.", icon: "🖼️", category: "general", type: "normal", href: "/tools/pdf-manager/pdf-to-image", featured: true, enabled: true, seoTitle: "تبدیل PDF به عکس آنلاین | PDF to JPG/PNG | توسن", seoDescription: "صفحات PDF را به تصویر PNG یا JPG تبدیل کنید؛ پردازش داخل مرورگر و دانلود جداگانه هر صفحه.", indexable: true },
  { id: "image-manager", title: "مدیریت عکس", description: "تغییر اندازه، فشرده‌سازی، تبدیل JPG، PNG و WebP و چرخش چند تصویر به‌صورت یکجا.", icon: "🖼️", category: "general", type: "normal", href: "/tools/image-manager", featured: true, enabled: true, seoTitle: "مدیریت عکس آنلاین | تغییر اندازه و تبدیل فرمت تصویر | توسن", seoDescription: "تصاویر را آنلاین تغییر اندازه دهید، فشرده کنید، به JPG، PNG یا WebP تبدیل کنید و بچرخانید؛ پردازش داخل مرورگر.", indexable: true },
  { id: "video-manager", title: "مدیریت ویدیو", description: "پیش‌نمایش ویدیو، نمایش مشخصات فایل و استخراج تصویر شاخص بدون آپلود روی سرور.", icon: "🎬", category: "general", type: "normal", href: "/tools/video-manager", featured: true, enabled: true, seoTitle: "مدیریت ویدیو آنلاین | Video Manager | توسن", seoDescription: "ویدیو را آنلاین پیش‌نمایش کنید، مشخصات آن را ببینید و تصویر شاخص استخراج کنید؛ بدون آپلود فایل روی سرور.", indexable: true },
];
