"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import OrderStatus from "@/components/orders/OrderStatus";
import AdminOrderStatus from "@/components/AdminOrderStatus";
import OrderMessages from "@/components/OrderMessages";
import AdminOrderFiles from "@/components/AdminOrderFiles";
import { GlassPanel, TusanCard, TusanButton, SectionHeader } from "@/components/ui";
import { buildFieldLabelMap } from "@/lib/formFieldLabels";

export default function AdminOrderDetailPage() {
  const params = useParams(); const router = useRouter(); const id = params.id as string;
  const [order,setOrder]=useState<any>(null); const [payment,setPayment]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [paymentBusy,setPaymentBusy]=useState(false); const [paymentMessage,setPaymentMessage]=useState("");
  const STATUS_LABELS:Record<string,string>={registered:"ثبت شده",checking:"در حال بررسی",need_documents:"نیازمند مدارک",processing:"در حال انجام",ready:"آماده تحویل",completed:"تکمیل شده",cancelled:"لغو شده"};
  useEffect(()=>{if(id)loadOrder();},[id]);
  async function loadOrder(){setLoading(true);setError("");try{const {data:{user}}=await supabase.auth.getUser();if(!user){router.push("/login");return;}const {data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(profile?.role!=="admin"){router.push("/dashboard");return;}const {data,error:orderError}=await supabase.from("orders").select(`*,services(title,icon,description,form_schema),custom_forms:form_id(id,title,schema,price),profiles!orders_user_id_fkey(full_name,phone),order_history(id,old_status,new_status,description,created_at)`).eq("id",id).single();if(orderError||!data)throw new Error(orderError?.message||"سفارش موردنظر پیدا نشد.");setOrder(data);const {data:p,error:paymentError}=await supabase.from("payments").select("id,method,gateway,status,amount,receipt_image_url,paid_at,created_at,admin_note").eq("order_id",id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(paymentError)console.warn(paymentError.message);setPayment(p||null);}catch(err:any){setError(err?.message||"خطایی هنگام دریافت سفارش رخ داد.");}finally{setLoading(false);}}
  async function reviewPayment(action:"approve"|"reject"){if(!payment)return;setPaymentBusy(true);setPaymentMessage("");try{if(action==="approve"){const amount=Number(order.price||0),paymentAmount=Number(payment.amount||0);if(paymentAmount!==amount)throw new Error(`مبلغ پرداخت (${paymentAmount.toLocaleString("fa-IR")} تومان) با مبلغ سفارش (${amount.toLocaleString("fa-IR")} تومان) برابر نیست.`);const {error:e}=await supabase.from("payments").update({status:"paid",paid_at:new Date().toISOString(),admin_note:"تأیید پرداخت کارت‌به‌کارت توسط مدیریت"}).eq("id",payment.id);if(e)throw new Error(e.message);if(order.status==="registered"){const {error:oe}=await supabase.from("orders").update({status:"checking",updated_at:new Date().toISOString()}).eq("id",order.id);if(oe)throw new Error(oe.message);}setPayment({...payment,status:"paid",paid_at:new Date().toISOString()});setOrder({...order,status:order.status==="registered"?"checking":order.status});setPaymentMessage("پرداخت تأیید شد و سفارش وارد مرحله بررسی شد.");}else{const {error:e}=await supabase.from("payments").update({status:"rejected",admin_note:"رسید پرداخت توسط مدیریت رد شد"}).eq("id",payment.id);if(e)throw new Error(e.message);setPayment({...payment,status:"rejected"});setPaymentMessage("رسید پرداخت رد شد. کاربر می‌تواند رسید جدید ارسال کند.");}}catch(err:any){setPaymentMessage(err?.message||"عملیات پرداخت ناموفق بود.");}finally{setPaymentBusy(false);}}
  async function openReceipt(){if(!payment?.receipt_image_url)return;const {data,error}=await supabase.storage.from("payment-receipts").createSignedUrl(payment.receipt_image_url,300);if(error||!data?.signedUrl){setPaymentMessage("امکان دریافت رسید وجود ندارد.");return;}window.open(data.signedUrl,"_blank","noopener,noreferrer");}
  if(loading)return <div dir="rtl" className="min-h-screen page-background flex items-center justify-center"><GlassPanel className="p-10 text-center text-[var(--text-muted)]">در حال دریافت اطلاعات سفارش...</GlassPanel></div>;
  if(!order)return <div dir="rtl" className="min-h-screen page-background p-6"><div className="max-w-2xl mx-auto"><GlassPanel className="p-8 text-center"><div className="text-5xl mb-4">⚠️</div><h1 className="text-xl font-bold">سفارش پیدا نشد</h1><p className="text-[var(--text-muted)] mt-2">{error}</p><Link href="/admin/orders"><TusanButton className="mt-6">بازگشت</TusanButton></Link></GlassPanel></div></div>;
  const history=[...(order.order_history||[])].sort((a:any,b:any)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime()); const cardPayment=payment?.method==="card_to_card"; const fieldLabelMap=buildFieldLabelMap(Array.isArray(order.form_schema_snapshot)&&order.form_schema_snapshot.length?order.form_schema_snapshot:order.custom_forms?.schema?.length?order.custom_forms.schema:order.services?.form_schema); const formEntries=Object.entries(order.form_data||{});
  return <div dir="rtl" className="min-h-screen page-background p-6 text-[var(--text)]"><div className="max-w-4xl mx-auto space-y-5"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><SectionHeader title="مدیریت سفارش" description={`${order.services?.icon||"📋"} ${order.custom_forms?.title||order.services?.title||"سفارش"}`}/><Link href="/admin/orders"><TusanButton variant="secondary">بازگشت به سفارش‌ها</TusanButton></Link></div>
    <GlassPanel className="p-6"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h2 className="text-xl font-bold">{order.services?.icon} {order.custom_forms?.title||order.services?.title}</h2><p className="text-[var(--text-muted)] mt-2">کد پیگیری: <strong>{order.tracking_code||"---"}</strong></p></div><OrderStatus status={order.status}/></div><div className="grid sm:grid-cols-2 gap-4 mt-6 pt-5 border-t"><TusanCard className="p-4"><div className="text-sm text-[var(--text-muted)]">نام مشتری</div><div className="font-bold mt-1">{order.profiles?.full_name||"---"}</div></TusanCard><TusanCard className="p-4"><div className="text-sm text-[var(--text-muted)]">شماره تماس</div><div className="font-bold mt-1">{order.profiles?.phone||"---"}</div></TusanCard><TusanCard className="p-4"><div className="text-sm text-[var(--text-muted)]">مبلغ سفارش</div><div className="font-bold mt-1">{Number(order.price||0).toLocaleString("fa-IR")} تومان</div></TusanCard><TusanCard className="p-4"><div className="text-sm text-[var(--text-muted)]">تاریخ ثبت</div><div className="font-bold mt-1">{new Date(order.created_at).toLocaleString("fa-IR")}</div></TusanCard></div></GlassPanel>
    {cardPayment&&<GlassPanel className="p-6 border border-amber-200"><div className="flex items-center justify-between gap-3 mb-5"><div><h2 className="text-xl font-bold">بررسی پرداخت کارت‌به‌کارت</h2><p className="text-sm text-[var(--text-muted)] mt-1">وضعیت: {payment.status==="awaiting_manual_verification"?"در انتظار بررسی":payment.status==="paid"?"تأیید شده":payment.status==="rejected"?"رد شده":payment.status}</p></div><div className="font-bold">{Number(payment.amount||0).toLocaleString("fa-IR")} تومان</div></div><div className="grid sm:grid-cols-3 gap-4 mb-5"><TusanCard className="p-4"><div className="text-sm text-[var(--text-secondary)]">روش</div><div className="font-bold mt-1">کارت‌به‌کارت</div></TusanCard><TusanCard className="p-4"><div className="text-sm text-[var(--text-secondary)]">مبلغ سفارش</div><div className="font-bold mt-1">{Number(order.price||0).toLocaleString("fa-IR")} تومان</div></TusanCard><TusanCard className="p-4"><div className="text-sm text-[var(--text-secondary)]">تاریخ پرداخت</div><div className="font-bold mt-1">{payment.paid_at?new Date(payment.paid_at).toLocaleString("fa-IR"):"---"}</div></TusanCard></div>{payment.receipt_image_url?<div className="flex flex-wrap gap-3"><TusanButton type="button" onClick={openReceipt}>مشاهده رسید</TusanButton>{payment.status==="awaiting_manual_verification"&&<><TusanButton type="button" onClick={()=>reviewPayment("approve")} disabled={paymentBusy}>تأیید پرداخت</TusanButton><TusanButton type="button" variant="secondary" onClick={()=>reviewPayment("reject")} disabled={paymentBusy}>رد رسید</TusanButton></>}</div>:<div className="rounded-xl bg-gray-50 p-4 text-[var(--text-secondary)]">هنوز رسیدی برای این پرداخت ارسال نشده است.</div>}{paymentMessage&&<div className="mt-4 rounded-xl bg-[var(--surface)] border p-4 text-sm leading-6">{paymentMessage}</div>}</GlassPanel>}
    <GlassPanel className="p-6"><h2 className="text-xl font-bold mb-4">تغییر وضعیت سفارش</h2><AdminOrderStatus orderId={order.id} currentStatus={order.status} onUpdate={loadOrder}/></GlassPanel>
    <GlassPanel className="p-6"><h2 className="text-xl font-bold mb-5">اطلاعات ارسال شده</h2>{formEntries.length===0?<p className="text-[var(--text-muted)]">اطلاعاتی برای این سفارش ارسال نشده است.</p>:<div className="space-y-3">{formEntries.map(([key,value]:any)=><div key={key} className="border border-[var(--border)] rounded-xl p-4 bg-[var(--surface)]"><div className="text-sm text-[var(--text-secondary)] mb-1">{fieldLabelMap[key]||key}</div><div className="font-bold break-words">{Array.isArray(value)?value.join("، "):value===true?"بله":value===false?"خیر":String(value??"---")}</div></div>)}</div>}</GlassPanel>
    <AdminOrderFiles orderId={order.id}/><OrderMessages orderId={order.id}/><GlassPanel className="p-6"><h2 className="text-xl font-bold mb-5">تاریخچه سفارش</h2>{history.length===0?<p className="text-[var(--text-muted)]">هنوز تاریخچه‌ای ثبت نشده است.</p>:<div className="space-y-5">{history.map((item:any)=><div key={item.id} className="border-r-4 border-[var(--primary)] pr-4"><p className="font-bold">{item.old_status===item.new_status?"ثبت سفارش":`تغییر وضعیت از ${STATUS_LABELS[item.old_status]||item.old_status} به ${STATUS_LABELS[item.new_status]||item.new_status}`}</p>{item.description&&<p className="text-sm mt-1">{item.description}</p>}<p className="text-[var(--text-muted)] text-sm mt-2">{new Date(item.created_at).toLocaleString("fa-IR")}</p></div>)}</div>}</GlassPanel>
  </div></div>;
}