"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { GlassPanel, TusanButton, SectionHeader } from "@/components/ui";

type Summary={available_balance:number;pending_settlement:number;settled_total:number;debt:number;total_earned:number};
type Bank={id:string;account_title:string;iban:string;account_number:string|null;is_default:boolean;is_active:boolean;status:string;verified_at:string|null};
const money=(n:number)=>Number(n||0).toLocaleString("fa-IR");
const bankStatus=(s:string)=>({pending:"در انتظار تأیید",approved:"تأیید شده",rejected:"رد شده"}[s]||s);
export default function StaffFinancePage(){
 const [summary,setSummary]=useState<Summary|null>(null),[banks,setBanks]=useState<Bank[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [title,setTitle]=useState(""),[iban,setIban]=useState(""),[accountNumber,setAccountNumber]=useState(""),[amount,setAmount]=useState("");
 async function load(){setLoading(true);setMessage("");const [s,b]=await Promise.all([supabase.rpc("get_staff_financial_summary"),supabase.rpc("list_my_staff_bank_accounts")]);if(s.error){setMessage(s.error.message)}else setSummary(Array.isArray(s.data)?s.data[0]||null:s.data);if(b.error)setMessage(prev=>prev||b.error.message);else setBanks((b.data||[]) as Bank[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function addBank(){setBusy(true);setMessage("");const {error}=await supabase.rpc("add_staff_bank_account",{p_account_title:title,p_iban:iban,p_account_number:accountNumber||null,p_is_default:banks.length===0});setMessage(error?error.message:"حساب ثبت شد و برای تأیید مدیر اصلی ارسال شد.");if(!error){setTitle("");setIban("");setAccountNumber("");await load()}setBusy(false)}
 async function requestSettlement(){setBusy(true);setMessage("");const selected=banks.find(b=>b.status==="approved"&&b.is_active);const value=Number(amount.replace(/,/g,""));if(!selected){setMessage("ابتدا یک شماره شبای تأییدشده ثبت کنید.");setBusy(false);return}if(!Number.isFinite(value)||value<=1000){setMessage("مبلغ تسویه باید بیشتر از ۱۰۰۰ ریال باشد.");setBusy(false);return}const {error}=await supabase.rpc("request_staff_settlement",{p_bank_account_id:selected.id,p_amount:Math.trunc(value)});setMessage(error?error.message:"درخواست تسویه با موفقیت ثبت شد.");if(!error){setAmount("");await load()}setBusy(false)}
 if(loading)return <main dir="rtl" className="min-h-screen page-background p-6"><GlassPanel className="p-10 text-center">در حال دریافت اطلاعات مالی...</GlassPanel></main>;
 return <main dir="rtl" className="min-h-screen page-background p-4 sm:p-6 text-[var(--text)]"><div className="mx-auto max-w-6xl space-y-6"><SectionHeader title="درآمد و تسویه حساب" description="مدیریت درآمد، حساب‌های بانکی و درخواست‌های تسویه"/>{message&&<GlassPanel className="p-4 text-sm leading-7">{message}</GlassPanel>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["قابل تسویه",summary?.available_balance], ["در انتظار تسویه",summary?.pending_settlement],["تسویه‌شده",summary?.settled_total],["کل درآمد",summary?.total_earned]].map(([label,value])=><GlassPanel key={String(label)} className="p-5"><div className="text-sm text-[var(--text-muted)]">{label}</div><div className="mt-2 text-2xl font-black">{money(Number(value))} ریال</div></GlassPanel>)}</div><div className="grid gap-6 lg:grid-cols-2"><GlassPanel className="p-5"><h2 className="text-lg font-black">حساب‌های بانکی</h2><div className="mt-4 space-y-3">{banks.length?banks.map(b=><div key={b.id} className="rounded-2xl border border-[var(--border)] p-4"><div className="flex items-center justify-between gap-3"><div className="font-bold">{b.account_title}</div><span className="text-xs rounded-full px-2 py-1 bg-[var(--surface-muted)]">{bankStatus(b.status)}</span></div><div className="mt-2 font-mono text-sm">{b.iban}</div></div>):<p className="text-sm text-[var(--text-muted)]">حساب بانکی ثبت نشده است.</p>}</div><div className="mt-5 space-y-3"><input className="w-full rounded-xl border p-3 bg-transparent" placeholder="عنوان حساب" value={title} onChange={e=>setTitle(e.target.value)}/><input className="w-full rounded-xl border p-3 bg-transparent font-mono" placeholder="IR... شماره شبا" value={iban} onChange={e=>setIban(e.target.value)}/><input className="w-full rounded-xl border p-3 bg-transparent" placeholder="شماره حساب (اختیاری)" value={accountNumber} onChange={e=>setAccountNumber(e.target.value)}/><TusanButton fullWidth disabled={busy||!title||!iban} onClick={()=>void addBank()}>ثبت حساب برای تأیید</TusanButton></div></GlassPanel><GlassPanel className="p-5"><h2 className="text-lg font-black">درخواست تسویه</h2><p className="mt-2 text-sm text-[var(--text-muted)] leading-7">فقط حساب بانکی تأییدشده توسط مدیر اصلی قابل استفاده است. کارمزد ثابت تسویه ۱۰۰۰ ریال است.</p><div className="mt-5 space-y-4"><div className="rounded-2xl bg-[var(--surface-muted)] p-4 text-sm">موجودی قابل تسویه: <b>{money(summary?.available_balance||0)} ریال</b></div><input inputMode="numeric" className="w-full rounded-xl border p-3 bg-transparent" placeholder="مبلغ تسویه به ریال" value={amount} onChange={e=>setAmount(e.target.value)}/><TusanButton fullWidth disabled={busy||!amount||!banks.some(b=>b.status==="approved"&&b.is_active)} onClick={()=>void requestSettlement()}>ثبت درخواست تسویه</TusanButton><div className="text-xs text-[var(--text-muted)]">حداقل مبلغ: بیشتر از ۱۰۰۰ ریال — مبلغ خالص پس از کسر کارمزد پرداخت می‌شود.</div></div></GlassPanel></div></div></main>;
}
