"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { supabase } from "@/lib/supabase";
import OrderStatus from "@/components/orders/OrderStatus";
import { getAdminUnreadMessagesByOrder, getAdminUnreadMessagesCount } from "@/lib/notifications";
import AdminDashboard from "@/components/admin/AdminDashboard";
import { useTheme } from "@/components/theme/ThemeProvider";
import { GlassPanel,TusanCard,TusanButton,SectionHeader } from "@/components/ui";
type Tab="orders"|"services"|"announcements";
export default function AdminPage(){const[activeTab,setActiveTab]=useState<Tab>("orders");const[orders,setOrders]=useState<any[]>([]);const[services,setServices]=useState<any[]>([]);const[loadingOrders,setLoadingOrders]=useState(true);const[loadingServices,setLoadingServices]=useState(true);const[unreadCount,setUnreadCount]=useState(0);const[orderUnread,setOrderUnread]=useState<Record<string,number>>({});const{theme,toggleTheme}=useTheme();
 useEffect(()=>{loadOrders();loadAdminUnread();loadServices();const channel=supabase.channel("admin-messages").on("postgres_changes",{event:"*",schema:"public",table:"messages"},async()=>{await loadAdminUnread();await loadOrders()}).subscribe();return()=>{supabase.removeChannel(channel)}},[]);
 async function loadAdminUnread(){setUnreadCount(await getAdminUnreadMessagesCount())} async function loadOrderUnread(list:any[]=orders){if(!list.length){setOrderUnread({});return}const entries=await Promise.all(list.map(async o=>[o.id,await getAdminUnreadMessagesByOrder(o.id)] as const));setOrderUnread(Object.fromEntries(entries))}
 async function loadOrders(){setLoadingOrders(true);try{const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(profile?.role!=="admin")return;const{data,error}=await supabase.from("orders").select("*,services(title,icon),profiles(full_name,phone)").order("created_at",{ascending:false});if(!error){const next=data||[];setOrders(next);await loadOrderUnread(next)}}finally{setLoadingOrders(false)}}
 async function loadServices(){setLoadingServices(true);const{data,error}=await supabase.from("services").select("*").order("created_at",{ascending:false});if(!error)setServices(data||[]);setLoadingServices(false)}
 async function toggleActive(id:string,current:boolean){const{error}=await supabase.from("services").update({is_active:!current}).eq("id",id);if(error)alert("خطا در بروزرسانی وضعیت خدمت");else await loadServices()} async function deleteService(id:string){if(!confirm("آیا از حذف این خدمت مطمئن هستید؟"))return;const{error}=await supabase.from("services").delete().eq("id",id);if(error)alert("خطا در حذف خدمت");else await loadServices()}
 function renderOrders(){if(loadingOrders)return <div className="bg-white rounded-2xl shadow p-10 text-center text-gray-500">در حال دریافت سفارش‌ها...</div>;if(!orders.length)return <GlassPanel className="p-10 text-center"><div className="text-5xl mb-4">📭</div><p className="text-[var(--text-muted)]">هنوز سفارشی ثبت نشده است.</p></GlassPanel>;return <div className="space-y-4">{orders.map(order=>{const unread=orderUnread[order.id]||0;return <TusanCard key={order.id} className="p-5"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><h2 className="font-bold text-xl">{order.services?.icon} {order.services?.title}</h2><OrderStatus status={order.status}/></div>{unread>0&&<Link href={`/admin/orders/${order.id}`} className="mt-4 flex items-center justify-between gap-3 bg-red-50 border border-red-200 text-red-700 rounded-xl px-4 py-3"><span className="font-bold">💬 {unread.toLocaleString("fa-IR")} پیام جدید مشتری</span><span className="text-sm font-bold">مشاهده پیام‌ها ←</span></Link>}<div className="mt-3 space-y-1"><p>مشتری: {order.profiles?.full_name||"---"}</p><p>تلفن: {order.profiles?.phone||"---"}</p><p>کد پیگیری: {order.tracking_code||"---"}</p></div><div className="mt-4"><Link href={`/admin/orders/${order.id}`} className="block"><TusanButton fullWidth>مدیریت سفارش</TusanButton></Link></div></TusanCard>})}</div>}
 function renderServices(){if(loadingServices)return <div className="bg-white rounded-2xl shadow p-10 text-center text-gray-500">در حال دریافت خدمات...</div>;return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><SectionHeader title="مدیریت خدمات" description="ایجاد، ویرایش، حذف و فعال یا غیرفعال کردن خدمات"/><Link href="/admin/services/new"><TusanButton>+ خدمت جدید</TusanButton></Link></div><GlassPanel className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[800px]"><thead className="bg-gray-50"><tr><th className="p-3 text-right">آیکون</th><th className="p-3 text-right">عنوان</th><th className="p-3 text-right">دسته‌بندی</th><th className="p-3 text-right">قیمت</th><th className="p-3 text-right">وضعیت</th><th className="p-3 text-right">عملیات</th></tr></thead><tbody>{services.map(service=><tr key={service.id} className="border-t"><td className="p-3 text-2xl">{service.icon}</td><td className="p-3 font-medium">{service.title}</td><td className="p-3">{service.category}</td><td className="p-3">{service.price?Number(service.price).toLocaleString("fa-IR")+" تومان":"-"}</td><td className="p-3"><span className={`px-2 py-1 rounded-full text-sm ${service.is_active?"bg-green-100 text-green-700":"bg-red-100 text-red-700"}`}>{service.is_active?"فعال":"غیرفعال"}</span></td><td className="p-3"><div className="flex gap-2"><Link href={`/admin/services/${service.id}`} className="px-3 py-1 rounded-lg bg-blue-500 text-white text-sm">ویرایش</Link><button onClick={()=>toggleActive(service.id,service.is_active)} className="px-3 py-1 rounded-lg bg-yellow-500 text-white text-sm">{service.is_active?"غیرفعال":"فعال"}</button><button onClick={()=>deleteService(service.id)} className="px-3 py-1 rounded-lg bg-red-500 text-white text-sm">حذف</button></div></td></tr>)}</tbody></table></div></GlassPanel></div>}
 function renderAnnouncements(){return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><SectionHeader title="مدیریت اطلاعیه‌ها" description="ثبت‌نام‌های فعال، اطلاعیه‌ها و اسلایدر صفحه خدمات"/><Link href="/admin/announcements/new"><TusanButton>+ اطلاعیه جدید</TusanButton></Link></div><GlassPanel className="p-8 text-center"><div className="text-5xl mb-4">📢</div><h3 className="text-xl font-bold">مدیریت اطلاعیه‌ها و ثبت‌نام‌های فعال</h3><p className="text-gray-500 mt-2 leading-7">از این بخش می‌توانید اطلاعیه‌ها، ثبت‌نام‌های فعال و آیتم‌های اسلایدر صفحه خدمات را مدیریت کنید.</p><div className="mt-6 flex justify-center"><Link href="/admin/announcements"><TusanButton>ورود به مدیریت اطلاعیه‌ها</TusanButton></Link></div></GlassPanel></div>}
 return <div dir="rtl" className="min-h-screen page-background text-[var(--text)] p-4 sm:p-6"><div className="max-w-6xl mx-auto space-y-6"><div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-6"><div className="flex-1"><SectionHeader title="پنل مدیریت کافی‌نت" description="مدیریت سفارش‌ها، خدمات، اطلاعیه‌ها و وضعیت سامانه از یک داشبورد یکپارچه"/><div className="mt-4"><AdminDashboard/></div></div>{unreadCount>0&&<GlassPanel className="p-4 min-w-[260px] border-red-500/20 bg-red-500/10"><Link href="/admin/orders" className="block"><div className="font-bold flex items-center gap-2 text-red-700">🔔 پیام‌های جدید مشتریان</div><div className="text-sm mt-2 text-red-700/80">{unreadCount.toLocaleString("fa-IR")} پیام خوانده‌نشده</div></Link></GlassPanel>}</div><GlassPanel className="p-2"><div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><button type="button" onClick={()=>setActiveTab("orders")} className={`relative rounded-xl px-4 py-3 font-bold ${activeTab==="orders"?"bg-[var(--primary)] text-white shadow":"text-[var(--text-secondary)] hover:bg-[var(--surface)]"}`}>📋 مدیریت سفارش‌ها{unreadCount>0&&<span className="absolute -top-2 -left-2 min-w-7 h-7 px-2 rounded-full flex items-center justify-center text-xs font-bold bg-red-500 text-white">{unreadCount.toLocaleString("fa-IR")}</span>}</button><button type="button" onClick={()=>setActiveTab("services")} className={`rounded-xl px-4 py-3 font-bold ${activeTab==="services"?"bg-[var(--primary)] text-white shadow":"text-[var(--text-secondary)] hover:bg-[var(--surface)]"}`}>⚙️ مدیریت خدمات</button><button type="button" onClick={()=>setActiveTab("announcements")} className={`rounded-xl px-4 py-3 font-bold ${activeTab==="announcements"?"bg-[var(--primary)] text-white shadow":"text-[var(--text-secondary)] hover:bg-[var(--surface)]"}`}>📢 اطلاعیه‌ها</button><Link href="/admin/staff" className="rounded-xl px-4 py-3 font-bold text-center text-[var(--text-secondary)] hover:bg-[var(--surface)]">👥 اعطای دسترسی</Link></div></GlassPanel>{activeTab==="orders"?renderOrders():activeTab==="services"?renderServices():renderAnnouncements()}</div></div>}
