"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { ArrowRight, RefreshCw, Activity, RotateCcw, ExternalLink, CheckCircle2, Clock3, CircleAlert } from "lucide-react";
import { supabase } from "@/lib/supabase";

interface Order { id:string; tracking_code:string; link:string; quantity:number; price:number; status:string; provider_order_id:string|null; payment_provider:string|null; payment_reference:string|null; created_at:string; updated_at:string|null; social_services?:{name:string}|null; social_platforms?:{name:string}|null }
const labels:Record<string,string>={pending:"در انتظار پرداخت",awaiting_payment:"در انتظار پرداخت",paid:"پرداخت‌شده",processing:"در حال پردازش",completed:"تکمیل‌شده",partial:"ناقص",cancelled:"لغوشده",failed:"ناموفق"};
const steps=["pending","paid","processing","completed"];
export default function SocialOrderDetail(){
 const {id}=useParams<{id:string}>(); const [order,setOrder]=useState<Order|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 async function load(){setLoading(true);const {data}=await supabase.from("social_orders").select("*, social_services(name), social_platforms(name)").eq("id",id).single();setOrder(data as Order|null);setLoading(false)}
 useEffect(()=>{if(id)void load()},[id]);
 async function authHeaders(){const {data}=await supabase.auth.getSession();return data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{}}
 async function status(){setBusy(true);setMessage("");try{const r=await fetch("/api/social/provider-status",{method:"POST",headers:{"Content-Type":"application/json",...(await authHeaders())},body:JSON.stringify({orderId:id})});const d=await r.json();if(!r.ok)throw new Error(d.error||"خطا");setMessage(`وضعیت به «${labels[d.status]||d.status}» بروزرسانی شد.`);await load()}catch(e){setMessage(e instanceof Error?e.message:"خطا در بررسی وضعیت")}finally{setBusy(false)}}
 async function resend(){if(!order||!confirm(`ارسال مجدد ${order.tracking_code} انجام شود؟`))return;setBusy(true);try{const r=await fetch("/api/social/provider-resend",{method:"POST",headers:{"Content-Type":"application/json",...(await authHeaders())},body:JSON.stringify({orderId:id})});const d=await r.json();if(!r.ok)throw new Error(d.error||"خطا");setMessage("سفارش با موفقیت مجدداً ارسال شد.");await load()}catch(e){setMessage(e instanceof Error?e.message:"ارسال مجدد ناموفق بود")}finally{setBusy(false)}}
 if(loading)return <main dir="rtl" className="min-h-screen bg-slate-50 p-8 text-center text-slate-500">در حال دریافت سفارش...</main>;
 if(!order)return <main dir="rtl" className="min-h-screen bg-slate-50 p-8 text-center">سفارش پیدا نشد.</main>;
 const current=steps.indexOf(order.status); const terminal=["failed","cancelled","partial"].includes(order.status);
 return <main dir="rtl" className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-5xl space-y-6">
  <div className="flex items-center justify-between"><Link href="/admin/social/orders" className="inline-flex items-center gap-2 text-sm text-slate-600"><ArrowRight size={18}/> بازگشت به سفارش‌ها</Link><button onClick={()=>void load()} className="rounded-xl bg-white p-2 shadow-sm"><RefreshCw size={18}/></button></div>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="text-sm text-slate-500">کد پیگیری</p><h1 className="text-2xl font-bold">{order.tracking_code}</h1><p className="mt-1 text-sm text-slate-500">{order.social_platforms?.name||"—"} · {order.social_services?.name||"—"}</p></div><span className="rounded-full bg-slate-100 px-4 py-2 text-sm font-medium">{labels[order.status]||order.status}</span></div></section>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-6 font-bold">روند سفارش</h2><div className="grid gap-5 md:grid-cols-4">{steps.map((s,i)=>{const done=current>=i&&!terminal;return <div key={s} className="flex items-start gap-3"><div className={`mt-0.5 rounded-full p-2 ${done?"bg-emerald-100 text-emerald-600":"bg-slate-100 text-slate-400"}`}>{done?<CheckCircle2 size={18}/>:<Clock3 size={18}/>}</div><div><div className="font-medium">{labels[s]}</div><div className="text-xs text-slate-400">{done?"انجام شده":"در انتظار"}</div></div></div>})}</div>{terminal&&<div className="mt-6 flex items-center gap-2 rounded-xl bg-amber-50 p-3 text-sm text-amber-800"><CircleAlert size={18}/>{labels[order.status]||order.status}</div>}</section>
  <section className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-bold">اطلاعات سفارش</h2><dl className="space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">تعداد</dt><dd>{order.quantity.toLocaleString("fa-IR")}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">مبلغ</dt><dd>{Number(order.price).toLocaleString("fa-IR")} تومان</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">ثبت</dt><dd>{new Date(order.created_at).toLocaleString("fa-IR")}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">بروزرسانی</dt><dd>{order.updated_at?new Date(order.updated_at).toLocaleString("fa-IR"):"—"}</dd></div></dl><a href={order.link} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-emerald-600"><ExternalLink size={16}/> مشاهده لینک سفارش</a></div>
  <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-bold">پرداخت و Provider</h2><dl className="space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">درگاه</dt><dd>{order.payment_provider||"—"}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">مرجع پرداخت</dt><dd>{order.payment_reference||"—"}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Provider Order ID</dt><dd>{order.provider_order_id||"—"}</dd></div></dl><div className="mt-5 flex flex-wrap gap-2">{order.provider_order_id&&<button disabled={busy} onClick={()=>void status()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm disabled:opacity-50"><Activity size={16}/>{busy?"در حال بررسی":"بررسی وضعیت"}</button>}{["failed","cancelled"].includes(order.status)&&!order.provider_order_id&&<button disabled={busy} onClick={()=>void resend()} className="inline-flex items-center gap-2 rounded-xl bg-amber-500 px-3 py-2 text-sm text-white disabled:opacity-50"><RotateCcw size={16}/>{busy?"در حال ارسال":"ارسال مجدد"}</button>}</div></div></section>
  {message&&<div className="rounded-xl border border-slate-200 bg-white p-4 text-sm">{message}</div>}
 </div></main>;
}
