"use client";
import { useEffect,useMemo,useState } from "react";
import { supabase } from "@/lib/supabase";
import { GlassPanel,TusanButton,SectionHeader } from "@/components/ui";
type Row={id:string;staff_id:string;amount:number;fee_amount:number;net_amount:number;status:string;admin_note:string|null;requested_at:string;processed_at:string|null;staff_name:string;staff_email:string;iban:string};
const labels:Record<string,string>={requested:"در انتظار بررسی",approved:"تأیید شده",processing:"در حال پرداخت",paid:"پرداخت شده",rejected:"رد شده"};
const money=(n:number)=>Number(n||0).toLocaleString("fa-IR");
export default function AdminSettlementsPage(){const [rows,setRows]=useState<Row[]>([]),[filter,setFilter]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState("");
 async function load(){setLoading(true);const {data,error}=await supabase.rpc("admin_list_staff_settlements",{p_status:filter||null});if(error)setMessage(error.message);else setRows((data||[]) as Row[]);setLoading(false)}
 useEffect(()=>{void load()},[filter]);
 async function action(id:string,action:string){setBusy(id);setMessage("");const {error}=await supabase.rpc("admin_update_staff_settlement",{p_settlement_id:id,p_action:action,p_note:null});setMessage(error?error.message:"عملیات با موفقیت انجام شد.");if(!error)await load();setBusy(null)}
 const stats=useMemo(()=>({requested:rows.filter(r=>r.status==="requested").length,open:rows.filter(r=>["requested","approved","processing"].includes(r.status)).reduce((s,r)=>s+Number(r.amount||0),0),paid:rows.filter(r=>r.status==="paid").reduce((s,r)=>s+Number(r.net_amount||0),0)}),[rows]);
 return <main dir="rtl" className="min-h-screen page-background p-4 sm:p-6 text-[var(--text)]"><div className="mx-auto max-w-7xl space-y-6"><SectionHeader title="مدیریت تسویه حساب مدیران" description="بررسی، تأیید، پردازش و ثبت پرداخت درخواست‌های تسویه"/>{message&&<GlassPanel className="p-4 text-sm">{message}</GlassPanel>}<div className="grid gap-4 sm:grid-cols-3"><GlassPanel className="p-5"><div className="text-sm text-[var(--text-muted)]">درخواست‌های در انتظار</div><div className="text-2xl font-black mt-2">{stats.requested.toLocaleString("fa-IR")}</div></GlassPanel><GlassPanel className="p-5"><div className="text-sm text-[var(--text-muted)]">مبلغ تسویه‌های باز</div><div className="text-2xl font-black mt-2">{money(stats.open)} ریال</div></GlassPanel><GlassPanel className="p-5"><div className="text-sm text-[var(--text-muted)]">خالص پرداخت‌شده</div><div className="text-2xl font-black mt-2">{money(stats.paid)} ریال</div></GlassPanel></div><div className="flex gap-2 flex-wrap">{[["","همه"],["requested","در انتظار"],["approved","تأیید شده"],["processing","در حال پرداخت"],["paid","پرداخت شده"],["rejected","رد شده"]].map(([v,l])=><button key={v} onClick={()=>setFilter(v)} className={`px-4 py-2 rounded-xl text-sm font-bold ${filter===v?"bg-[var(--primary)] text-white":"bg-[var(--surface-muted)]"}`}>{l}</button>)}</div>{loading?<GlassPanel className="p-10 text-center">در حال دریافت درخواست‌ها...</GlassPanel>:rows.length?<div className="grid gap-4">{rows.map(r=><GlassPanel key={r.id} className="p-5"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><div className="font-black text-lg">{r.staff_name||"کاربر"}</div><div className="text-sm text-[var(--text-muted)]">{r.staff_email||"—"}</div><div className="mt-2 font-mono text-sm">{r.iban}</div></div><div className="text-right lg:text-left"><div className="font-black text-xl">{money(r.amount)} ریال</div><div className="text-xs text-[var(--text-muted)]">کارمزد {money(r.fee_amount)} ریال · خالص {money(r.net_amount)} ریال</div></div><span className="rounded-full px-3 py-1 bg-[var(--surface-muted)] text-sm font-bold">{labels[r.status]||r.status}</span></div><div className="mt-4 flex flex-wrap gap-2">{r.status==="requested"&&<><TusanButton disabled={busy===r.id} onClick={()=>void action(r.id,"approve")}>تأیید درخواست</TusanButton><TusanButton variant="secondary" disabled={busy===r.id} onClick={()=>void action(r.id,"reject")}>رد</TusanButton></>}{r.status==="approved"&&<TusanButton disabled={busy===r.id} onClick={()=>void action(r.id,"processing")}>شروع پرداخت</TusanButton>}{r.status==="processing"&&<TusanButton disabled={busy===r.id} onClick={()=>void action(r.id,"paid")}>ثبت پرداخت نهایی</TusanButton>}</div></GlassPanel>)}</div>:<GlassPanel className="p-10 text-center text-[var(--text-muted)]">درخواستی برای نمایش وجود ندارد.</GlassPanel>}</div></main>;
}
