"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { supabase } from "@/lib/supabase";
import { getAdminUnreadMessagesCount } from "@/lib/notifications";
import AdminNavigation, { type AdminTab } from "@/components/admin/AdminNavigation";
import AdminStats from "@/components/admin/AdminStats";
import AdminOrderTrend from "@/components/admin/AdminOrderTrend";
import AdminRevenueStats from "@/components/admin/AdminRevenueStats";
import AdminOrderStatus, { type OrderStatusStats } from "@/components/admin/AdminOrderStatus";
import AdminTopServices, { type ServiceStat } from "@/components/admin/AdminTopServices";
import AdminRecentOrders, { type RecentOrder } from "@/components/admin/AdminRecentOrders";
import AdminUsers from "@/components/admin/AdminUsers";
import AdminMessages from "@/components/admin/AdminMessages";
import AdminReports from "@/components/admin/AdminReports";
import AdminSettings from "@/components/admin/AdminSettings";
import { GlassPanel, TusanButton, SectionHeader } from "@/components/ui";

type Stats = { totalOrders:number; todayOrders:number; processingOrders:number; totalRevenue:number; completedRevenue:number; averageOrderValue:number; usersCount:number; unreadMessages:number; completedOrders:number };
type TrendItem = { date:string; orders:number };
const DEFAULT_STATS:Stats={totalOrders:0,todayOrders:0,processingOrders:0,totalRevenue:0,completedRevenue:0,averageOrderValue:0,usersCount:0,unreadMessages:0,completedOrders:0};
const DEFAULT_ORDER_STATUSES:OrderStatusStats={registered:0,checking:0,need_documents:0,processing:0,ready:0,completed:0,cancelled:0};

export default function AdminDashboard(){
 const [activeTab,setActiveTab]=useState<AdminTab>("dashboard"); const [stats,setStats]=useState<Stats>(DEFAULT_STATS); const [orderStatuses,setOrderStatuses]=useState<OrderStatusStats>(DEFAULT_ORDER_STATUSES); const [trendDays,setTrendDays]=useState(7); const [trendData,setTrendData]=useState<TrendItem[]>([]); const [serviceStats,setServiceStats]=useState<ServiceStat[]>([]); const [recentOrders,setRecentOrders]=useState<RecentOrder[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{loadDashboard();},[]); useEffect(()=>{loadTrend(trendDays);},[trendDays]);
 async function loadDashboard(){setLoading(true);try{const todayString=new Date().toISOString().split("T")[0];const [totalOrdersRes,todayOrdersRes,processingOrdersRes,revenueRes,usersRes,unreadMessages,ordersStatusRes,completedRevenueRes,recentOrdersRes]=await Promise.all([supabase.from("orders").select("id",{count:"exact",head:true}),supabase.from("orders").select("id",{count:"exact",head:true}).gte("created_at",`${todayString}T00:00:00`).lte("created_at",`${todayString}T23:59:59`),supabase.from("orders").select("id",{count:"exact",head:true}).in("status",["checking","processing","need_documents"]),supabase.from("orders").select("price"),supabase.from("profiles").select("id",{count:"exact",head:true}),getAdminUnreadMessagesCount(),supabase.from("orders").select("status"),supabase.from("orders").select("price").eq("status","completed"),supabase.from("orders").select(`id,tracking_code,status,price,created_at,services(title,icon),profiles(full_name)`).order("created_at",{ascending:false}).limit(8)]);const allRevenue=revenueRes.data?.reduce((s,i)=>s+Number(i.price||0),0)||0;const completedRevenue=completedRevenueRes.data?.reduce((s,i)=>s+Number(i.price||0),0)||0;const completedOrders=completedRevenueRes.data?.length||0;const statusCounts={...DEFAULT_ORDER_STATUSES};ordersStatusRes.data?.forEach(o=>{const s=o.status as keyof OrderStatusStats;if(s in statusCounts)statusCounts[s]++;});const formatted:RecentOrder[]=(recentOrdersRes.data||[]).map((o:any)=>({id:o.id,tracking_code:o.tracking_code,status:o.status,price:o.price,created_at:o.created_at,serviceTitle:o.services?.title||"خدمت نامشخص",serviceIcon:o.services?.icon||"📋",customerName:o.profiles?.full_name||"---"}));setStats({totalOrders:totalOrdersRes.count||0,todayOrders:todayOrdersRes.count||0,processingOrders:processingOrdersRes.count||0,totalRevenue:allRevenue,completedRevenue,averageOrderValue:completedOrders?completedRevenue/completedOrders:0,usersCount:usersRes.count||0,unreadMessages,completedOrders});setOrderStatuses(statusCounts);setRecentOrders(formatted);await loadServiceStats();await loadTrend(trendDays);}catch(e){console.error("خطا در دریافت اطلاعات داشبورد:",e);}finally{setLoading(false);}}
 async function loadTrend(days:number){const end=new Date(),start=new Date();start.setDate(start.getDate()-days+1);start.setHours(0,0,0,0);const {data,error}=await supabase.from("orders").select("created_at").gte("created_at",start.toISOString()).lte("created_at",end.toISOString());if(error)return;const result:TrendItem[]=[];for(let i=0;i<days;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toISOString().split("T")[0];result.push({date:d.toLocaleDateString("fa-IR",{month:"numeric",day:"numeric"}),orders:data?.filter(o=>o.created_at.startsWith(key)).length||0});}setTrendData(result);}
 async function loadServiceStats(){const {data,error}=await supabase.from("orders").select(`id,price,services(id,title,icon)`);if(error)return;const map=new Map<string,ServiceStat>();data?.forEach((o:any)=>{const s=o.services;if(!s?.id)return;const e=map.get(s.id);if(e){e.orders++;e.revenue+=Number(o.price||0);}else map.set(s.id,{id:s.id,title:s.title,icon:s.icon||"📋",orders:1,revenue:Number(o.price||0)});});setServiceStats(Array.from(map.values()).sort((a,b)=>b.orders-a.orders).slice(0,5));}
 function renderDashboard(){return <div className="space-y-6"><AdminStats stats={stats} loading={loading}/><AdminOrderTrend data={trendData} days={trendDays} onDaysChange={setTrendDays}/><AdminRevenueStats stats={stats}/><AdminOrderStatus stats={orderStatuses} totalOrders={stats.totalOrders}/><AdminTopServices services={serviceStats}/><AdminRecentOrders orders={recentOrders}/><GlassPanel className="p-6 border-[var(--primary)]/20"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><h2 className="text-xl font-black">📱 مدیریت شبکه‌های اجتماعی</h2><p className="text-[var(--text-muted)] mt-1">مدیریت کاتالوگ، نام سرویس‌ها، همگام‌سازی و سفارش‌های اجتماعی.</p></div><Link href="/admin/social"><TusanButton>ورود به مدیریت شبکه‌های اجتماعی</TusanButton></Link></div></GlassPanel></div>;}
 function renderTabContent(){if(activeTab==="dashboard")return renderDashboard();if(activeTab==="orders")return <GlassPanel className="p-8"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold">مدیریت سفارش‌ها</h2><p className="text-[var(--text-muted)] mt-1">مشاهده و مدیریت سفارش‌های مشتریان</p></div><Link href="/admin/orders"><TusanButton>ورود به مدیریت سفارش‌ها</TusanButton></Link></div></GlassPanel>;if(activeTab==="services")return <GlassPanel className="p-8"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold">مدیریت خدمات</h2><p className="text-[var(--text-muted)] mt-1">مدیریت خدمات و فرم‌های قابل ارائه</p></div><Link href="/admin/services"><TusanButton>ورود به مدیریت خدمات</TusanButton></Link></div></GlassPanel>;if(activeTab==="social")return <GlassPanel className="p-8"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h2 className="text-xl font-bold">مدیریت شبکه‌های اجتماعی</h2><p className="text-[var(--text-muted)] mt-1">مدیریت نام نمایشی سرویس‌ها، همگام‌سازی FJPanel و سفارش‌های اجتماعی.</p></div><Link href="/admin/social"><TusanButton>ورود به مدیریت شبکه‌های اجتماعی</TusanButton></Link></div></GlassPanel>;if(activeTab==="users")return <AdminUsers/>;if(activeTab==="messages")return <AdminMessages/>;if(activeTab==="reports")return <AdminReports/>;if(activeTab==="settings")return <AdminSettings/>;return null;}
 function title(){return ({dashboard:"داشبورد مدیریت",orders:"مدیریت سفارش‌ها",services:"مدیریت خدمات",social:"مدیریت شبکه‌های اجتماعی",users:"مدیریت کاربران",messages:"پیام‌ها",reports:"گزارش‌ها",settings:"تنظیمات"} as Record<AdminTab,string>)[activeTab]||"داشبورد مدیریت";}
 function description(){return ({dashboard:"نمای کلی عملکرد کافی‌نت",orders:"مشاهده و مدیریت سفارش‌های مشتریان",services:"مدیریت خدمات و فرم‌های قابل ارائه",social:"مدیریت کاتالوگ و سفارش‌های خدمات شبکه‌های اجتماعی",users:"مدیریت کاربران ثبت‌نام‌شده",messages:"مدیریت پیام‌های مشتریان",reports:"گزارش‌های مالی و عملکردی",settings:"تنظیمات پنل مدیریت"} as Record<AdminTab,string>)[activeTab]||"";}
 return <div dir="rtl" className="min-h-screen page-background text-[var(--text)]"><AdminNavigation activeTab={activeTab} unreadMessages={stats.unreadMessages} onTabChange={setActiveTab}/><main className="max-w-7xl mx-auto px-3 sm:px-6 py-5 sm:py-6"><div className="mb-5"><SectionHeader title={title()} description={description()}/></div>{renderTabContent()}</main></div>;
}
