"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { GlassPanel, TusanButton } from "@/components/ui";

type RequestRow={id:string;order_id:string;staff_user_id:string;status:string;commission_percent:number;created_at:string;tracking_code?:string|null;order_status?:string|null;price?:number|null;customer?:{full_name?:string|null;phone?:string|null;email?:string|null}|null;service?:{title?:string|null;icon?:string|null}|null;staff?:{full_name?:string|null;phone?:string|null;email?:string|null}|null};
export default function OrderAssignmentRequests(){
 const [rows,setRows]=useState<RequestRow[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState("");
 async function load(){setLoading(true);setMessage("");const {data,error}=await supabase.from("order_staff_requests").select("id,order_id,staff_user_id,status,commission_percent,created_at").eq("status","pending").order("created_at",{ascending:false});if(error){setMessage(`دریافت درخواست‌های تخصیص انجام نشد: ${error.message}`);setRows([]);setLoading(false);return;}const base=data||[];const orderIds=[...new Set(base.map(r=>r.order_id))];const staffIds=[...new Set(base.map(r=>r.staff_user_id))];const [{data:orders},{data:staff}]=await Promise.all([orderIds.length?supabase.from("orders").select("id,tracking_code,status,price,user_id,service_id").in("id",orderIds):Promise.resolve({data:[]}),staffIds.length?supabase.from("profiles").select("id,full_name,phone").in("id",staffIds):Promise.resolve({data:[]})]);const customerIds=[...new Set((orders||[]).map((o:any)=>o.user_id))];const serviceIds=[...new Set((orders||[]).map((o:any)=>o.service_id))];const [{data:customers},{data:services}]=await Promise.all([customerIds.length?supabase.from("profiles").select("id,full_name,phone").in("id",customerIds):Promise.resolve({data:[]}),serviceIds.length?supabase.from("services").select("id,title,icon").in("id",serviceIds):Promise.resolve({data:[]})]);const om=new Map((orders||[]).map((x:any)=>[x.id,x]));const sm=new Map((staff||[]).map((x:any)=>[x.id,x]));const cm=new Map((customers||[]).map((x:any)=>[x.id,x]));const vm=new Map((services||[]).map((x:any)=>[x.id,x]));setRows(base.map((r:any)=>{const o=om.get(r.order_id);return {...r,tracking_code:o?.tracking_code,order_status:o?.status,price:o?.price,customer:o?cm.get(o.user_id):null,service:o?vm.get(o.service_id):null,staff:sm.get(r.staff_user_id)||null};}));setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function review(id:string,approve:boolean){setBusy(id);setMessage("");const {error}=await supabase.rpc("approve_order_assignment",{p_request_id:id,p_approve:approve});if(error)setMessage(error.message);else setMessage(approve?"درخواست تخصیص تأیید شد.":"درخواست تخصیص رد شد.");await load();setBusy(null)}
 return <section dir="rtl" className="mb-6"><GlassPanel className="p-5"><div className="flex items-center justify-between gap-3 mb-4"><div><h2 className="text-xl font-black">درخواست‌های تخصیص سفارش</h2><p className="text-sm text-[var(--text-muted)] mt-1">مدیر اصلی می‌تواند درخواست مدیران سفارشات را تأیید یا رد کند.</p></div><TusanButton variant="outline" onClick={()=>void load()}>بروزرسانی</TusanButton></div>{message&&<div className="mb-4 rounded-xl border p-3 text-sm">{message}</div>}{loading?<div className="p-6 text-center text-sm">در حال بارگذاری...</div>:rows.length===0?<div className="p-6 text-center text-sm text-[var(--text-muted)]">درخواست در انتظار تأیید وجود ندارد.</div>:<div className="space-y-3">{rows.map(r=><div key={r.id} className="rounded-xl border p-4"><div className="grid gap-3 md:grid-cols-4"><div><div className="text-xs text-[var(--text-muted)]">سفارش</div><b>{r.service?.icon||"📋"} {r.service?.title||"خدمت"}</b><div className="text-xs mt-1">{r.tracking_code||"---"}</div></div><div><div className="text-xs text-[var(--text-muted)]">مشتری</div><b>{r.customer?.full_name||r.customer?.phone||"---"}</b></div><div><div className="text-xs text-[var(--text-muted)]">درخواست‌دهنده</div><b>{r.staff?.full_name||r.staff?.phone||"---"}</b></div><div><div className="text-xs text-[var(--text-muted)]">مبلغ / کارمزد</div><b>{Number(r.price||0).toLocaleString("fa-IR")} تومان</b><div className="text-xs mt-1">{Number(r.commission_percent||0).toLocaleString("fa-IR")}٪</div></div></div><div className="mt-4 flex flex-wrap gap-2"><TusanButton onClick={()=>void review(r.id,true)} disabled={busy===r.id}>{busy===r.id?"در حال بررسی...":"تأیید تخصیص"}</TusanButton><TusanButton variant="secondary" onClick={()=>void review(r.id,false)} disabled={busy===r.id}>رد درخواست</TusanButton></div></div>)}</div>}</GlassPanel></section>
}
