"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { GlassPanel, SectionHeader } from "@/components/ui";
import { supabase } from "@/lib/supabase";

type Request={id:string;order_id:string;staff_user_id:string;status:string;commission_percent:number;created_at:string;orders?:{tracking_code?:string|null;price?:number|null;services?:{title?:string|null;icon?:string|null}|null;profiles?:{full_name?:string|null;phone?:string|null}|null}|null;profiles?:{full_name?:string|null;phone?:string|null}|null};

export default function OrderApprovals(){const [rows,setRows]=useState<Request[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);const {data,error:e}=await supabase.from("order_staff_requests").select("id,order_id,staff_user_id,status,commission_percent,created_at,profiles!order_staff_requests_staff_user_id_fkey(full_name,phone),orders(tracking_code,price,services(title,icon),profiles(full_name,phone))").eq("status","pending").order("created_at",{ascending:true});if(e)setError(e.message);else setRows((data||[]) as Request[]);setLoading(false)}
 async function decide(id:string,approve:boolean){setError("");const {error:e}=await supabase.rpc("approve_order_assignment",{p_request_id:id,p_approve:approve,p_commission:null});if(e)setError(e.message);else await load()}
 return <main dir="rtl" className="min-h-screen page-background p-4 sm:p-6 text-[var(--text)]"><div className="mx-auto max-w-6xl space-y-6"><div className="flex items-center justify-between"><SectionHeader title="تأیید تخصیص سفارش‌ها" description="درخواست‌های مدیران سفارشات برای دریافت و انجام خدمات"/><Link href="/admin" className="text-sm font-bold text-[var(--primary)]">بازگشت به پنل ←</Link></div>{error&&<GlassPanel className="p-4 text-sm text-red-600">{error}</GlassPanel>}{loading?<GlassPanel className="p-10 text-center">در حال بارگذاری...</GlassPanel>:rows.length===0?<GlassPanel className="p-10 text-center text-[var(--text-muted)]">درخواست تأییدنشده‌ای وجود ندارد.</GlassPanel>:rows.map(r=><GlassPanel key={r.id} className="p-5"><div className="grid gap-4 md:grid-cols-2"><div><div className="font-black">{r.orders?.services?.icon} {r.orders?.services?.title||"خدمت"}</div><div className="mt-2 text-sm">کد پیگیری: {r.orders?.tracking_code||"---"}</div><div className="mt-1 text-sm text-[var(--text-muted)]">مشتری: {r.orders?.profiles?.full_name||"---"} · {r.orders?.profiles?.phone||"---"}</div></div><div><div className="font-black">درخواست‌کننده: {r.profiles?.full_name||"مدیر سفارشات"}</div><div className="mt-1 text-sm text-[var(--text-muted)]">کارمزد پیشنهادی: {Number(r.commission_percent).toLocaleString("fa-IR")}%</div><div className="mt-1 text-xs text-[var(--text-muted)]">{new Date(r.created_at).toLocaleString("fa-IR")}</div></div></div><div className="mt-5 flex gap-2"><button onClick={()=>void decide(r.id,true)} className="rounded-xl bg-green-600 px-5 py-2.5 text-sm font-black text-white">تأیید و تخصیص</button><button onClick={()=>void decide(r.id,false)} className="rounded-xl bg-red-500/10 px-5 py-2.5 text-sm font-black text-red-600">رد درخواست</button></div></GlassPanel>)}</div></main>;
}
